release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG   # Run this job when a tag is created manually
  script:
    - echo 'running release_job'
  release:
    name: 'Asqatasun $CI_COMMIT_TAG'
    description: 'Asqatasun $CI_COMMIT_TAG description'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
