image: maven:3.6-openjdk-8

stages:
  - .pre
  - build
  - test
  - deploy
  - .post

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  WEBAPP_ARTIFACT_DIR: web-app/asqatasun-web-app/target
  REST_SERVER_ARTIFACT_DIR: server/asqatasun-server/target

cache:
  paths:
    - .m2/repository/

include:
  #  - local: /.gitlab/ci/10-.pre/10_lint.gitlab-ci.yml
  - local: /.gitlab/ci/10_.pre/00_prepare.gitlab-ci.yml
  - local: /.gitlab/ci/10_.pre/lint_mvn.gitlab-ci.yml
  - local: /.gitlab/ci/20_build/build.gitlab-ci.yml
  - local: /.gitlab/ci/30_test/test.gitlab-ci.yml
#  - local: /.gitlab/ci/40_deploy/10_release.gitlab-ci.yml
  - local: /.gitlab/ci/40_deploy/20_upload_artefacts.gitlab-ci.yml






