version: "3.8"
services:
  # Mail catcher: email testing tool for developers
  ###############################################################################################################
  # MAILHOG  https://github.com/mailhog/MailHog
  #          https://hub.docker.com/r/mailhog/mailhog
  #
  # - SMTP port: 1025
  # - HTTP port: 8025
  # - HTTP URL:  http://localhost:8025     By default
  #              http://<host_ip>:8025     By default
  #              http://<host_ip>:<port>   If you use the .env configuration file
  ###############################################################################################################
  asqatasun-mailhog:
    image: "mailhog/mailhog"
    ports:
      - "${MAILHOG_SMTP_IP:-127.0.0.1}:${MAILHOG_SMTP_PORT:-1025}:1025"
      - "${MAILHOG_HTTP_IP:-0.0.0.0}:${MAILHOG_HTTP_PORT:-8025}:8025"

  # Asqatasun database
  ###############################################################################################################
  # - port: 3306
  # - URL:  jdbc:mysql://localhost:3306/asqatasun     By default
  #         jdbc:mysql://<host_ip>:3306/asqatasun     By default
  #         jdbc:mysql://<host_ip>:<port>/asqatasun   If you use the .env configuration file
  ###############################################################################################################
  asqatasun-db_dev:
    image: "${DB_IMAGE:-mysql:5.7}"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER:     "${DB_USER:-asqatasunDatabaseUserLogin}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-asqatasunDatabaseUserP4ssword}"
      MYSQL_DATABASE: "${DB_DATABASE:-asqatasun}"
    ports:
      - "${DB_HOST_IP:-0.0.0.0}:${DB_HOST_PORT:-3306}:${DB_PORT:-3306}"

  # Asqatasun webapp
  ###############################################################################################################
  # - port: 8080
  # - URL:  http://localhost:8080     By default
  #         http://<host_ip>:8080     By default
  #         http://<host_ip>:<port>   If you use the .env configuration file
  ##############################################################################################################
  asqatasun-webapp_dev:
    build: .
    links:
      - asqatasun-db_dev
      - asqatasun-mailhog
    depends_on:
      - asqatasun-db_dev
    environment:
      WEBAPP_URL:    "${WEBAPP_URL:-http://localhost:8080/}"
      DB_DRIVER:     "${DB_DRIVER:-mysql}"
      DB_PORT:       "${DB_PORT:-3306}"
      DB_HOST:       "${DB_HOST:-asqatasun-db_dev}"
      DB_USER:       "${DB_USER:-asqatasunDatabaseUserLogin}"
      DB_PASSWORD:   "${DB_PASSWORD:-asqatasunDatabaseUserP4ssword}"
      DB_DATABASE:   "${DB_DATABASE:-asqatasun}"
      SMTP_DEBUG:    "${SMTP_DEBUG:-false}"
      SMTP_FROM:     "${SMTP_FROM:-from-asqatsun@example.com}"
      SMTP_HOST:     "${SMTP_HOST:-asqatasun-mailhog}"
      SMTP_PORT:     "${SMTP_PORT:-1025}"
      SMTP_USER:     "${SMTP_USER:-}"
      SMTP_PASSWORD: "${SMTP_PASSWORD:-}"
      SMTP_STARTLS_ENABLE:  "${SMTP_STARTLS_ENABLE:-false}"
      SMTP_SSL_ENABLE:      "${SMTP_SSL_ENABLE:-false}"  # If true then SMTP_STARTLS_ENABLE is not taken into account
      SMTP_SSL_PROTOCOLS:   "${SMTP_SSL_PROTOCOLS:-TLSv1.2}"
    ports:
      - "${APP_HOST_IP:-0.0.0.0}:${APP_HOST_PORT:-8080}:8080"
