---
- name: Set Postfix options
  debconf: 
    name: postifx 
    question: "{{ item.question }}" 
    value: "{{ item.value }} " 
    vtype: "string"
  with_items:
    - { question: "postfix/mailname", value: " " }
    - { question: "postfix/main_mailer_type", value: "Satellite system" }

- name: Update locale Setting
  locale_gen:
    name: "{{ locale }}"
    state: present
  register: set_locale

- name: Reconfigure locale
  command: dpkg-reconfigure locales
  when: set_locale.changed

- name: Update the Ubuntu repos
  apt: 
    update_cache: yes 

- name: Install the Asqatasun Prerequisites
  apt: 
    name: "{{ item }}" 
    update_cache: yes 
    state: installed
  with_items: asqatasun_debian_pkgs

- name: Copy the asqatasun.cnf template to /etc/mysql/conf.d
  template:
    dest: /etc/mysql/conf.d/asqatasun.cnf
    src: asqatasun.cnf.j2
    owner: root
    group: root
  notify:
    - Restart MySQL
    
- name: Create a soft link for tomcat jar and mysql connector
  file:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    state: link
  with_items:
    - { src: '/usr/share/java/spring3-instrument-tomcat.jar', dest: '/usr/share/tomcat7/lib/spring3-instrument-tomcat.jar' }
    - { src: '/usr/share/java/mysql-connector-java.jar', dest: '/usr/share/tomcat7/lib/mysql-connector-java.jar'}

- name: Copy the xvfb template to /etc/init.d
  template:
    dest: /etc/init.d/xvfb
    src: xvfb.j2
    owner: root
    group: root
    mode: 755
  register: xvfb
  notify:
    - Restart xvfb

- name: Configure xvfb to run at startup
  command: update-rc.d xvfb defaults
  ignore_errors: yes
  when: xvfb.changed

- name: Download the latest ESR Firfox
  get_url: 
    url: "{{ fixfox_esr_link }}" 
    dest: "/tmp/{{ fixfox_esr_link | basename }}"

- name: Unzip the downloaded Firfox zipped file
  unarchive: 
    src: "/tmp/{{ fixfox_esr_link | basename }}" 
    dest: /opt 
    copy: no

- name: Download the latest Asqatasun tarball
  get_url: 
    url: "{{ asqatasun_download_link }}" 
    dest: "/tmp/{{ asqatasun_download_link | basename }}"

- name: Unzip the downloaded Asqatasun tarball
  unarchive: 
    src: "/tmp/{{ asqatasun_download_link | basename }}" 
    dest: "/tmp/" 
    copy: no

- name: Create MySQL database for Asqatasun
  mysql_db: 
    name: "{{ asqatasun_parameters.db_name }}"
    state: present 
    encoding: utf8
    collation: utf8_general_ci

- name: Create MySQL user for Asqatasun
  mysql_user: 
    name: "{{ asqatasun_parameters.db_user }}"
    password: "{{ asqatasun_parameters.db_password }}"
    host: "{{ asqatasun_parameters.db_host }}"  
    priv: "{{ asqatasun_parameters.db_name }}.*:ALL"
    state: present

- name: Check that asqatasun app is running
  shell: >
    /bin/ps aux | grep -i asqatasun
  register: asqatasun_app
  changed_when: no

- name: Install the Asqatasun
  shell: >
    /bin/echo "yes" | ./install.sh --database-user "{{ asqatasun_parameters.db_user }}" \
    --database-passwd "{{ asqatasun_parameters.db_password }}" \
    --database-db "{{ asqatasun_parameters.db_name }}" \ 
    --database-host "{{ asqatasun_parameters.db_host }}" \ 
    --asqatasun-url http://localhost:8080/asqatasun/ \
    --tomcat-webapps /var/lib/tomcat7/webapps/ \
    --tomcat-user tomcat7 \
    --asqa-admin-email "{{ asqatasun_parameters.admin_email }}" \
    --asqa-admin-passwd "{{ asqatasun_parameters.admin_passwd }}" \ 
    --firefox-esr-binary-path /opt/firefox-esr/firefox 
    --display-port ":99"
  args:
    chdir: "/tmp/{{ asqatasun_version }}.i386"
  when: "asqatasun_app.stdout.find('/etc/asqatasun') == -1"
  notify:
    - Restart Tomcat7

