START TRANSACTION;
SET standard_conforming_strings=off;
SET escape_string_warning=off;
SET CONSTRAINTS ALL DEFERRED;


INSERT INTO "reference" VALUES 
(2,'RGAA22',NULL,'Rgaa 2.2',2,'www.references.modernisation.gouv.fr/sites/default/files/RGAA_v2.2.1.pdf',2 );


INSERT INTO "theme" VALUES 
(101,'RGAA22-1','http://rgaa.net/-Cadres-.html','Cadres',1),
(102,'RGAA22-2','http://rgaa.net/-Couleurs-.html','Couleurs',2),
(103,'RGAA22-3','http://rgaa.net/-Formulaires-.html','Formulaires',3),
(104,'RGAA22-4','http://rgaa.net/-Images-.html','Images',4),
(105,'RGAA22-5','http://rgaa.net/-Multimedia-.html','Multimédia',5),
(106,'RGAA22-6','http://rgaa.net/-Navigation-.html','Navigation',6),
(107,'RGAA22-7','http://rgaa.net/-presentation-.html','Présentation',7),
(108,'RGAA22-8','http://rgaa.net/-Scripts-.html','Scripts',8),
(109,'RGAA22-9','http://rgaa.net/-Standards-.html','Standards',9),
(110,'RGAA22-10','http://rgaa.net/-Structure-.html','Structure',10),
(111,'RGAA22-11','http://rgaa.net/-Tableaux-.html','Tableaux',11),
(112,'RGAA22-12','http://rgaa.net/-Textes-.html','Textes',12);


INSERT INTO "criterion" VALUES 
(2001,'Rgaa22-0101','','1.1',2010101,'http://rgaa.net/1-1-Absence-de-cadres-non-titres.html',2,101),
(2002,'Rgaa22-0102','','1.2',2010201,'http://rgaa.net/Pertinence-des-titres-donnes-aux.html',2,101),
(2003,'Rgaa22-0201','','2.1',2020101,'http://rgaa.net/presence-d-un-autre-moyen-que-la.html',2,102),
(2004,'Rgaa22-0202','','2.2',2020201,'http://rgaa.net/presence-d-un-autre-moyen-que-la,4.html',2,102),
(2005,'Rgaa22-0203','','2.3',2020301,'http://rgaa.net/presence-d-un-moyen-de.html',2,102),
(2006,'Rgaa22-0204','','2.4',2020401,'http://rgaa.net/presence-d-un-moyen-de,6.html',2,102),
(2007,'Rgaa22-0205','','2.5',2020501,'http://rgaa.net/Valeur-du-rapport-de-contraste-du.html',2,102),
(2008,'Rgaa22-0206','','2.6',2020601,'http://rgaa.net/Valeur-du-rapport-de-contraste-du,8.html',2,102),
(2009,'Rgaa22-0207','','2.7',2020701,'http://rgaa.net/Valeur-du-rapport-de-contraste-du,9.html',2,102),
(2010,'Rgaa22-0208','','2.8',2020801,'http://rgaa.net/Valeur-du-rapport-de-contraste-du,10.html',2,102),
(2011,'Rgaa22-0209','','2.9',2020901,'http://rgaa.net/Valeur-du-rapport-de-contraste-du,11.html',2,102),
(2012,'Rgaa22-0210','','2.10',2021001,'http://rgaa.net/Valeur-du-rapport-de-contraste-du,12.html',2,102),
(2013,'Rgaa22-0211','','2.11',2021101,'http://rgaa.net/Valeur-du-rapport-de-contraste-du,13.html',2,102),
(2014,'Rgaa22-0212','','2.12',2021201,'http://rgaa.net/Valeur-du-rapport-de-contraste-du,14.html',2,102),
(2015,'Rgaa22-0213','','2.13',2021301,'http://rgaa.net/Valeur-du-rapport-de-contraste-du,15.html',2,102),
(2016,'Rgaa22-0214','','2.14',2021401,'http://rgaa.net/Valeur-du-rapport-de-contraste-du,16.html',2,102),
(2017,'Rgaa22-0215','','2.15',2021501,'http://rgaa.net/Valeur-du-rapport-de-contraste-du,17.html',2,102),
(2018,'Rgaa22-0216','','2.16',2021601,'http://rgaa.net/Valeur-du-rapport-de-contraste-du,18.html',2,102),
(2019,'Rgaa22-0301','','3.1',2030101,'http://rgaa.net/Possibilite-d-identifier-les.html',2,103),
(2020,'Rgaa22-0302','','3.2',2030201,'http://rgaa.net/presence-d-information-prealable.html',2,103),
(2021,'Rgaa22-0303','','3.3',2030301,'http://rgaa.net/Positionnement-correct-des.html',2,103),
(2022,'Rgaa22-0304','','3.4',2030401,'http://rgaa.net/Regroupement-d-elements-de.html',2,103),
(2023,'Rgaa22-0305','','3.5',2030501,'http://rgaa.net/Absence-d-element-fieldset-sans.html',2,103),
(2024,'Rgaa22-0306','','3.6',2030601,'http://rgaa.net/Pertinence-du-contenu-de-l-element.html',2,103),
(2025,'Rgaa22-0307','','3.7',2030701,'http://rgaa.net/Regroupement-d-elements-option.html',2,103),
(2026,'Rgaa22-0308','','3.8',2030801,'http://rgaa.net/presence-d-un-attribut-label-sur-l.html',2,103),
(2027,'Rgaa22-0309','','3.9',2030901,'http://rgaa.net/Pertinence-du-contenu-de-l.html',2,103),
(2028,'Rgaa22-0310','','3.10',2031001,'http://rgaa.net/Absence-d-element-de-formulaire.html',2,103),
(2029,'Rgaa22-0311','','3.11',2031101,'http://rgaa.net/Absence-d-element-de-formulaire,29.html',2,103),
(2030,'Rgaa22-0312','','3.12',2031201,'http://rgaa.net/Pertinence-des-etiquettes-d.html',2,103),
(2031,'Rgaa22-0313','','3.13',2031301,'http://rgaa.net/presence-d-informations-ou-de.html',2,103),
(2032,'Rgaa22-0314','','3.14',2031401,'http://rgaa.net/presence-de-mecanismes-permettant.html',2,103),
(2033,'Rgaa22-0315','','3.15',2031501,'http://rgaa.net/presence-de-mecanismes-permettant,33.html',2,103),
(2034,'Rgaa22-0316','','3.16',2031601,'http://rgaa.net/presence-d-une-page-d-aide-ou-d-un.html',2,103),
(2035,'Rgaa22-0401','','4.1',2040101,'http://rgaa.net/presence-de-l-attribut-alt.html',2,104),
(2036,'Rgaa22-0402','','4.2',2040201,'http://rgaa.net/Pertinence-de-l-alternative.html',2,104),
(2037,'Rgaa22-0403','','4.3',2040301,'http://rgaa.net/Pertinence-de-l-alternative,37.html',2,104),
(2038,'Rgaa22-0404','','4.4',2040401,'http://rgaa.net/Pertinence-de-l-alternative,38.html',2,104),
(2039,'Rgaa22-0405','','4.5',2040501,'http://rgaa.net/Pertinence-de-l-alternative-vide.html',2,104),
(2040,'Rgaa22-0406','','4.6',2040601,'http://rgaa.net/longueur-du-contenu-des.html',2,104),
(2041,'Rgaa22-0407','','4.7',2040701,'http://rgaa.net/Existence-d-une-description-longue.html',2,104),
(2042,'Rgaa22-0408','','4.8',2040801,'http://rgaa.net/Pertinence-de-la-description.html',2,104),
(2043,'Rgaa22-0409','','4.9',2040901,'http://rgaa.net/presence-de-l-attribut-longdesc.html',2,104),
(2044,'Rgaa22-0410','','4.10',2041001,'http://rgaa.net/presence-d-une-information-de.html',2,104),
(2045,'Rgaa22-0411','','4.11',2041101,'http://rgaa.net/Coherence-dans-l-identification.html',2,104),
(2046,'Rgaa22-0501','','5.1',2050101,'http://rgaa.net/Acces-a-une-information.html',2,105),
(2047,'Rgaa22-0502','','5.2',2050201,'http://rgaa.net/presence-de-la-transcription.html',2,105),
(2048,'Rgaa22-0503','','5.3',2050301,'http://rgaa.net/Pertinence-de-la-transcription.html',2,105),
(2049,'Rgaa22-0504','','5.4',2050401,'http://rgaa.net/presence-d-une-description-audio.html',2,105),
(2050,'Rgaa22-0505','','5.5',2050501,'http://rgaa.net/Pertinence-de-la-description-audio.html',2,105),
(2051,'Rgaa22-0506','','5.6',2050601,'http://rgaa.net/Possibilite-de-controler-l.html',2,105),
(2052,'Rgaa22-0507','','5.7',2050701,'http://rgaa.net/presence-d-une-description-audio,52.html',2,105),
(2053,'Rgaa22-0508','','5.8',2050801,'http://rgaa.net/presence-d-une-description-audio,53.html',2,105),
(2054,'Rgaa22-0509','','5.9',2050901,'http://rgaa.net/presence-du-sous-titrage.html',2,105),
(2055,'Rgaa22-0510','','5.10',2051001,'http://rgaa.net/Pertinence-du-sous-titrage.html',2,105),
(2056,'Rgaa22-0511','','5.11',2051101,'http://rgaa.net/presence-d-une-alternative-aux.html',2,105),
(2057,'Rgaa22-0512','','5.12',2051201,'http://rgaa.net/presence-d-une-alternative-aux,57.html',2,105),
(2058,'Rgaa22-0513','','5.13',2051301,'http://rgaa.net/Absence-d-elements-provoquant-des.html',2,105),
(2059,'Rgaa22-0514','','5.14',2051401,'http://rgaa.net/Absence-de-code-javascript,59.html',2,105),
(2060,'Rgaa22-0515','','5.15',2051501,'http://rgaa.net/Absence-de-mise-en-forme.html',2,105),
(2061,'Rgaa22-0516','','5.16',2051601,'http://rgaa.net/Compatibilite-des-elements.html',2,105),
(2062,'Rgaa22-0517','','5.17',2051701,'http://rgaa.net/Absence-totale-de-changements.html',2,105),
(2063,'Rgaa22-0518','','5.18',2051801,'http://rgaa.net/presence-du-sous-titrage,63.html',2,105),
(2064,'Rgaa22-0519','','5.19',2051901,'http://rgaa.net/Absence-de-l-element-blink.html',2,105),
(2065,'Rgaa22-0520','','5.20',2052001,'http://rgaa.net/Absence-d-elements-provoquant-des,65.html',2,105),
(2066,'Rgaa22-0521','','5.21',2052101,'http://rgaa.net/Absence-de-code-javascript,66.html',2,105),
(2067,'Rgaa22-0522','','5.22',2052201,'http://rgaa.net/Absence-de-mise-en-forme,67.html',2,105),
(2068,'Rgaa22-0523','','5.23',2052301,'http://rgaa.net/Absence-d-element-marquee.html',2,105),
(2069,'Rgaa22-0524','','5.24',2052401,'http://rgaa.net/Absence-d-elements-affichant-des.html',2,105),
(2070,'Rgaa22-0525','','5.25',2052501,'http://rgaa.net/Absence-de-code-javascript,70.html',2,105),
(2071,'Rgaa22-0526','','5.26',2052601,'http://rgaa.net/Absence-de-mise-en-forme,71.html',2,105),
(2072,'Rgaa22-0527','','5.27',2052701,'http://rgaa.net/Independance-du-peripherique-d.html',2,105),
(2073,'Rgaa22-0528','','5.28',2052801,'http://rgaa.net/presence-d-une-alternative-aux,73.html',2,105),
(2074,'Rgaa22-0529','','5.29',2052901,'http://rgaa.net/Absence-d-elements-declenchant-la.html',2,105),
(2075,'Rgaa22-0530','','5.30',2053001,'http://rgaa.net/Absence-d-element-bgsound.html',2,105),
(2076,'Rgaa22-0531','','5.31',2053101,'http://rgaa.net/presence-de-version-en-langue-des.html',2,105),
(2077,'Rgaa22-0532','','5.32',2053201,'http://rgaa.net/Pertinence-de-la-version-en-langue.html',2,105),
(2078,'Rgaa22-0533','','5.33',2053301,'http://rgaa.net/Niveau-sonore-de-la-piste-de.html',2,105),
(2079,'Rgaa22-0534','','5.34',2053401,'http://rgaa.net/presence-d-un-mecanisme-pour.html',2,105),
(2080,'Rgaa22-0601','','6.1',2060101,'http://rgaa.net/Acces-aux-ens-textuels-doublant.html',2,106),
(2081,'Rgaa22-0602','','6.2',2060201,'http://rgaa.net/presence-d-un-avertissement.html',2,106),
(2082,'Rgaa22-0603','','6.3',2060301,'http://rgaa.net/presence-d-un-avertissement,82.html',2,106),
(2083,'Rgaa22-0604','','6.4',2060401,'http://rgaa.net/presence-d-un-avertissement,83.html',2,106),
(2084,'Rgaa22-0605','','6.5',2060501,'http://rgaa.net/Absence-d-ouverture-de-nouvelles.html',2,106),
(2085,'Rgaa22-0606','','6.6',2060601,'http://rgaa.net/Absence-de-piege-lors-de-la.html',2,106),
(2086,'Rgaa22-0607','','6.7',2060701,'http://rgaa.net/Absence-d-element-meta-provoquant.html',2,106),
(2087,'Rgaa22-0608','','6.8',2060801,'http://rgaa.net/Absence-de-code-javascript.html',2,106),
(2088,'Rgaa22-0609','','6.9',2060901,'http://rgaa.net/Absence-d-elements-provoquant-un.html',2,106),
(2089,'Rgaa22-0610','','6.10',2061001,'http://rgaa.net/Absence-d-element-meta-provoquant,89.html',2,106),
(2090,'Rgaa22-0611','','6.11',2061101,'http://rgaa.net/Absence-de-code-javascript,90.html',2,106),
(2091,'Rgaa22-0612','','6.12',2061201,'http://rgaa.net/Absence-d-elements-provoquant-une.html',2,106),
(2092,'Rgaa22-0613','','6.13',2061301,'http://rgaa.net/Possibite-d-identifier-la.html',2,106),
(2093,'Rgaa22-0614','','6.14',2061401,'http://rgaa.net/Possibite-d-identifier-la,93.html',2,106),
(2094,'Rgaa22-0615','','6.15',2061501,'http://rgaa.net/Coherence-de-la-destination-ou-de.html',2,106),
(2095,'Rgaa22-0616','','6.16',2061601,'http://rgaa.net/Absence-de-ens-sans-intitule.html',2,106),
(2096,'Rgaa22-0617','','6.17',2061701,'http://rgaa.net/presence-d-une-page-contenant-le.html',2,106),
(2097,'Rgaa22-0618','','6.18',2061801,'http://rgaa.net/Coherence-du-plan-du-site.html',2,106),
(2098,'Rgaa22-0619','','6.19',2061901,'http://rgaa.net/presence-d-un-acces-a-la-page.html',2,106),
(2099,'Rgaa22-0620','','6.20',2062001,'http://rgaa.net/presence-d-un-fil-d-ariane.html',2,106),
(2100,'Rgaa22-0621','','6.21',2062101,'http://rgaa.net/presence-de-menus-ou-de-barres-de.html',2,106),
(2101,'Rgaa22-0622','','6.22',2062201,'http://rgaa.net/Coherence-de-la-position-des-menus.html',2,106),
(2102,'Rgaa22-0623','','6.23',2062301,'http://rgaa.net/Coherence-de-la-presentation-des.html',2,106),
(2103,'Rgaa22-0624','','6.24',2062401,'http://rgaa.net/Navigation-au-clavier-dans-un.html',2,106),
(2104,'Rgaa22-0625','','6.25',2062501,'http://rgaa.net/presence-d-un-avertissement,104.html',2,106),
(2105,'Rgaa22-0626','','6.26',2062601,'http://rgaa.net/presence-des-informations-de.html',2,106),
(2106,'Rgaa22-0627','','6.27',2062701,'http://rgaa.net/presence-des-informations-de-poids.html',2,106),
(2107,'Rgaa22-0628','','6.28',2062801,'http://rgaa.net/presence-des-informations-de,107.html',2,106),
(2108,'Rgaa22-0629','','6.29',2062901,'http://rgaa.net/presence-de-regroupement-pour-les.html',2,106),
(2109,'Rgaa22-0630','','6.30',2063001,'http://rgaa.net/presence-d-un-basage-permettant.html',2,106),
(2110,'Rgaa22-0631','','6.31',2063101,'http://rgaa.net/presence-de-ens-d-evitement-ou-d.html',2,106),
(2111,'Rgaa22-0632','','6.32',2063201,'http://rgaa.net/Coherence-des-ens-d-evitement-ou.html',2,106),
(2112,'Rgaa22-0633','','6.33',2063301,'http://rgaa.net/Ordre-des-liens-d-evitement-ou-d.html',2,106),
(2113,'Rgaa22-0634','','6.34',2063401,'http://rgaa.net/presence-d-un-moteur-de-recherche.html',2,106),
(2114,'Rgaa22-0635','','6.35',2063501,'http://rgaa.net/Possibilite-de-naviguer-facilement.html',2,106),
(2115,'Rgaa22-0636','','6.36',2063601,'http://rgaa.net/presence-d-une-indication-de-la.html',2,106),
(2116,'Rgaa22-0701','','7.1',2070101,'http://rgaa.net/Absence-de-generation-de-contenus.html',2,107),
(2117,'Rgaa22-0702','','7.2',2070201,'http://rgaa.net/Absence-d-alteration-de-la.html',2,107),
(2118,'Rgaa22-0703','','7.3',2070301,'http://rgaa.net/Lisibilite-des-informations.html',2,107),
(2119,'Rgaa22-0704','','7.4',2070401,'http://rgaa.net/Absence-d-espaces-utilises-pour.html',2,107),
(2120,'Rgaa22-0705','','7.5',2070501,'http://rgaa.net/Absence-de-definition-d-une.html',2,107),
(2121,'Rgaa22-0706','','7.6',2070601,'http://rgaa.net/Possibilite-de-remplacer-les.html',2,107),
(2122,'Rgaa22-0707','','7.7',2070701,'http://rgaa.net/Possibilite-de-remplacer-les,122.html',2,107),
(2123,'Rgaa22-0708','','7.8',2070801,'http://rgaa.net/Absence-d-attributs-ou-d-elements.html',2,107),
(2124,'Rgaa22-0709','','7.9',2070901,'http://rgaa.net/Absence-d-elements-HTML-utilises-a.html',2,107),
(2125,'Rgaa22-0710','','7.10',2071001,'http://rgaa.net/Maintien-de-la-distinction.html',2,107),
(2126,'Rgaa22-0711','','7.11',2071101,'http://rgaa.net/Absence-de-suppression-de-l-effet.html',2,107),
(2127,'Rgaa22-0712','','7.12',2071201,'http://rgaa.net/Absence-de-justification-du-texte.html',2,107),
(2128,'Rgaa22-0713','','7.13',2071301,'http://rgaa.net/Lisibilite-du-document-en-cas-d.html',2,107),
(2129,'Rgaa22-0714','','7.14',2071401,'http://rgaa.net/Absence-d-unites-absolues-ou-de.html',2,107),
(2130,'Rgaa22-0715','','7.15',2071501,'http://rgaa.net/Absence-d-apparition-de-barre-de.html',2,107),
(2131,'Rgaa22-0716','','7.16',2071601,'http://rgaa.net/Largeur-des-blocs-de-textes.html',2,107),
(2132,'Rgaa22-0717','','7.17',2071701,'http://rgaa.net/Valeur-de-l-espace-entre-les.html',2,107),
(2133,'Rgaa22-0718','','7.18',2071801,'http://rgaa.net/Restitution-correcte-dans-les.html',2,107),
(2134,'Rgaa22-0801','','8.1',2080101,'http://rgaa.net/Mise-a-jour-des-alternatives-aux.html',2,108),
(2135,'Rgaa22-0802','','8.2',2080201,'http://rgaa.net/Universalite-du-gestionnaire-d.html',2,108),
(2136,'Rgaa22-0803','','8.3',2080301,'http://rgaa.net/Universalite-des-gestionnaires-d.html',2,108),
(2137,'Rgaa22-0804','','8.4',2080401,'http://rgaa.net/Possibilite-de-desactiver-toute.html',2,108),
(2138,'Rgaa22-0805','','8.5',2080501,'http://rgaa.net/Absence-de-changements-de-contexte.html',2,108),
(2139,'Rgaa22-0806','','8.6',2080601,'http://rgaa.net/Ordre-d-acces-au-clavier-aux.html',2,108),
(2140,'Rgaa22-0807','','8.7',2080701,'http://rgaa.net/Utilisation-correcte-du-role-des.html',2,108),
(2141,'Rgaa22-0808','','8.8',2080801,'http://rgaa.net/presence-d-une-alternative-au-code.html',2,108),
(2142,'Rgaa22-0809','','8.9',2080901,'http://rgaa.net/Absence-de-suppression-du-focus.html',2,108),
(2143,'Rgaa22-0810','','8.10',2080101,'http://rgaa.net/Absence-de-limite-de-temps-pour.html',2,108),
(2144,'Rgaa22-0811','','8.11',2080111,'http://rgaa.net/Absence-de-perte-d-informations.html',2,108),
(2145,'Rgaa22-0812','','8.12',2080121,'http://rgaa.net/presence-d-une-alternative-au-code,145.html',2,108),
(2146,'Rgaa22-0813','','8.13',2080131,'http://rgaa.net/Accessibilite-des-contenus.html',2,108),
(2147,'Rgaa22-0901','','9.1',2090101,'http://rgaa.net/presence-de-la-declaration-d.html',2,109),
(2148,'Rgaa22-0902','','9.2',2090201,'http://rgaa.net/Conformite-de-la-position-de-la.html',2,109),
(2149,'Rgaa22-0903','','9.3',2090301,'http://rgaa.net/Conformite-syntaxique-de-la.html',2,109),
(2150,'Rgaa22-0904','','9.4',2090401,'http://rgaa.net/Validite-du-code-HTML-XHTML-au.html',2,109),
(2151,'Rgaa22-0905','','9.5',2090501,'http://rgaa.net/Absence-de-composants-obsoletes.html',2,109),
(2152,'Rgaa22-0906','','9.6',2090601,'http://rgaa.net/presence-d-un-titre-dans-la-page.html',2,109),
(2153,'Rgaa22-0907','','9.7',2090701,'http://rgaa.net/Pertinence-du-titre-de-la-page.html',2,109),
(2154,'Rgaa22-0908','','9.8',2090801,'http://rgaa.net/presence-d-une-langue-de.html',2,109),
(2155,'Rgaa22-1001','','10.1',2100101,'http://rgaa.net/presence-d-au-moins-un-titre-de.html',2,110),
(2156,'Rgaa22-1002','','10.2',2100201,'http://rgaa.net/Pertinence-du-contenu-des-titres.html',2,110),
(2157,'Rgaa22-1003','','10.3',2100301,'http://rgaa.net/Absence-d-interruption-dans-la.html',2,110),
(2158,'Rgaa22-1004','','10.4',2100401,'http://rgaa.net/presence-d-une-hierarchie-de.html',2,110),
(2159,'Rgaa22-1005','','10.5',2100501,'http://rgaa.net/Absence-de-simulation-visuelle-de.html',2,110),
(2160,'Rgaa22-1006','','10.6',2100601,'http://rgaa.net/Utilisation-systematique-de-listes.html',2,110),
(2161,'Rgaa22-1007','','10.7',2100701,'http://rgaa.net/Balisage-correct-des-listes-de.html',2,110),
(2162,'Rgaa22-1008','','10.8',2100801,'http://rgaa.net/Balisage-correct-des-citations.html',2,110),
(2163,'Rgaa22-1009','','10.9',2100901,'http://rgaa.net/Balisage-correct-des-abreviations.html',2,110),
(2164,'Rgaa22-1010','','10.10',2101001,'http://rgaa.net/Balisage-correct-des-acronymes.html',2,110),
(2165,'Rgaa22-1011','','10.11',2101101,'http://rgaa.net/Pertinence-de-la-version-non.html',2,110),
(2166,'Rgaa22-1012','','10.12',2101201,'http://rgaa.net/Pertinence-de-la-version-complete.html',2,110),
(2167,'Rgaa22-1013','','10.13',2101301,'http://rgaa.net/Accessibilite-des-documents.html',2,110),
(2168,'Rgaa22-1101','','11.1',2110101,'http://rgaa.net/presence-des-balises-th-pour.html',2,111),
(2169,'Rgaa22-1102','','11.2',2110201,'http://rgaa.net/presence-d-une-relation-entre-les.html',2,111),
(2170,'Rgaa22-1103','','11.3',2110301,'http://rgaa.net/presence-d-une-relation-entre-les,170.html',2,111),
(2171,'Rgaa22-1104','','11.4',2110401,'http://rgaa.net/Absence-des-elements-propres-aux.html',2,111),
(2172,'Rgaa22-1105','','11.5',2110501,'http://rgaa.net/Absence-de-tableaux-de-donnees-ou.html',2,111),
(2173,'Rgaa22-1106','','11.6',2110601,'http://rgaa.net/Linearisation-correcte-des.html',2,111),
(2174,'Rgaa22-1107','','11.7',2110701,'http://rgaa.net/presence-d-un-titre-pour-les.html',2,111),
(2175,'Rgaa22-1108','','11.8',2110801,'http://rgaa.net/presence-d-un-resume-pour-les.html',2,111),
(2176,'Rgaa22-1109','','11.9',2110901,'http://rgaa.net/Pertinence-du-titre-du-tableau-de.html',2,111),
(2177,'Rgaa22-1110','','11.10',2111001,'http://rgaa.net/Pertinence-du-resume-du-tableau-de.html',2,111),
(2178,'Rgaa22-1201','','12.1',2120101,'http://rgaa.net/presence-de-l-indication-des.html',2,112),
(2179,'Rgaa22-1202','','12.2',2120201,'http://rgaa.net/presence-de-l-indication-des,179.html',2,112),
(2180,'Rgaa22-1203','','12.3',2120301,'http://rgaa.net/Equivalence-de-l-information-mise.html',2,112),
(2181,'Rgaa22-1204','','12.4',2120401,'http://rgaa.net/presence-de-liens-ou-de.html',2,112),
(2182,'Rgaa22-1205','','12.5',2120501,'http://rgaa.net/Absence-de-syntaxes-cryptiques-par.html',2,112),
(2183,'Rgaa22-1206','','12.6',2120601,'http://rgaa.net/presence-d-informations-sur-les.html',2,112),
(2184,'Rgaa22-1207','','12.7',2120701,'http://rgaa.net/presence-d-un-moyen-de,184.html',2,112),
(2185,'Rgaa22-1208','','12.8',2120801,'http://rgaa.net/presence-d-un-autre-moyen-que-la,185.html',2,112),
(2186,'Rgaa22-1209','','12.9',2120901,'http://rgaa.net/presence-d-un-autre-moyen-que-la,186.html',2,112),
(2187,'Rgaa22-1210','','12.10',2121001,'http://rgaa.net/Utilisation-d-un-style-de.html',2,112);


INSERT INTO "test" VALUES 
(2001,'Rgaa22-01011','http://rgaa.net/1-1-Absence-de-cadres-non-titres.html','1.1',2010101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule01011','http://www.tanaguru.org/en/content/rgaa22-rule-1-1',2001,NULL,1,NULL,1,TRUE),
(2002,'Rgaa22-01021','http://rgaa.net/Pertinence-des-titres-donnes-aux.html','1.2',2010201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule01021','http://www.tanaguru.org/en/content/rgaa22-rule-1-2',2002,NULL,1,NULL,1,TRUE),
(2003,'Rgaa22-02011','http://rgaa.net/presence-d-un-autre-moyen-que-la.html','2.1',2020101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule02011','http://www.tanaguru.org/en/content/rgaa22-rule-2-1',2003,NULL,1,NULL,1,TRUE),
(2004,'Rgaa22-02021','http://rgaa.net/presence-d-un-autre-moyen-que-la,4.html','2.2',2020201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule02021','http://www.tanaguru.org/en/content/rgaa22-rule-2-2',2004,NULL,1,NULL,1,TRUE),
(2005,'Rgaa22-02031','http://rgaa.net/presence-d-un-moyen-de.html','2.3',2020301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule02031','http://www.tanaguru.org/en/content/rgaa22-rule-2-3',2005,NULL,1,NULL,1,TRUE),
(2006,'Rgaa22-02041','http://rgaa.net/presence-d-un-moyen-de,6.html','2.4',2020401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule02041','http://www.tanaguru.org/en/content/rgaa22-rule-2-4',2006,NULL,1,NULL,1,TRUE),
(2007,'Rgaa22-02051','http://rgaa.net/Valeur-du-rapport-de-contraste-du.html','2.5',2020501,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule02051','http://www.tanaguru.org/en/content/rgaa22-rule-2-5',2007,NULL,2,NULL,1,TRUE),
(2008,'Rgaa22-02061','http://rgaa.net/Valeur-du-rapport-de-contraste-du,8.html','2.6',2020601,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule02061','http://www.tanaguru.org/en/content/rgaa22-rule-2-6',2008,NULL,2,NULL,1,TRUE),
(2009,'Rgaa22-02071','http://rgaa.net/Valeur-du-rapport-de-contraste-du,9.html','2.7',2020701,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule02071','http://www.tanaguru.org/en/content/rgaa22-rule-2-7',2009,NULL,2,NULL,1,TRUE),
(2010,'Rgaa22-02081','http://rgaa.net/Valeur-du-rapport-de-contraste-du,10.html','2.8',2020801,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule02081','http://www.tanaguru.org/en/content/rgaa22-rule-2-8',2010,NULL,2,NULL,1,TRUE),
(2011,'Rgaa22-02091','http://rgaa.net/Valeur-du-rapport-de-contraste-du,11.html','2.9',2020901,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule02091','http://www.tanaguru.org/en/content/rgaa22-rule-2-9',2011,NULL,2,NULL,1,TRUE),
(2012,'Rgaa22-02101','http://rgaa.net/Valeur-du-rapport-de-contraste-du,12.html','2.10',2021001,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule02101','http://www.tanaguru.org/en/content/rgaa22-rule-2-10',2012,NULL,2,NULL,1,TRUE),
(2013,'Rgaa22-02111','http://rgaa.net/Valeur-du-rapport-de-contraste-du,13.html','2.11',2021101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule02111','http://www.tanaguru.org/en/content/rgaa22-rule-2-11',2013,NULL,3,NULL,1,TRUE),
(2014,'Rgaa22-02121','http://rgaa.net/Valeur-du-rapport-de-contraste-du,14.html','2.12',2021201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule02121','http://www.tanaguru.org/en/content/rgaa22-rule-2-12',2014,NULL,3,NULL,1,TRUE),
(2015,'Rgaa22-02131','http://rgaa.net/Valeur-du-rapport-de-contraste-du,15.html','2.13',2021301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule02131','http://www.tanaguru.org/en/content/rgaa22-rule-2-13',2015,NULL,3,NULL,1,TRUE),
(2016,'Rgaa22-02141','http://rgaa.net/Valeur-du-rapport-de-contraste-du,16.html','2.14',2021401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule02141','http://www.tanaguru.org/en/content/rgaa22-rule-2-14',2016,NULL,3,NULL,1,TRUE),
(2017,'Rgaa22-02151','http://rgaa.net/Valeur-du-rapport-de-contraste-du,17.html','2.15',2021501,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule02151','http://www.tanaguru.org/en/content/rgaa22-rule-2-15',2017,NULL,3,NULL,1,TRUE),
(2018,'Rgaa22-02161','http://rgaa.net/Valeur-du-rapport-de-contraste-du,18.html','2.16',2021601,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule02161','http://www.tanaguru.org/en/content/rgaa22-rule-2-16',2018,NULL,3,NULL,1,TRUE),
(2019,'Rgaa22-03011','http://rgaa.net/Possibilite-d-identifier-les.html','3.1',2030101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule03011','http://www.tanaguru.org/en/content/rgaa22-rule-3-1',2019,NULL,1,NULL,1,TRUE),
(2020,'Rgaa22-03021','http://rgaa.net/presence-d-information-prealable.html','3.2',2030201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule03021','http://www.tanaguru.org/en/content/rgaa22-rule-3-2',2020,NULL,1,NULL,1,TRUE),
(2021,'Rgaa22-03031','http://rgaa.net/Positionnement-correct-des.html','3.3',2030301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule03031','http://www.tanaguru.org/en/content/rgaa22-rule-3-3',2021,NULL,1,NULL,1,TRUE),
(2022,'Rgaa22-03041','http://rgaa.net/Regroupement-d-elements-de.html','3.4',2030401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule03041','http://www.tanaguru.org/en/content/rgaa22-rule-3-4',2022,NULL,1,NULL,1,TRUE),
(2023,'Rgaa22-03051','http://rgaa.net/Absence-d-element-fieldset-sans.html','3.5',2030501,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule03051','http://www.tanaguru.org/en/content/rgaa22-rule-3-5',2023,NULL,1,NULL,1,TRUE),
(2024,'Rgaa22-03061','http://rgaa.net/Pertinence-du-contenu-de-l-element.html','3.6',2030601,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule03061','http://www.tanaguru.org/en/content/rgaa22-rule-3-6',2024,NULL,1,NULL,1,TRUE),
(2025,'Rgaa22-03071','http://rgaa.net/Regroupement-d-elements-option.html','3.7',2030701,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule03071','http://www.tanaguru.org/en/content/rgaa22-rule-3-7',2025,NULL,1,NULL,1,TRUE),
(2026,'Rgaa22-03081','http://rgaa.net/presence-d-un-attribut-label-sur-l.html','3.8',2030801,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule03081','http://www.tanaguru.org/en/content/rgaa22-rule-3-8',2026,NULL,1,NULL,1,TRUE),
(2027,'Rgaa22-03091','http://rgaa.net/Pertinence-du-contenu-de-l.html','3.9',2030901,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule03091','http://www.tanaguru.org/en/content/rgaa22-rule-3-9',2027,NULL,1,NULL,1,TRUE),
(2028,'Rgaa22-03101','http://rgaa.net/Absence-d-element-de-formulaire.html','3.10',2031001,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule03101','http://www.tanaguru.org/en/content/rgaa22-rule-3-10',2028,NULL,1,NULL,1,TRUE),
(2029,'Rgaa22-03111','http://rgaa.net/Absence-d-element-de-formulaire,29.html','3.11',2031101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule03121','http://www.tanaguru.org/en/content/rgaa22-rule-3-11',2029,NULL,1,NULL,1,TRUE),
(2030,'Rgaa22-03121','http://rgaa.net/Pertinence-des-etiquettes-d.html','3.12',2031201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule03121','http://www.tanaguru.org/en/content/rgaa22-rule-3-12',2030,NULL,1,NULL,1,TRUE),
(2031,'Rgaa22-03131','http://rgaa.net/presence-d-informations-ou-de.html','3.13',2031301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule03131','http://www.tanaguru.org/en/content/rgaa22-rule-3-13',2031,NULL,2,NULL,1,TRUE),
(2032,'Rgaa22-03141','http://rgaa.net/presence-de-mecanismes-permettant.html','3.14',2031401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule03141','http://www.tanaguru.org/en/content/rgaa22-rule-3-14',2032,NULL,2,NULL,1,TRUE),
(2033,'Rgaa22-03151','http://rgaa.net/presence-de-mecanismes-permettant,33.html','3.15',2031501,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule03151','http://www.tanaguru.org/en/content/rgaa22-rule-3-15',2033,NULL,3,NULL,1,TRUE),
(2034,'Rgaa22-03161','http://rgaa.net/presence-d-une-page-d-aide-ou-d-un.html','3.16',2031601,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule03161','http://www.tanaguru.org/en/content/rgaa22-rule-3-16',2034,NULL,3,NULL,1,TRUE),
(2035,'Rgaa22-04011','http://rgaa.net/presence-de-l-attribut-alt.html','4.1',2040101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule04011','http://www.tanaguru.org/en/content/rgaa22-rule-4-1',2035,NULL,1,NULL,1,TRUE),
(2036,'Rgaa22-04021','http://rgaa.net/Pertinence-de-l-alternative.html','4.2',2040201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule04021','http://www.tanaguru.org/en/content/rgaa22-rule-4-2',2036,NULL,1,NULL,1,TRUE),
(2037,'Rgaa22-04031','http://rgaa.net/Pertinence-de-l-alternative,37.html','4.3',2040301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule04031','http://www.tanaguru.org/en/content/rgaa22-rule-4-3',2037,NULL,1,NULL,1,TRUE),
(2038,'Rgaa22-04041','http://rgaa.net/Pertinence-de-l-alternative,38.html','4.4',2040401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule04041','http://www.tanaguru.org/en/content/rgaa22-rule-4-4',2038,NULL,1,NULL,1,TRUE),
(2039,'Rgaa22-04051','http://rgaa.net/Pertinence-de-l-alternative-vide.html','4.5',2040501,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule04051','http://www.tanaguru.org/en/content/rgaa22-rule-4-5',2039,NULL,1,NULL,1,TRUE),
(2040,'Rgaa22-04061','http://rgaa.net/longueur-du-contenu-des.html','4.6',2040601,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule04061','http://www.tanaguru.org/en/content/rgaa22-rule-4-6',2040,NULL,1,NULL,1,TRUE),
(2041,'Rgaa22-04071','http://rgaa.net/Existence-d-une-description-longue.html','4.7',2040701,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule04071','http://www.tanaguru.org/en/content/rgaa22-rule-4-7',2041,NULL,1,NULL,1,TRUE),
(2042,'Rgaa22-04081','http://rgaa.net/Pertinence-de-la-description.html','4.8',2040801,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule04081','http://www.tanaguru.org/en/content/rgaa22-rule-4-8',2042,NULL,1,NULL,1,TRUE),
(2043,'Rgaa22-04091','http://rgaa.net/presence-de-l-attribut-longdesc.html','4.9',2040901,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule04091','http://www.tanaguru.org/en/content/rgaa22-rule-4-9',2043,NULL,1,NULL,1,TRUE),
(2044,'Rgaa22-04101','http://rgaa.net/presence-d-une-information-de.html','4.10',2041001,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule04101','http://www.tanaguru.org/en/content/rgaa22-rule-4-10',2044,NULL,1,NULL,1,TRUE),
(2045,'Rgaa22-04111','http://rgaa.net/Coherence-dans-l-identification.html','4.11',2041101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule04111','http://www.tanaguru.org/en/content/rgaa22-rule-4-11',2045,NULL,2,NULL,1,TRUE),
(2046,'Rgaa22-05011','http://rgaa.net/Acces-a-une-information.html','5.1',2050101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05011','http://www.tanaguru.org/en/content/rgaa22-rule-5-1',2046,NULL,1,NULL,1,TRUE),
(2047,'Rgaa22-05021','http://rgaa.net/presence-de-la-transcription.html','5.2',2050201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05021','http://www.tanaguru.org/en/content/rgaa22-rule-5-2',2047,NULL,1,NULL,1,TRUE),
(2048,'Rgaa22-05031','http://rgaa.net/Pertinence-de-la-transcription.html','5.3',2050301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05031','http://www.tanaguru.org/en/content/rgaa22-rule-5-3',2048,NULL,1,NULL,1,TRUE),
(2049,'Rgaa22-05041','http://rgaa.net/presence-d-une-description-audio.html','5.4',2050401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05041','http://www.tanaguru.org/en/content/rgaa22-rule-5-4',2049,NULL,1,NULL,1,TRUE),
(2050,'Rgaa22-05051','http://rgaa.net/Pertinence-de-la-description-audio.html','5.5',2050501,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05051','http://www.tanaguru.org/en/content/rgaa22-rule-5-5',2050,NULL,1,NULL,1,TRUE),
(2051,'Rgaa22-05061','http://rgaa.net/Possibilite-de-controler-l.html','5.6',2050601,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05061','http://www.tanaguru.org/en/content/rgaa22-rule-5-6',2051,NULL,1,NULL,1,TRUE),
(2052,'Rgaa22-05071','http://rgaa.net/presence-d-une-description-audio,52.html','5.7',2050701,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05071','http://www.tanaguru.org/en/content/rgaa22-rule-5-7',2052,NULL,3,NULL,1,TRUE),
(2053,'Rgaa22-05081','http://rgaa.net/presence-d-une-description-audio,53.html','5.8',2050801,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05081','http://www.tanaguru.org/en/content/rgaa22-rule-5-8',2053,NULL,2,NULL,1,TRUE),
(2054,'Rgaa22-05091','http://rgaa.net/presence-du-sous-titrage.html','5.9',2050901,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05091','http://www.tanaguru.org/en/content/rgaa22-rule-5-9',2054,NULL,1,NULL,1,TRUE),
(2055,'Rgaa22-05101','http://rgaa.net/Pertinence-du-sous-titrage.html','5.10',2051001,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05101','http://www.tanaguru.org/en/content/rgaa22-rule-5-10',2055,NULL,1,NULL,1,TRUE),
(2056,'Rgaa22-05111','http://rgaa.net/presence-d-une-alternative-aux.html','5.11',2051101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05111','http://www.tanaguru.org/en/content/rgaa22-rule-5-11',2056,NULL,1,NULL,1,TRUE),
(2057,'Rgaa22-05121','http://rgaa.net/presence-d-une-alternative-aux,57.html','5.12',2051201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05121','http://www.tanaguru.org/en/content/rgaa22-rule-5-12',2057,NULL,1,NULL,1,TRUE),
(2058,'Rgaa22-05131','http://rgaa.net/Absence-d-elements-provoquant-des.html','5.13',2051301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05131','http://www.tanaguru.org/en/content/rgaa22-rule-5-13',2058,NULL,1,NULL,1,TRUE),
(2059,'Rgaa22-05141','http://rgaa.net/Absence-de-code-javascript,59.html','5.14',2051401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05141','http://www.tanaguru.org/en/content/rgaa22-rule-5-14',2059,NULL,1,NULL,1,TRUE),
(2060,'Rgaa22-05151','http://rgaa.net/Absence-de-mise-en-forme.html','5.15',2051501,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05151','http://www.tanaguru.org/en/content/rgaa22-rule-5-15',2060,NULL,1,NULL,1,TRUE),
(2061,'Rgaa22-05161','http://rgaa.net/Compatibilite-des-elements.html','5.16',2051601,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05161','http://www.tanaguru.org/en/content/rgaa22-rule-5-16',2061,NULL,1,NULL,1,TRUE),
(2062,'Rgaa22-05171','http://rgaa.net/Absence-totale-de-changements.html','5.17',2051701,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05171','http://www.tanaguru.org/en/content/rgaa22-rule-5-17',2062,NULL,3,NULL,1,TRUE),
(2063,'Rgaa22-05181','http://rgaa.net/presence-du-sous-titrage,63.html','5.18',2051801,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05181','http://www.tanaguru.org/en/content/rgaa22-rule-5-18',2063,NULL,2,NULL,1,TRUE),
(2064,'Rgaa22-05191','http://rgaa.net/Absence-de-l-element-blink.html','5.19',2051901,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05191','http://www.tanaguru.org/en/content/rgaa22-rule-5-19',2064,NULL,1,NULL,1,TRUE),
(2065,'Rgaa22-05201','http://rgaa.net/Absence-d-elements-provoquant-des,65.html','5.20',2052001,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05201','http://www.tanaguru.org/en/content/rgaa22-rule-5-20',2065,NULL,1,NULL,1,TRUE),
(2066,'Rgaa22-05211','http://rgaa.net/Absence-de-code-javascript,66.html','5.21',2052101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05211','http://www.tanaguru.org/en/content/rgaa22-rule-5-21',2066,NULL,1,NULL,1,TRUE),
(2067,'Rgaa22-05221','http://rgaa.net/Absence-de-mise-en-forme,67.html','5.22',2052201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05221','http://www.tanaguru.org/en/content/rgaa22-rule-5-22',2067,NULL,1,NULL,1,TRUE),
(2068,'Rgaa22-05231','http://rgaa.net/Absence-d-element-marquee.html','5.23',2052301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05231','http://www.tanaguru.org/en/content/rgaa22-rule-5-23',2068,NULL,1,NULL,1,TRUE),
(2069,'Rgaa22-05241','http://rgaa.net/Absence-d-elements-affichant-des.html','5.24',2052401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05241','http://www.tanaguru.org/en/content/rgaa22-rule-5-24',2069,NULL,1,NULL,1,TRUE),
(2070,'Rgaa22-05251','http://rgaa.net/Absence-de-code-javascript,70.html','5.25',2052501,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05251','http://www.tanaguru.org/en/content/rgaa22-rule-5-25',2070,NULL,1,NULL,1,TRUE),
(2071,'Rgaa22-05261','http://rgaa.net/Absence-de-mise-en-forme,71.html','5.26',2052601,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05261','http://www.tanaguru.org/en/content/rgaa22-rule-5-26',2071,NULL,1,NULL,1,TRUE),
(2072,'Rgaa22-05271','http://rgaa.net/Independance-du-peripherique-d.html','5.27',2052701,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05271','http://www.tanaguru.org/en/content/rgaa22-rule-5-27',2072,NULL,1,NULL,1,TRUE),
(2073,'Rgaa22-05281','http://rgaa.net/presence-d-une-alternative-aux,73.html','5.28',2052801,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05281','http://www.tanaguru.org/en/content/rgaa22-rule-5-28',2073,NULL,1,NULL,1,TRUE),
(2074,'Rgaa22-05291','http://rgaa.net/Absence-d-elements-declenchant-la.html','5.29',2052901,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05291','http://www.tanaguru.org/en/content/rgaa22-rule-5-29',2074,NULL,1,NULL,1,TRUE),
(2075,'Rgaa22-05301','http://rgaa.net/Absence-d-element-bgsound.html','5.30',2053001,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05301','http://www.tanaguru.org/en/content/rgaa22-rule-5-30',2075,NULL,1,NULL,1,TRUE),
(2076,'Rgaa22-05311','http://rgaa.net/presence-de-version-en-langue-des.html','5.31',2053101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05311','http://www.tanaguru.org/en/content/rgaa22-rule-5-31',2076,NULL,3,NULL,1,TRUE),
(2077,'Rgaa22-05321','http://rgaa.net/Pertinence-de-la-version-en-langue.html','5.32',2053201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05321','http://www.tanaguru.org/en/content/rgaa22-rule-5-32',2077,NULL,3,NULL,1,TRUE),
(2078,'Rgaa22-05331','http://rgaa.net/Niveau-sonore-de-la-piste-de.html','5.33',2053301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05331','http://www.tanaguru.org/en/content/rgaa22-rule-5-33',2078,NULL,3,NULL,1,TRUE),
(2079,'Rgaa22-05341','http://rgaa.net/presence-d-un-mecanisme-pour.html','5.34',2053401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule05341','http://www.tanaguru.org/en/content/rgaa22-rule-5-34',2079,NULL,3,NULL,1,TRUE),
(2080,'Rgaa22-06011','http://rgaa.net/Acces-aux-ens-textuels-doublant.html','6.1',2060101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06011','http://www.tanaguru.org/en/content/rgaa22-rule-6-1',2080,NULL,1,NULL,1,TRUE),
(2081,'Rgaa22-06021','http://rgaa.net/presence-d-un-avertissement.html','6.2',2060201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06021','http://www.tanaguru.org/en/content/rgaa22-rule-6-2',2081,NULL,1,NULL,1,TRUE),
(2082,'Rgaa22-06031','http://rgaa.net/presence-d-un-avertissement,82.html','6.3',2060301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06031','http://www.tanaguru.org/en/content/rgaa22-rule-6-3',2082,NULL,1,NULL,1,TRUE),
(2083,'Rgaa22-06041','http://rgaa.net/presence-d-un-avertissement,83.html','6.4',2060401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06041','http://www.tanaguru.org/en/content/rgaa22-rule-6-4',2083,NULL,1,NULL,1,TRUE),
(2084,'Rgaa22-06051','http://rgaa.net/Absence-d-ouverture-de-nouvelles.html','6.5',2060501,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06051','http://www.tanaguru.org/en/content/rgaa22-rule-6-5',2084,NULL,1,NULL,1,TRUE),
(2085,'Rgaa22-06061','http://rgaa.net/Absence-de-piege-lors-de-la.html','6.6',2060601,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06061','http://www.tanaguru.org/en/content/rgaa22-rule-6-6',2085,NULL,1,NULL,1,TRUE),
(2086,'Rgaa22-06071','http://rgaa.net/Absence-d-element-meta-provoquant.html','6.7',2060701,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06071','http://www.tanaguru.org/en/content/rgaa22-rule-6-7',2086,NULL,1,NULL,1,TRUE),
(2087,'Rgaa22-06081','http://rgaa.net/Absence-de-code-javascript.html','6.8',2060801,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06081','http://www.tanaguru.org/en/content/rgaa22-rule-6-8',2087,NULL,1,NULL,1,TRUE),
(2088,'Rgaa22-06091','http://rgaa.net/Absence-d-elements-provoquant-un.html','6.9',2060901,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06091','http://www.tanaguru.org/en/content/rgaa22-rule-6-9',2088,NULL,1,NULL,1,TRUE),
(2089,'Rgaa22-06101','http://rgaa.net/Absence-d-element-meta-provoquant,89.html','6.10',2061001,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06101','http://www.tanaguru.org/en/content/rgaa22-rule-6-10',2089,NULL,1,NULL,1,TRUE),
(2090,'Rgaa22-06111','http://rgaa.net/Absence-de-code-javascript,90.html','6.11',2061101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06111','http://www.tanaguru.org/en/content/rgaa22-rule-6-11',2090,NULL,1,NULL,1,TRUE),
(2091,'Rgaa22-06121','http://rgaa.net/Absence-d-elements-provoquant-une.html','6.12',2061201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06121','http://www.tanaguru.org/en/content/rgaa22-rule-6-12',2091,NULL,1,NULL,1,TRUE),
(2092,'Rgaa22-06131','http://rgaa.net/Possibite-d-identifier-la.html','6.13',2061301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06131','http://www.tanaguru.org/en/content/rgaa22-rule-6-13',2092,NULL,1,NULL,1,TRUE),
(2093,'Rgaa22-06141','http://rgaa.net/Possibite-d-identifier-la,93.html','6.14',2061401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06141','http://www.tanaguru.org/en/content/rgaa22-rule-6-14',2093,NULL,3,NULL,1,TRUE),
(2094,'Rgaa22-06151','http://rgaa.net/Coherence-de-la-destination-ou-de.html','6.15',2061501,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06151','http://www.tanaguru.org/en/content/rgaa22-rule-6-15',2094,NULL,1,NULL,1,TRUE),
(2095,'Rgaa22-06161','http://rgaa.net/Absence-de-ens-sans-intitule.html','6.16',2061601,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06161','http://www.tanaguru.org/en/content/rgaa22-rule-6-16',2095,NULL,1,NULL,1,TRUE),
(2096,'Rgaa22-06171','http://rgaa.net/presence-d-une-page-contenant-le.html','6.17',2061701,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06171','http://www.tanaguru.org/en/content/rgaa22-rule-6-17',2096,NULL,2,NULL,1,TRUE),
(2097,'Rgaa22-06181','http://rgaa.net/Coherence-du-plan-du-site.html','6.18',2061801,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06181','http://www.tanaguru.org/en/content/rgaa22-rule-6-18',2097,NULL,2,NULL,1,TRUE),
(2098,'Rgaa22-06191','http://rgaa.net/presence-d-un-acces-a-la-page.html','6.19',2061901,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06191','http://www.tanaguru.org/en/content/rgaa22-rule-6-19',2098,NULL,2,NULL,1,TRUE),
(2099,'Rgaa22-06201','http://rgaa.net/presence-d-un-fil-d-ariane.html','6.20',2062001,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06201','http://www.tanaguru.org/en/content/rgaa22-rule-6-20',2099,NULL,3,NULL,1,TRUE),
(2100,'Rgaa22-06211','http://rgaa.net/presence-de-menus-ou-de-barres-de.html','6.21',2062101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06211','http://www.tanaguru.org/en/content/rgaa22-rule-6-21',2100,NULL,2,NULL,1,TRUE),
(2101,'Rgaa22-06221','http://rgaa.net/Coherence-de-la-position-des-menus.html','6.22',2062201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06221','http://www.tanaguru.org/en/content/rgaa22-rule-6-22',2101,NULL,2,NULL,1,TRUE),
(2102,'Rgaa22-06231','http://rgaa.net/Coherence-de-la-presentation-des.html','6.23',2062301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06231','http://www.tanaguru.org/en/content/rgaa22-rule-6-23',2102,NULL,2,NULL,1,TRUE),
(2103,'Rgaa22-06241','http://rgaa.net/Navigation-au-clavier-dans-un.html','6.24',2062401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06241','http://www.tanaguru.org/en/content/rgaa22-rule-6-24',2103,NULL,1,NULL,1,TRUE),
(2104,'Rgaa22-06251','http://rgaa.net/presence-d-un-avertissement,104.html','6.25',2062501,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06251','http://www.tanaguru.org/en/content/rgaa22-rule-6-25',2104,NULL,3,NULL,1,TRUE),
(2105,'Rgaa22-06261','http://rgaa.net/presence-des-informations-de.html','6.26',2062601,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06261','http://www.tanaguru.org/en/content/rgaa22-rule-6-26',2105,NULL,1,NULL,1,TRUE),
(2106,'Rgaa22-06271','http://rgaa.net/presence-des-informations-de-poids.html','6.27',2062701,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06271','http://www.tanaguru.org/en/content/rgaa22-rule-6-27',2106,NULL,1,NULL,1,TRUE),
(2107,'Rgaa22-06281','http://rgaa.net/presence-des-informations-de,107.html','6.28',2062801,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06281','http://www.tanaguru.org/en/content/rgaa22-rule-6-28',2107,NULL,1,NULL,1,TRUE),
(2108,'Rgaa22-06291','http://rgaa.net/presence-de-regroupement-pour-les.html','6.29',2062901,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06291','http://www.tanaguru.org/en/content/rgaa22-rule-6-29',2108,NULL,1,NULL,1,TRUE),
(2109,'Rgaa22-06301','http://rgaa.net/presence-d-un-basage-permettant.html','6.30',2063001,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06301','http://www.tanaguru.org/en/content/rgaa22-rule-6-30',2109,NULL,1,NULL,1,TRUE),
(2110,'Rgaa22-06311','http://rgaa.net/presence-de-ens-d-evitement-ou-d.html','6.31',2063101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06311','http://www.tanaguru.org/en/content/rgaa22-rule-6-31',2110,NULL,1,NULL,1,TRUE),
(2111,'Rgaa22-06321','http://rgaa.net/Coherence-des-ens-d-evitement-ou.html','6.32',2063201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06321','http://www.tanaguru.org/en/content/rgaa22-rule-6-32',2111,NULL,1,NULL,1,TRUE),
(2112,'Rgaa22-06331','http://rgaa.net/Ordre-des-liens-d-evitement-ou-d.html','6.33',2063301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06331','http://www.tanaguru.org/en/content/rgaa22-rule-6-33',2112,NULL,2,NULL,1,TRUE),
(2113,'Rgaa22-06341','http://rgaa.net/presence-d-un-moteur-de-recherche.html','6.34',2063401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06341','http://www.tanaguru.org/en/content/rgaa22-rule-6-34',2113,NULL,2,NULL,1,TRUE),
(2114,'Rgaa22-06351','http://rgaa.net/Possibilite-de-naviguer-facilement.html','6.35',2063501,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06351','http://www.tanaguru.org/en/content/rgaa22-rule-6-35',2114,NULL,2,NULL,1,TRUE),
(2115,'Rgaa22-06361','http://rgaa.net/presence-d-une-indication-de-la.html','6.36',2063601,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule06361','http://www.tanaguru.org/en/content/rgaa22-rule-6-36',2115,NULL,3,NULL,1,TRUE),
(2116,'Rgaa22-07011','http://rgaa.net/Absence-de-generation-de-contenus.html','7.1',2070101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule07011','http://www.tanaguru.org/en/content/rgaa22-rule-7-1',2116,NULL,1,NULL,1,TRUE),
(2117,'Rgaa22-07021','http://rgaa.net/Absence-d-alteration-de-la.html','7.2',2070201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule07021','http://www.tanaguru.org/en/content/rgaa22-rule-7-2',2117,NULL,1,NULL,1,TRUE),
(2118,'Rgaa22-07031','http://rgaa.net/Lisibilite-des-informations.html','7.3',2070301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule07031','http://www.tanaguru.org/en/content/rgaa22-rule-7-3',2118,NULL,1,NULL,1,TRUE),
(2119,'Rgaa22-07041','http://rgaa.net/Absence-d-espaces-utilises-pour.html','7.4',2070401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule07041','http://www.tanaguru.org/en/content/rgaa22-rule-7-4',2119,NULL,1,NULL,1,TRUE),
(2120,'Rgaa22-07051','http://rgaa.net/Absence-de-definition-d-une.html','7.5',2070501,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule07051','http://www.tanaguru.org/en/content/rgaa22-rule-7-5',2120,NULL,2,NULL,1,TRUE),
(2121,'Rgaa22-07061','http://rgaa.net/Possibilite-de-remplacer-les.html','7.6',2070601,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule07061','http://www.tanaguru.org/en/content/rgaa22-rule-7-6',2121,NULL,2,NULL,1,TRUE),
(2122,'Rgaa22-07071','http://rgaa.net/Possibilite-de-remplacer-les,122.html','7.7',2070701,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule07071','http://www.tanaguru.org/en/content/rgaa22-rule-7-7',2122,NULL,3,NULL,1,TRUE),
(2123,'Rgaa22-07081','http://rgaa.net/Absence-d-attributs-ou-d-elements.html','7.8',2070801,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule07081','http://www.tanaguru.org/en/content/rgaa22-rule-7-8',2123,NULL,1,NULL,1,TRUE),
(2124,'Rgaa22-07091','http://rgaa.net/Absence-d-elements-HTML-utilises-a.html','7.9',2070901,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule07091','http://www.tanaguru.org/en/content/rgaa22-rule-7-9',2124,NULL,1,NULL,1,TRUE),
(2125,'Rgaa22-07101','http://rgaa.net/Maintien-de-la-distinction.html','7.10',2071001,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule07101','http://www.tanaguru.org/en/content/rgaa22-rule-7-10',2125,NULL,1,NULL,1,TRUE),
(2126,'Rgaa22-07111','http://rgaa.net/Absence-de-suppression-de-l-effet.html','7.11',2071101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule07111','http://www.tanaguru.org/en/content/rgaa22-rule-7-11',2126,NULL,1,NULL,1,TRUE),
(2127,'Rgaa22-07121','http://rgaa.net/Absence-de-justification-du-texte.html','7.12',2071201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule07121','http://www.tanaguru.org/en/content/rgaa22-rule-7-12',2127,NULL,3,NULL,1,TRUE),
(2128,'Rgaa22-07131','http://rgaa.net/Lisibilite-du-document-en-cas-d.html','7.13',2071301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule07131','http://www.tanaguru.org/en/content/rgaa22-rule-7-13',2128,NULL,2,NULL,1,TRUE),
(2129,'Rgaa22-07141','http://rgaa.net/Absence-d-unites-absolues-ou-de.html','7.14',2071401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule07141','http://www.tanaguru.org/en/content/rgaa22-rule-7-14',2129,NULL,2,NULL,1,TRUE),
(2130,'Rgaa22-07151','http://rgaa.net/Absence-d-apparition-de-barre-de.html','7.15',2071501,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule07151','http://www.tanaguru.org/en/content/rgaa22-rule-7-15',2130,NULL,3,NULL,1,TRUE),
(2131,'Rgaa22-07161','http://rgaa.net/Largeur-des-blocs-de-textes.html','7.16',2071601,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule07161','http://www.tanaguru.org/en/content/rgaa22-rule-7-16',2131,NULL,3,NULL,1,TRUE),
(2132,'Rgaa22-07171','http://rgaa.net/Valeur-de-l-espace-entre-les.html','7.17',2071701,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule07171','http://www.tanaguru.org/en/content/rgaa22-rule-7-17',2132,NULL,3,NULL,1,TRUE),
(2133,'Rgaa22-07181','http://rgaa.net/Restitution-correcte-dans-les.html','7.18',2071801,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule07181','http://www.tanaguru.org/en/content/rgaa22-rule-7-18',2133,NULL,1,NULL,1,TRUE),
(2134,'Rgaa22-08011','http://rgaa.net/Mise-a-jour-des-alternatives-aux.html','8.1',2080101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule08011','http://www.tanaguru.org/en/content/rgaa22-rule-8-1',2134,NULL,1,NULL,1,TRUE),
(2135,'Rgaa22-08021','http://rgaa.net/Universalite-du-gestionnaire-d.html','8.2',2080201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule08021','http://www.tanaguru.org/en/content/rgaa22-rule-8-2',2135,NULL,1,NULL,1,TRUE),
(2136,'Rgaa22-08031','http://rgaa.net/Universalite-des-gestionnaires-d.html','8.3',2080301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule08031','http://www.tanaguru.org/en/content/rgaa22-rule-8-3',2136,NULL,1,NULL,1,TRUE),
(2137,'Rgaa22-08041','http://rgaa.net/Possibilite-de-desactiver-toute.html','8.4',2080401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule08041','http://www.tanaguru.org/en/content/rgaa22-rule-8-4',2137,NULL,3,NULL,1,TRUE),
(2138,'Rgaa22-08051','http://rgaa.net/Absence-de-changements-de-contexte.html','8.5',2080501,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule08051','http://www.tanaguru.org/en/content/rgaa22-rule-8-5',2138,NULL,1,NULL,1,TRUE),
(2139,'Rgaa22-08061','http://rgaa.net/Ordre-d-acces-au-clavier-aux.html','8.6',2080601,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule08061','http://www.tanaguru.org/en/content/rgaa22-rule-8-6',2139,NULL,1,NULL,1,TRUE),
(2140,'Rgaa22-08071','http://rgaa.net/Utilisation-correcte-du-role-des.html','8.7',2080701,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule08071','http://www.tanaguru.org/en/content/rgaa22-rule-8-7',2140,NULL,1,NULL,1,TRUE),
(2141,'Rgaa22-08081','http://rgaa.net/presence-d-une-alternative-au-code.html','8.8',2080801,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule08081','http://www.tanaguru.org/en/content/rgaa22-rule-8-8',2141,NULL,1,NULL,1,TRUE),
(2142,'Rgaa22-08091','http://rgaa.net/Absence-de-suppression-du-focus.html','8.9',2080901,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule08091','http://www.tanaguru.org/en/content/rgaa22-rule-8-9',2142,NULL,1,NULL,1,TRUE),
(2143,'Rgaa22-08101','http://rgaa.net/Absence-de-limite-de-temps-pour.html','8.10',2080101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule08101','http://www.tanaguru.org/en/content/rgaa22-rule-8-10',2143,NULL,3,NULL,1,TRUE),
(2144,'Rgaa22-08111','http://rgaa.net/Absence-de-perte-d-informations.html','8.11',2080111,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule08111','http://www.tanaguru.org/en/content/rgaa22-rule-8-11',2144,NULL,3,NULL,1,TRUE),
(2145,'Rgaa22-08121','http://rgaa.net/presence-d-une-alternative-au-code,145.html','8.12',2080121,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule08121','http://www.tanaguru.org/en/content/rgaa22-rule-8-12',2145,NULL,1,NULL,1,TRUE),
(2146,'Rgaa22-08131','http://rgaa.net/Accessibilite-des-contenus.html','8.13',2080131,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule08131','http://www.tanaguru.org/en/content/rgaa22-rule-8-13',2146,NULL,1,NULL,1,TRUE),
(2147,'Rgaa22-09011','http://rgaa.net/presence-de-la-declaration-d.html','9.1',2090101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule09011','http://www.tanaguru.org/en/content/rgaa22-rule-9-1',2147,NULL,1,NULL,1,TRUE),
(2148,'Rgaa22-09021','http://rgaa.net/Conformite-de-la-position-de-la.html','9.2',2090201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule09021','http://www.tanaguru.org/en/content/rgaa22-rule-9-2',2148,NULL,1,NULL,1,TRUE),
(2149,'Rgaa22-09031','http://rgaa.net/Conformite-syntaxique-de-la.html','9.3',2090301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule09031','http://www.tanaguru.org/en/content/rgaa22-rule-9-3',2149,NULL,1,NULL,1,TRUE),
(2150,'Rgaa22-09041','http://rgaa.net/Validite-du-code-HTML-XHTML-au.html','9.4',2090401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule09041','http://www.tanaguru.org/en/content/rgaa22-rule-9-4',2150,NULL,1,NULL,1,TRUE),
(2151,'Rgaa22-09051','http://rgaa.net/Absence-de-composants-obsoletes.html','9.5',2090501,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule09051','http://www.tanaguru.org/en/content/rgaa22-rule-9-5',2151,NULL,1,NULL,1,TRUE),
(2152,'Rgaa22-09061','http://rgaa.net/presence-d-un-titre-dans-la-page.html','9.6',2090601,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule09061','http://www.tanaguru.org/en/content/rgaa22-rule-9-6',2152,NULL,1,NULL,1,TRUE),
(2153,'Rgaa22-09071','http://rgaa.net/Pertinence-du-titre-de-la-page.html','9.7',2090701,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule09071','http://www.tanaguru.org/en/content/rgaa22-rule-9-7',2153,NULL,1,NULL,1,TRUE),
(2154,'Rgaa22-09081','http://rgaa.net/presence-d-une-langue-de.html','9.8',2090801,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule09081','http://www.tanaguru.org/en/content/rgaa22-rule-9-8',2154,NULL,1,NULL,1,TRUE),
(2155,'Rgaa22-10011','http://rgaa.net/presence-d-au-moins-un-titre-de.html','10.1',2100101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule10011','http://www.tanaguru.org/en/content/rgaa22-rule-10-1',2155,NULL,1,NULL,1,TRUE),
(2156,'Rgaa22-10021','http://rgaa.net/Pertinence-du-contenu-des-titres.html','10.2',2100201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule10021','http://www.tanaguru.org/en/content/rgaa22-rule-10-2',2156,NULL,1,NULL,1,TRUE),
(2157,'Rgaa22-10031','http://rgaa.net/Absence-d-interruption-dans-la.html','10.3',2100301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule10031','http://www.tanaguru.org/en/content/rgaa22-rule-10-3',2157,NULL,1,NULL,1,TRUE),
(2158,'Rgaa22-10041','http://rgaa.net/presence-d-une-hierarchie-de.html','10.4',2100401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule10041','http://www.tanaguru.org/en/content/rgaa22-rule-10-4',2158,NULL,1,NULL,1,TRUE),
(2159,'Rgaa22-10051','http://rgaa.net/Absence-de-simulation-visuelle-de.html','10.5',2100501,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule10051','http://www.tanaguru.org/en/content/rgaa22-rule-10-5',2159,NULL,1,NULL,1,TRUE),
(2160,'Rgaa22-10061','http://rgaa.net/Utilisation-systematique-de-listes.html','10.6',2100601,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule10061','http://www.tanaguru.org/en/content/rgaa22-rule-10-6',2160,NULL,1,NULL,1,TRUE),
(2161,'Rgaa22-10071','http://rgaa.net/Balisage-correct-des-listes-de.html','10.7',2100701,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule10071','http://www.tanaguru.org/en/content/rgaa22-rule-10-7',2161,NULL,1,NULL,1,TRUE),
(2162,'Rgaa22-10081','http://rgaa.net/Balisage-correct-des-citations.html','10.8',2100801,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule10081','http://www.tanaguru.org/en/content/rgaa22-rule-10-8',2162,NULL,1,NULL,1,TRUE),
(2163,'Rgaa22-10091','http://rgaa.net/Balisage-correct-des-abreviations.html','10.9',2100901,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule10091','http://www.tanaguru.org/en/content/rgaa22-rule-10-9',2163,NULL,3,NULL,1,TRUE),
(2164,'Rgaa22-10101','http://rgaa.net/Balisage-correct-des-acronymes.html','10.10',2101001,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule10101','http://www.tanaguru.org/en/content/rgaa22-rule-10-10',2164,NULL,3,NULL,1,TRUE),
(2165,'Rgaa22-10111','http://rgaa.net/Pertinence-de-la-version-non.html','10.11',2101101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule10111','http://www.tanaguru.org/en/content/rgaa22-rule-10-11',2165,NULL,3,NULL,1,TRUE),
(2166,'Rgaa22-10121','http://rgaa.net/Pertinence-de-la-version-complete.html','10.12',2101201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule10121','http://www.tanaguru.org/en/content/rgaa22-rule-10-12',2166,NULL,3,NULL,1,TRUE),
(2167,'Rgaa22-10131','http://rgaa.net/Accessibilite-des-documents.html','10.13',2101301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule10131','http://www.tanaguru.org/en/content/rgaa22-rule-10-13',2167,NULL,1,NULL,1,TRUE),
(2168,'Rgaa22-11011','http://rgaa.net/presence-des-balises-th-pour.html','11.1',2110101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule11011','http://www.tanaguru.org/en/content/rgaa22-rule-11-1',2168,NULL,1,NULL,1,TRUE),
(2169,'Rgaa22-11021','http://rgaa.net/presence-d-une-relation-entre-les.html','11.2',2110201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule11021','http://www.tanaguru.org/en/content/rgaa22-rule-11-2',2169,NULL,1,NULL,1,TRUE),
(2170,'Rgaa22-11031','http://rgaa.net/presence-d-une-relation-entre-les,170.html','11.3',2110301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule11031','http://www.tanaguru.org/en/content/rgaa22-rule-11-3',2170,NULL,1,NULL,1,TRUE),
(2171,'Rgaa22-11041','http://rgaa.net/Absence-des-elements-propres-aux.html','11.4',2110401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule11041','http://www.tanaguru.org/en/content/rgaa22-rule-11-4',2171,NULL,1,NULL,1,TRUE),
(2172,'Rgaa22-11051','http://rgaa.net/Absence-de-tableaux-de-donnees-ou.html','11.5',2110501,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule11051','http://www.tanaguru.org/en/content/rgaa22-rule-11-5',2172,NULL,1,NULL,1,TRUE),
(2173,'Rgaa22-11061','http://rgaa.net/Linearisation-correcte-des.html','11.6',2110601,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule11061','http://www.tanaguru.org/en/content/rgaa22-rule-11-6',2173,NULL,1,NULL,1,TRUE),
(2174,'Rgaa22-11071','http://rgaa.net/presence-d-un-titre-pour-les.html','11.7',2110701,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule11071','http://www.tanaguru.org/en/content/rgaa22-rule-11-7',2174,NULL,1,NULL,1,TRUE),
(2175,'Rgaa22-11081','http://rgaa.net/presence-d-un-resume-pour-les.html','11.8',2110801,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule11081','http://www.tanaguru.org/en/content/rgaa22-rule-11-8',2175,NULL,1,NULL,1,TRUE),
(2176,'Rgaa22-11091','http://rgaa.net/Pertinence-du-titre-du-tableau-de.html','11.9',2110901,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule11091','http://www.tanaguru.org/en/content/rgaa22-rule-11-9',2176,NULL,1,NULL,1,TRUE),
(2177,'Rgaa22-11101','http://rgaa.net/Pertinence-du-resume-du-tableau-de.html','11.10',2111001,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule11101','http://www.tanaguru.org/en/content/rgaa22-rule-11-10',2177,NULL,1,NULL,1,TRUE),
(2178,'Rgaa22-12011','http://rgaa.net/presence-de-l-indication-des.html','12.1',2120101,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule12011','http://www.tanaguru.org/en/content/rgaa22-rule-12-1',2178,NULL,2,NULL,1,TRUE),
(2179,'Rgaa22-12021','http://rgaa.net/presence-de-l-indication-des,179.html','12.2',2120201,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule12021','http://www.tanaguru.org/en/content/rgaa22-rule-12-2',2179,NULL,2,NULL,1,TRUE),
(2180,'Rgaa22-12031','http://rgaa.net/Equivalence-de-l-information-mise.html','12.3',2120301,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule12031','http://www.tanaguru.org/en/content/rgaa22-rule-12-3',2180,NULL,1,NULL,1,TRUE),
(2181,'Rgaa22-12041','http://rgaa.net/presence-de-liens-ou-de.html','12.4',2120401,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule12041','http://www.tanaguru.org/en/content/rgaa22-rule-12-4',2181,NULL,3,NULL,1,TRUE),
(2182,'Rgaa22-12051','http://rgaa.net/Absence-de-syntaxes-cryptiques-par.html','12.5',2120501,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule12051','http://www.tanaguru.org/en/content/rgaa22-rule-12-5',2182,NULL,1,NULL,1,TRUE),
(2183,'Rgaa22-12061','http://rgaa.net/presence-d-informations-sur-les.html','12.6',2120601,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule12061','http://www.tanaguru.org/en/content/rgaa22-rule-12-6',2183,NULL,3,NULL,1,TRUE),
(2184,'Rgaa22-12071','http://rgaa.net/presence-d-un-moyen-de,184.html','12.7',2120701,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule12071','http://www.tanaguru.org/en/content/rgaa22-rule-12-7',2184,NULL,1,NULL,1,TRUE),
(2185,'Rgaa22-12081','http://rgaa.net/presence-d-un-autre-moyen-que-la,185.html','12.8',2120801,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule12081','http://www.tanaguru.org/en/content/rgaa22-rule-12-8',2185,NULL,1,NULL,1,TRUE),
(2186,'Rgaa22-12091','http://rgaa.net/presence-d-un-autre-moyen-que-la,186.html','12.9',2120901,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule12091','http://www.tanaguru.org/en/content/rgaa22-rule-12-9',2186,NULL,1,NULL,1,TRUE),
(2187,'Rgaa22-12101','http://rgaa.net/Utilisation-d-un-style-de.html','12.10',2121001,1.0,'rgaa2.2','org.tanaguru.rules.rgaa22.Rgaa22Rule12101','http://www.tanaguru.org/en/content/rgaa22-rule-12-10',2187,NULL,3,NULL,1,TRUE);


update test set no_process=FALSE WHERE 
cd_test='Rgaa22-01011' or 
cd_test='Rgaa22-01021' or 
cd_test='Rgaa22-02071' or 
cd_test='Rgaa22-02101' or 
cd_test='Rgaa22-02131' or 
cd_test='Rgaa22-02161' or 
cd_test='Rgaa22-03011' or 
cd_test='Rgaa22-03021' or 
cd_test='Rgaa22-03031' or 
cd_test='Rgaa22-03041' or 
cd_test='Rgaa22-03051' or 
cd_test='Rgaa22-03061' or 
cd_test='Rgaa22-03071' or 
cd_test='Rgaa22-03081' or 
cd_test='Rgaa22-03091' or 
cd_test='Rgaa22-03101' or 
cd_test='Rgaa22-03111' or 
cd_test='Rgaa22-03121' or 
cd_test='Rgaa22-03131' or 
cd_test='Rgaa22-03141' or 
cd_test='Rgaa22-03151' or 
cd_test='Rgaa22-03161' or
cd_test='Rgaa22-04011' or 
cd_test='Rgaa22-04021' or 
cd_test='Rgaa22-04031' or 
cd_test='Rgaa22-04041' or 
cd_test='Rgaa22-04051' or 
cd_test='Rgaa22-04061' or 
cd_test='Rgaa22-04071' or 
cd_test='Rgaa22-04081' or 
cd_test='Rgaa22-04091' or 
cd_test='Rgaa22-04101' or 
cd_test='Rgaa22-05111' or
cd_test='Rgaa22-05121' or
cd_test='Rgaa22-05161' or
cd_test='Rgaa22-05191' or
cd_test='Rgaa22-05231' or
cd_test='Rgaa22-05271' or
cd_test='Rgaa22-05281' or
cd_test='Rgaa22-05291' or
cd_test='Rgaa22-05301' or
cd_test='Rgaa22-06011' or
cd_test='Rgaa22-06021' or
cd_test='Rgaa22-06031' or
cd_test='Rgaa22-06131' or
cd_test='Rgaa22-06141' or
cd_test='Rgaa22-06151' or
cd_test='Rgaa22-06161' or
cd_test='Rgaa22-06251' or
cd_test='Rgaa22-06261' or
cd_test='Rgaa22-06271' or
cd_test='Rgaa22-06281' or
cd_test='Rgaa22-07011' or
cd_test='Rgaa22-07081' or
cd_test='Rgaa22-07091' or
cd_test='Rgaa22-07111' or
cd_test='Rgaa22-07181' or
cd_test='Rgaa22-08051' or
cd_Test='Rgaa22-09011' or
cd_Test='Rgaa22-09021' or
cd_Test='Rgaa22-09031' or
cd_test='Rgaa22-09061' or
cd_test='Rgaa22-09071' or
cd_test='Rgaa22-09081' or
cd_test='Rgaa22-10011' or
cd_test='Rgaa22-10021' or
cd_Test='Rgaa22-10031' or
cd_test='Rgaa22-10071' or
cd_test='Rgaa22-10131' or
cd_test='Rgaa22-10111' or
cd_test='Rgaa22-10121' or
cd_test='Rgaa22-11011' or
cd_test='Rgaa22-11021' or
cd_test='Rgaa22-11031' or
cd_test='Rgaa22-11041' or
cd_test='Rgaa22-11061' or
cd_test='Rgaa22-11071' or
cd_test='Rgaa22-11081' or
cd_test='Rgaa22-11091' or
cd_test='Rgaa22-11101' or
cd_test='Rgaa22-12011' or
cd_test='Rgaa22-12031';


-- Post-data save --
COMMIT;