use $myDatabaseName;

ALTER TABLE `PROCESS_RESULT` DROP FOREIGN KEY `FK1C41A80DB6D0E092`;
ALTER TABLE `PROCESS_RESULT` ADD CONSTRAINT `FK1C41A80DB6D0E092` FOREIGN KEY Id_Audit_Net_Result_Index (`Id_Audit_Net_Result`) REFERENCES `AUDIT` (`Id_Audit`) ON DELETE CASCADE;

ALTER TABLE `PROCESS_RESULT` DROP FOREIGN KEY `FK1C41A80D8146180B`;
ALTER TABLE `PROCESS_RESULT` ADD CONSTRAINT `FK1C41A80D8146180B` FOREIGN KEY Id_Audit_Gross_Result_Index (`Id_Audit_Gross_Result`) REFERENCES `AUDIT` (`Id_Audit`) ON DELETE CASCADE;

ALTER TABLE `AUDIT_TEST` DROP FOREIGN KEY FK838E6E96493EC9C2;
ALTER TABLE `AUDIT_TEST` ADD CONSTRAINT `FK838E6E96493EC9C2` FOREIGN KEY Id_Audit_Index (`Id_Audit`) REFERENCES `AUDIT` (`Id_Audit`) ON DELETE CASCADE;

ALTER TABLE `WEB_RESOURCE` DROP FOREIGN KEY FKD9A970B9493EC9C2;
ALTER TABLE `WEB_RESOURCE` ADD CONSTRAINT `FKD9A970B9493EC9C2` FOREIGN KEY Id_Audit_Index (`Id_Audit`) REFERENCES `AUDIT` (`Id_Audit`) ON DELETE CASCADE;
