use $myDatabaseName;

ALTER TABLE `PROCESS_RESULT` DROP FOREIGN KEY `FK1C41A80DB6D0E092`;
ALTER TABLE `PROCESS_RESULT` ADD CONSTRAINT `FK1C41A80DB6D0E092` FOREIGN KEY Id_Audit_Net_Result_Index (`Id_Audit_Net_Result`) REFERENCES `AUDIT` (`Id_Audit`) ON DELETE CASCADE;

ALTER TABLE `PROCESS_RESULT` DROP FOREIGN KEY `FK1C41A80D8146180B`;
ALTER TABLE `PROCESS_RESULT` ADD CONSTRAINT `FK1C41A80D8146180B` FOREIGN KEY Id_Audit_Gross_Result_Index (`Id_Audit_Gross_Result`) REFERENCES `AUDIT` (`Id_Audit`) ON DELETE CASCADE;

ALTER TABLE `AUDIT_TEST` DROP FOREIGN KEY `FK838E6E96493EC9C2`;
ALTER TABLE `AUDIT_TEST` ADD CONSTRAINT `FK838E6E96493EC9C2` FOREIGN KEY Id_Audit_Index (`Id_Audit`) REFERENCES `AUDIT` (`Id_Audit`) ON DELETE CASCADE;

ALTER TABLE `WEB_RESOURCE` DROP FOREIGN KEY `FKD9A970B9493EC9C2`;
ALTER TABLE `WEB_RESOURCE` DROP FOREIGN KEY `FKD9A970B92F70FF12`;
ALTER TABLE `WEB_RESOURCE` 
	ADD CONSTRAINT `FKD9A970B92F70FF12` FOREIGN KEY Id_Web_Resource_Parent_Index (`Id_Web_Resource_Parent`) REFERENCES `WEB_RESOURCE` (`Id_Web_Resource`) ON DELETE CASCADE ON UPDATE CASCADE,
	ADD CONSTRAINT `FKD9A970B9493EC9C2` FOREIGN KEY Id_Audit_Index (`Id_Audit`) REFERENCES `AUDIT` (`Id_Audit`) ON DELETE CASCADE;


ALTER TABLE `EVIDENCE_ELEMENT` DROP FOREIGN KEY `FK698B98F425AD22C4`;
ALTER TABLE `EVIDENCE_ELEMENT` DROP FOREIGN KEY `FK698B98F4C94A0CBA`;

ALTER TABLE `EVIDENCE_ELEMENT`
	ADD CONSTRAINT `FK698B98F425AD22C4` FOREIGN KEY PROCESS_REMARK_Id_Process_Remark_Index (`PROCESS_REMARK_Id_Process_Remark`) REFERENCES `PROCESS_REMARK` (`Id_Process_Remark`) ON DELETE CASCADE,
	ADD CONSTRAINT `FK698B98F4C94A0CBA` FOREIGN KEY EVIDENCE_Id_Evidence_Index (`EVIDENCE_Id_Evidence`) REFERENCES `EVIDENCE` (`Id_Evidence`);

ALTER TABLE `CONTENT` DROP FOREIGN KEY `FK6382C059A8A177A1`;
ALTER TABLE `CONTENT` DROP FOREIGN KEY `FK6382C059493EC9C2`;

ALTER TABLE `CONTENT`
	ADD CONSTRAINT `FK6382C059A8A177A1` FOREIGN KEY Id_Page_Index (`Id_Page`) REFERENCES `WEB_RESOURCE` (`Id_Web_Resource`) ON DELETE CASCADE,
	ADD CONSTRAINT `FK6382C059493EC9C2` FOREIGN KEY Id_Audit_Index (`Id_Audit`) REFERENCES `AUDIT` (`Id_Audit`) ON DELETE CASCADE;