CREATE USER 'tgTest'@'localhost' IDENTIFIED BY '********';

GRANT USAGE ON * . * TO 'tgTest'@'localhost' IDENTIFIED BY '********' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

CREATE DATABASE IF NOT EXISTS `tgTest` CHARACTER SET utf8;

GRANT ALL PRIVILEGES ON `tgTest` . * TO 'tgTest'@'localhost';

FLUSH PRIVILEGES;