use tanaguru;
truncate table EVIDENCE_ELEMENT ; truncate table PROCESS_REMARK ; truncate table PROCESS_RESULT ; truncate table CONTENT_RELATIONSHIP; truncate table CONTENT;
DELETE FROM WEB_RESOURCE WHERE DTYPE='PageImpl'; DELETE FROM WEB_RESOURCE WHERE DTYPE='SiteImpl'; TRUNCATE TABLE AUDIT_TEST; TRUNCATE TABLE AUDIT;