START TRANSACTION;
SET standard_conforming_strings=off;
SET escape_string_warning=off;
SET CONSTRAINTS ALL DEFERRED;


INSERT INTO "reference" VALUES 
(4,'Aw22-',NULL,'Accessiweb 2.2',4,'http://www.accessiweb.org/index.php/accessiweb-22-english-version.html',2);


INSERT INTO "theme" VALUES 
(31,'Aw22--1',NULL,'Images',1),
(32,'Aw22--2',NULL,'Cadres',2),
(33,'Aw22--3',NULL,'Couleurs',3),
(34,'Aw22--4',NULL,'Multimédia',4),
(35,'Aw22--5',NULL,'Tableaux',5),
(36,'Aw22--6',NULL,'Liens',6),
(37,'Aw22--7',NULL,'Script',7),
(38,'Aw22--8',NULL,'Éléments Obligatoires',8),
(39,'Aw22--9',NULL,'Structuration de l''information',9),
(40,'Aw22--10',NULL,'Présentation de l''information',10),
(41,'Aw22--11',NULL,'Formulaires',11),
(42,'Aw22--12',NULL,'Navigation',12),
(43,'Aw22--13',NULL,'Consultation',13);


INSERT INTO "criterion" VALUES 
(201,'Aw22--0101','','1.1',201,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-1-1 ',4,31),
(202,'Aw22--0102','','1.2',202,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-1-2 ',4,31),
(203,'Aw22--0103','','1.3',203,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-1-3 ',4,31),
(204,'Aw22--0104','','1.4',204,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-1-4 ',4,31),
(205,'Aw22--0105','','1.5',205,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-1-5 ',4,31),
(206,'Aw22--0106','','1.6',206,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-1-6 ',4,31),
(207,'Aw22--0107','','1.7',207,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-1-7 ',4,31),
(208,'Aw22--0108','','1.8',208,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-1-8 ',4,31),
(209,'Aw22--0109','','1.9',209,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-1-9 ',4,31),
(210,'Aw22--0201','','2.1',210,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-2-1 ',4,32),
(211,'Aw22--0202','','2.2',211,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-2-2 ',4,32),
(212,'Aw22--0301','','3.1',212,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-3-1 ',4,33),
(213,'Aw22--0302','','3.2',213,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-3-2 ',4,33),
(214,'Aw22--0303','','3.3',214,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-3-3 ',4,33),
(215,'Aw22--0304','','3.4',215,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-3-4 ',4,33),
(216,'Aw22--0401','','4.1',216,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-1 ',4,34),
(217,'Aw22--0402','','4.2',219,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-2 ',4,34),
(218,'Aw22--0403','','4.3',218,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-3 ',4,34),
(219,'Aw22--0404','','4.4',219,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-4 ',4,34),
(220,'Aw22--0405','','4.5',220,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-5 ',4,34),
(221,'Aw22--0406','','4.6',221,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-6 ',4,34),
(222,'Aw22--0407','','4.7',222,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-7 ',4,34),
(223,'Aw22--0408','','4.8',223,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-8 ',4,34),
(224,'Aw22--0409','','4.9',224,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-9 ',4,34),
(225,'Aw22--0410','','4.10',225,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-10 ',4,34),
(226,'Aw22--0411','','4.11',226,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-11 ',4,34),
(227,'Aw22--0412','','4.12',227,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-12 ',4,34),
(228,'Aw22--0413','','4.13',228,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-13 ',4,34),
(229,'Aw22--0414','','4.14',229,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-14 ',4,34),
(230,'Aw22--0415','','4.15',230,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-15 ',4,34),
(231,'Aw22--0416','','4.16',231,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-16 ',4,34),
(232,'Aw22--0417','','4.17',232,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-17 ',4,34),
(233,'Aw22--0418','','4.18',233,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-18 ',4,34),
(234,'Aw22--0419','','4.19',234,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-19 ',4,34),
(235,'Aw22--0420','','4.20',235,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-20 ',4,34),
(236,'Aw22--0421','','4.21',236,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-21 ',4,34),
(237,'Aw22--0422','','4.22',237,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-4-22 ',4,34),
(238,'Aw22--0501','','5.1',238,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-5-1 ',4,35),
(239,'Aw22--0502','','5.2',239,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-5-2 ',4,35),
(240,'Aw22--0503','','5.3',240,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-5-3 ',4,35),
(241,'Aw22--0504','','5.4',241,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-5-4 ',4,35),
(242,'Aw22--0505','','5.5',242,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-5-5 ',4,35),
(243,'Aw22--0506','','5.6',243,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-5-6 ',4,35),
(244,'Aw22--0507','','5.7',244,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-5-7 ',4,35),
(245,'Aw22--0508','','5.8',245,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-5-8 ',4,35),
(246,'Aw22--0601','','6.1',246,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-6-1 ',4,36),
(247,'Aw22--0602','','6.2',247,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-6-2 ',4,36),
(248,'Aw22--0603','','6.3',248,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-6-3 ',4,36),
(249,'Aw22--0604','','6.4',249,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-6-4 ',4,36),
(250,'Aw22--0605','','6.5',250,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-6-5 ',4,36),
(251,'Aw22--0606','','6.6',251,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-6-6 ',4,36),
(252,'Aw22--0701','','7.1',252,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-7-1 ',4,37),
(253,'Aw22--0702','','7.2',253,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-7-2 ',4,37),
(254,'Aw22--0703','','7.3',254,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-7-3 ',4,37),
(255,'Aw22--0704','','7.4',255,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-7-4 ',4,37),
(256,'Aw22--0705','','7.5',256,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-7-5 ',4,37),
(257,'Aw22--0706','','7.6',257,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-7-6 ',4,37),
(258,'Aw22--0801','','8.1',258,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-8-1 ',4,38),
(259,'Aw22--0802','','8.2',259,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-8-2 ',4,38),
(260,'Aw22--0803','','8.3',260,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-8-3 ',4,38),
(261,'Aw22--0804','','8.4',261,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-8-4 ',4,38),
(262,'Aw22--0805','','8.5',262,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-8-5 ',4,38),
(263,'Aw22--0806','','8.6',263,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-8-6 ',4,38),
(264,'Aw22--0807','','8.7',264,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-8-7 ',4,38),
(265,'Aw22--0808','','8.8',265,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-8-8 ',4,38),
(266,'Aw22--0809','','8.9',266,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-8-9 ',4,38),
(267,'Aw22--0810','','8.10',267,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-8-10 ',4,38),
(268,'Aw22--0901','','9.1',268,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-9-1 ',4,39),
(269,'Aw22--0902','','9.2',269,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-9-2 ',4,39),
(270,'Aw22--0903','','9.3',270,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-9-3 ',4,39),
(271,'Aw22--0904','','9.4',271,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-9-4 ',4,39),
(272,'Aw22--0905','','9.5',272,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-9-5 ',4,39),
(273,'Aw22--1001','','10.1',273,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-10-1 ',4,40),
(274,'Aw22--1002','','10.2',274,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-10-2 ',4,40),
(275,'Aw22--1003','','10.3',275,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-10-3 ',4,40),
(276,'Aw22--1004','','10.4',276,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-10-4 ',4,40),
(277,'Aw22--1005','','10.5',277,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-10-5 ',4,40),
(278,'Aw22--1006','','10.6',278,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-10-6 ',4,40),
(279,'Aw22--1007','','10.7',279,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-10-7 ',4,40),
(280,'Aw22--1008','','10.8',280,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-10-8 ',4,40),
(281,'Aw22--1009','','10.9',281,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-10-9 ',4,40),
(282,'Aw22--1010','','10.10',282,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-10-10 ',4,40),
(283,'Aw22--1011','','10.11',283,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-10-11 ',4,40),
(284,'Aw22--1012','','10.12',284,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-10-12 ',4,40),
(285,'Aw22--1013','','10.13',285,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-10-13 ',4,40),
(286,'Aw22--1014','','10.14',286,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-10-14 ',4,40),
(287,'Aw22--1015','','10.15',287,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-10-15 ',4,40),
(288,'Aw22--1101','','11.1',288,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-11-1 ',4,41),
(289,'Aw22--1102','','11.2',289,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-11-2 ',4,41),
(290,'Aw22--1103','','11.3',290,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-11-3 ',4,41),
(291,'Aw22--1104','','11.4',291,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-11-4 ',4,41),
(292,'Aw22--1105','','11.5',292,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-11-5 ',4,41),
(293,'Aw22--1106','','11.6',293,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-11-6 ',4,41),
(294,'Aw22--1107','','11.7',294,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-11-7 ',4,41),
(295,'Aw22--1108','','11.8',295,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-11-8 ',4,41),
(296,'Aw22--1109','','11.9',296,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-11-9 ',4,41),
(297,'Aw22--1110','','11.10',297,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-11-10 ',4,41),
(298,'Aw22--1111','','11.11',298,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-11-11 ',4,41),
(299,'Aw22--1112','','11.12',299,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-11-12 ',4,41),
(300,'Aw22--1113','','11.13',300,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-11-13 ',4,41),
(301,'Aw22--1114','','11.14',301,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-11-14 ',4,41),
(302,'Aw22--1115','','11.15',302,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-11-15 ',4,41),
(303,'Aw22--1201','','12.1',303,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-12-1 ',4,42),
(304,'Aw22--1202','','12.2',304,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-12-2 ',4,42),
(305,'Aw22--1203','','12.3',305,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-12-3 ',4,42),
(306,'Aw22--1204','','12.4',306,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-12-4 ',4,42),
(307,'Aw22--1205','','12.5',307,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-12-5 ',4,42),
(308,'Aw22--1206','','12.6',308,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-12-6 ',4,42),
(309,'Aw22--1207','','12.7',309,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-12-7 ',4,42),
(310,'Aw22--1208','','12.8',310,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-12-8 ',4,42),
(311,'Aw22--1209','','12.9',311,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-12-9 ',4,42),
(312,'Aw22--1210','','12.10',312,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-12-10 ',4,42),
(313,'Aw22--1211','','12.11',313,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-12-11 ',4,42),
(314,'Aw22--1212','','12.12',314,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-12-12 ',4,42),
(315,'Aw22--1213','','12.13',315,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-12-13 ',4,42),
(316,'Aw22--1214','','12.14',316,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-12-14 ',4,42),
(317,'Aw22--1301','','13.1',319,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-13-1 ',4,43),
(318,'Aw22--1302','','13.2',318,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-13-2 ',4,43),
(319,'Aw22--1303','','13.3',319,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-13-3 ',4,43),
(320,'Aw22--1304','','13.4',320,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-13-4 ',4,43),
(321,'Aw22--1305','','13.5',321,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-13-5 ',4,43),
(322,'Aw22--1306','','13.6',322,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-13-6 ',4,43),
(323,'Aw22--1307','','13.7',323,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-13-7 ',4,43),
(324,'Aw22--1308','','13.8',324,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-13-8 ',4,43),
(325,'Aw22--1309','','13.9',325,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-13-9 ',4,43),
(326,'Aw22--1310','','13.10',326,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-13-10 ',4,43),
(327,'Aw22--1311','','13.11',327,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-13-11 ',4,43),
(328,'Aw22--1312','','13.12',328,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-13-12 ',4,43),
(329,'Aw22--1313','','13.13',329,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-13-13 ',4,43),
(330,'Aw22--1314','','13.14',330,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-13-14 ',4,43),
(331,'Aw22--1315','','13.15',331,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-13-15 ',4,43),
(332,'Aw22--1316','','13.16',332,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-13-16 ',4,43),
(333,'Aw22--1317','','13.17',333,'http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#crit-13-17 ',4,43);


INSERT INTO "test" VALUES 
(501,'Aw22-01011','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.1.1',3010101,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01011','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.1.1',201,NULL,1,NULL,1,TRUE),
(502,'Aw22-01012','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.1.2',3010102,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01012','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.1.2',201,NULL,1,NULL,1,TRUE),
(503,'Aw22-01013','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.1.3',3010103,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01013','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.1.3',201,NULL,1,NULL,1,TRUE),
(504,'Aw22-01014','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.1.4',3010104,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01014','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.1.4',201,NULL,1,NULL,1,TRUE),
(505,'Aw22-01021','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.2.1',3010201,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01021','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.2.1',202,NULL,1,NULL,1,TRUE),
(506,'Aw22-01022','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.2.2',3010202,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01022','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.2.2',202,NULL,1,NULL,1,TRUE),
(507,'Aw22-01023','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.2.3',3010203,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01023','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.2.3',202,NULL,1,NULL,1,TRUE),
(508,'Aw22-01024','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.2.4',3010204,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01024','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.2.4',202,NULL,1,NULL,1,TRUE),
(509,'Aw22-01025','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.2.5',3010205,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01025','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.2.5',202,NULL,1,NULL,1,TRUE),
(510,'Aw22-01031','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.3.1',3010301,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01031','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.3.1',203,NULL,1,NULL,1,TRUE),
(511,'Aw22-01032','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.3.2',3010302,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01032','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.3.2',203,NULL,1,NULL,1,TRUE),
(512,'Aw22-01033','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.3.3',3010303,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01033','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.3.3',203,NULL,1,NULL,1,TRUE),
(513,'Aw22-01034','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.3.4',3010304,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01034','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.3.4',203,NULL,1,NULL,1,TRUE),
(514,'Aw22-01035','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.3.5',3010305,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01035','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.3.5',203,NULL,1,NULL,1,TRUE),
(515,'Aw22-01036','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.3.6',3010306,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01036','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.3.6',203,NULL,1,NULL,1,TRUE),
(516,'Aw22-01037','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.3.7',3010307,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01037','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.3.7',203,NULL,1,NULL,1,TRUE),
(517,'Aw22-01041','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.4.1',3010401,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01041','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.4.1',204,NULL,1,NULL,1,TRUE),
(518,'Aw22-01042','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.4.2',3010402,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01042','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.4.2',204,NULL,1,NULL,1,TRUE),
(519,'Aw22-01043','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.4.3',3010403,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01043','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.4.3',204,NULL,1,NULL,1,TRUE),
(520,'Aw22-01044','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.4.4',3010404,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01044','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.4.4',204,NULL,1,NULL,1,TRUE),
(521,'Aw22-01045','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.4.5',3010405,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01045','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.4.5',204,NULL,1,NULL,1,TRUE),
(522,'Aw22-01046','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.4.6',3010406,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01046','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.4.6',204,NULL,1,NULL,1,TRUE),
(523,'Aw22-01051','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.5.1',3010501,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01051','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.5.1',205,NULL,1,NULL,1,TRUE),
(524,'Aw22-01052','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.5.2',3010502,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01052','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.5.2',205,NULL,1,NULL,1,TRUE),
(525,'Aw22-01061','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.6.1',3010601,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01061','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.6.1',206,NULL,1,NULL,1,TRUE),
(526,'Aw22-01062','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.6.2',3010602,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01062','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.6.2',206,NULL,1,NULL,1,TRUE),
(527,'Aw22-01063','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.6.3',3010603,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01063','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.6.3',206,NULL,1,NULL,1,TRUE),
(528,'Aw22-01064','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.6.4',3010604,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01064','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.6.4',206,NULL,1,NULL,1,TRUE),
(529,'Aw22-01065','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.6.5',3010605,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01065','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.6.5',206,NULL,1,NULL,1,TRUE),
(530,'Aw22-01071','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.7.1',3010701,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01071','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.7.1',207,NULL,1,NULL,1,TRUE),
(531,'Aw22-01072','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.7.2',3010702,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01072','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.7.2',207,NULL,1,NULL,1,TRUE),
(532,'Aw22-01073','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.7.3',3010703,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01073','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.7.3',207,NULL,1,NULL,1,TRUE),
(533,'Aw22-01074','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.7.4',3010704,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01074','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.7.4',207,NULL,1,NULL,1,TRUE),
(534,'Aw22-01081','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.8.1',3010801,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01081','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.8.1',208,NULL,2,NULL,1,TRUE),
(535,'Aw22-01082','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.8.2',3010802,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01082','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.8.2',208,NULL,2,NULL,1,TRUE),
(536,'Aw22-01083','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.8.3',3010803,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01083','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.8.3',208,NULL,2,NULL,1,TRUE),
(537,'Aw22-01084','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.8.4',3010804,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01084','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.8.4',208,NULL,2,NULL,1,TRUE),
(538,'Aw22-01085','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.8.5',3010805,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01085','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.8.5',208,NULL,2,NULL,1,TRUE),
(539,'Aw22-01086','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.8.6',3010806,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01086','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.8.6',208,NULL,2,NULL,1,TRUE),
(540,'Aw22-01091','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.9.1',3010901,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01091','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.9.1',209,NULL,3,NULL,1,TRUE),
(541,'Aw22-01092','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.9.2',3010902,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01092','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.9.2',209,NULL,3,NULL,1,TRUE),
(542,'Aw22-01093','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.9.3',3010903,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01093','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.9.3',209,NULL,3,NULL,1,TRUE),
(543,'Aw22-01094','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.9.4',3010904,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01094','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.9.4',209,NULL,3,NULL,1,TRUE),
(544,'Aw22-01095','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.9.5',3010905,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01095','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.9.5',209,NULL,3,NULL,1,TRUE),
(545,'Aw22-01096','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#images','1.9.6',3010906,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule01096','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-1.9.6',209,NULL,3,NULL,1,TRUE),
(546,'Aw22-02011','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#cadres','2.1.1',3020101,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule02011','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-2.1.1',210,NULL,1,NULL,1,TRUE),
(547,'Aw22-02012','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#cadres','2.1.2',3020102,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule02012','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-2.1.2',210,NULL,1,NULL,1,TRUE),
(548,'Aw22-02021','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#cadres','2.2.1',3020201,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule02021','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-2.2.1',211,NULL,1,NULL,1,TRUE),
(549,'Aw22-02022','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#cadres','2.2.2',3020202,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule02022','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-2.2.2',211,NULL,1,NULL,1,TRUE),
(550,'Aw22-03011','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.1.1',3030101,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03011','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.1.1',212,NULL,1,NULL,1,TRUE),
(551,'Aw22-03012','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.1.2',3030102,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03012','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.1.2',212,NULL,1,NULL,1,TRUE),
(552,'Aw22-03013','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.1.3',3030103,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03013','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.1.3',212,NULL,1,NULL,1,TRUE),
(553,'Aw22-03014','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.1.4',3030104,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03014','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.1.4',212,NULL,1,NULL,1,TRUE),
(554,'Aw22-03015','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.1.5',3030105,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03015','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.1.5',212,NULL,1,NULL,1,TRUE),
(555,'Aw22-03016','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.1.6',3030106,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03016','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.1.6',212,NULL,1,NULL,1,TRUE),
(556,'Aw22-03021','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.2.1',3030201,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03021','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.2.1',213,NULL,1,NULL,1,TRUE),
(557,'Aw22-03022','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.2.2',3030202,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03022','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.2.2',213,NULL,1,NULL,1,TRUE),
(558,'Aw22-03023','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.2.3',3030203,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03023','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.2.3',213,NULL,1,NULL,1,TRUE),
(559,'Aw22-03024','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.2.4',3030204,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03024','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.2.4',213,NULL,1,NULL,1,TRUE),
(560,'Aw22-03025','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.2.5',3030205,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03025','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.2.5',213,NULL,1,NULL,1,TRUE),
(561,'Aw22-03026','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.2.6',3030206,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03026','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.2.6',213,NULL,1,NULL,1,TRUE),
(562,'Aw22-03031','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.3.1',3030301,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03031','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.3.1',214,NULL,2,NULL,1,TRUE),
(563,'Aw22-03032','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.3.2',3030302,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03032','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.3.2',214,NULL,2,NULL,1,TRUE),
(564,'Aw22-03033','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.3.3',3030303,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03033','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.3.3',214,NULL,2,NULL,1,TRUE),
(565,'Aw22-03034','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.3.4',3030304,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03034','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.3.4',214,NULL,2,NULL,1,TRUE),
(566,'Aw22-03041','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.4.1',3030401,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03041','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.4.1',215,NULL,3,NULL,1,TRUE),
(567,'Aw22-03042','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.4.2',3030402,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03042','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.4.2',215,NULL,3,NULL,1,TRUE),
(568,'Aw22-03043','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.4.3',3030403,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03043','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.4.3',215,NULL,3,NULL,1,TRUE),
(569,'Aw22-03044','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#couleurs','3.4.4',3030404,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule03044','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-3.4.4',215,NULL,3,NULL,1,TRUE),
(570,'Aw22-04011','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.1.1',3040101,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04011','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.1.1',216,NULL,1,NULL,1,TRUE),
(571,'Aw22-04012','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.1.2',3040102,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04012','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.1.2',216,NULL,1,NULL,1,TRUE),
(572,'Aw22-04013','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.1.3',3040103,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04013','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.1.3',216,NULL,1,NULL,1,TRUE),
(573,'Aw22-04014','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.1.4',3040104,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04014','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.1.4',216,NULL,1,NULL,1,TRUE),
(574,'Aw22-04021','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.2.1',3040201,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04021','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.2.1',217,NULL,1,NULL,1,TRUE),
(575,'Aw22-04022','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.2.2',3040202,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04022','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.2.2',217,NULL,1,NULL,1,TRUE),
(576,'Aw22-04023','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.2.3',3040203,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04023','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.2.3',217,NULL,1,NULL,1,TRUE),
(577,'Aw22-04031','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.3.1',3040301,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04031','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.3.1',218,NULL,1,NULL,1,TRUE),
(578,'Aw22-04041','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.4.1',3040401,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04041','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.4.1',219,NULL,1,NULL,1,TRUE),
(579,'Aw22-04051','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.5.1',3040501,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04051','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.5.1',220,NULL,1,NULL,1,TRUE),
(580,'Aw22-04052','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.5.2',3040502,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04052','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.5.2',220,NULL,1,NULL,1,TRUE),
(581,'Aw22-04053','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.5.3',3040503,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04053','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.5.3',220,NULL,1,NULL,1,TRUE),
(582,'Aw22-04061','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.6.1',3040601,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04061','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.6.1',221,NULL,2,NULL,1,TRUE),
(583,'Aw22-04062','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.6.2',3040602,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04062','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.6.2',221,NULL,2,NULL,1,TRUE),
(584,'Aw22-04071','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.7.1',3040701,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04071','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.7.1',222,NULL,2,NULL,1,TRUE),
(585,'Aw22-04072','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.7.2',3040702,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04072','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.7.2',222,NULL,2,NULL,1,TRUE),
(586,'Aw22-04081','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.8.1',3040801,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04081','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.8.1',223,NULL,2,NULL,1,TRUE),
(587,'Aw22-04082','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.8.2',3040802,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04082','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.8.2',223,NULL,2,NULL,1,TRUE),
(588,'Aw22-04091','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.9.1',3040901,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04091','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.9.1',224,NULL,3,NULL,1,TRUE),
(589,'Aw22-04092','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.9.2',3040902,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04092','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.9.2',224,NULL,3,NULL,1,TRUE),
(590,'Aw22-04101','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.10.1',3041001,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04101','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.10.1',225,NULL,3,NULL,1,TRUE),
(591,'Aw22-04102','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.10.2',3041002,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04102','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.10.2',225,NULL,3,NULL,1,TRUE),
(592,'Aw22-04111','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.11.1',3041101,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04111','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.11.1',226,NULL,3,NULL,1,TRUE),
(593,'Aw22-04112','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.11.2',3041102,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04112','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.11.2',226,NULL,3,NULL,1,TRUE),
(594,'Aw22-04121','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.12.1',3041201,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04121','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.12.1',227,NULL,3,NULL,1,TRUE),
(595,'Aw22-04122','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.12.2',3041202,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04122','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.12.2',227,NULL,3,NULL,1,TRUE),
(596,'Aw22-04131','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.13.1',3041301,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04131','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.13.1',228,NULL,3,NULL,1,TRUE),
(597,'Aw22-04132','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.13.2',3041302,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04132','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.13.2',228,NULL,3,NULL,1,TRUE),
(598,'Aw22-04133','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.13.3',3041303,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04133','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.13.3',228,NULL,3,NULL,1,TRUE),
(599,'Aw22-04141','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.14.1',3041401,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04141','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.14.1',229,NULL,3,NULL,1,TRUE),
(600,'Aw22-04142','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.14.2',3041402,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04142','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.14.2',229,NULL,3,NULL,1,TRUE),
(601,'Aw22-04151','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.15.1',3041501,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04151','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.15.1',230,NULL,1,NULL,1,TRUE),
(602,'Aw22-04152','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.15.2',3041502,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04152','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.15.2',230,NULL,1,NULL,1,TRUE),
(603,'Aw22-04161','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.16.1',3041601,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04161','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.16.1',231,NULL,1,NULL,1,TRUE),
(604,'Aw22-04162','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.16.2',3041602,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04162','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.16.2',231,NULL,1,NULL,1,TRUE),
(605,'Aw22-04171','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.17.1',3041701,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04171','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.17.1',232,NULL,1,NULL,1,TRUE),
(606,'Aw22-04181','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.18.1',3041801,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04181','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.18.1',233,NULL,1,NULL,1,TRUE),
(607,'Aw22-04191','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.19.1',3041901,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04191','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.19.1',234,NULL,3,NULL,1,TRUE),
(608,'Aw22-04201','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.20.1',3042001,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04201','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.20.1',235,NULL,1,NULL,1,TRUE),
(609,'Aw22-04202','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.20.2',3042002,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04202','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.20.2',235,NULL,1,NULL,1,TRUE),
(610,'Aw22-04203','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.20.3',3042003,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04203','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.20.3',235,NULL,1,NULL,1,TRUE),
(611,'Aw22-04211','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.21.1',3042101,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04211','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.21.1',236,NULL,1,NULL,1,TRUE),
(612,'Aw22-04212','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.21.2',3042102,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04212','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.21.2',236,NULL,1,NULL,1,TRUE),
(613,'Aw22-04221','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#multimedia','4.22.1',3042201,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule04221','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-4.22.1',237,NULL,1,NULL,1,TRUE),
(614,'Aw22-05011','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#tableaux','5.1.1',3050101,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule05011','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-5.1.1',238,NULL,1,NULL,1,TRUE),
(615,'Aw22-05021','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#tableaux','5.2.1',3050201,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule05021','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-5.2.1',239,NULL,1,NULL,1,TRUE),
(616,'Aw22-05022','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#tableaux','5.2.2',3050202,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule05022','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-5.2.2',239,NULL,1,NULL,1,TRUE),
(617,'Aw22-05031','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#tableaux','5.3.1',3050301,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule05031','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-5.3.1',240,NULL,1,NULL,1,TRUE),
(618,'Aw22-05041','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#tableaux','5.4.1',3050401,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule05041','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-5.4.1',241,NULL,1,NULL,1,TRUE),
(619,'Aw22-05051','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#tableaux','5.5.1',3050501,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule05051','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-5.5.1',242,NULL,1,NULL,1,TRUE),
(620,'Aw22-05061','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#tableaux','5.6.1',3050601,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule05061','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-5.6.1',243,NULL,1,NULL,1,TRUE),
(621,'Aw22-05062','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#tableaux','5.6.2',3050602,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule05062','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-5.6.2',243,NULL,1,NULL,1,TRUE),
(622,'Aw22-05071','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#tableaux','5.7.1',3050701,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule05071','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-5.7.1',244,NULL,1,NULL,1,TRUE),
(623,'Aw22-05072','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#tableaux','5.7.2',3050702,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule05072','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-5.7.2',244,NULL,1,NULL,1,TRUE),
(624,'Aw22-05073','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#tableaux','5.7.3',3050703,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule05073','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-5.7.3',244,NULL,1,NULL,1,TRUE),
(625,'Aw22-05074','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#tableaux','5.7.4',3050704,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule05074','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-5.7.4',244,NULL,1,NULL,1,TRUE),
(626,'Aw22-05081','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#tableaux','5.8.1',3050801,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule05081','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-5.8.1',245,NULL,1,NULL,1,TRUE),
(627,'Aw22-06011','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.1.1',3060101,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06011','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.1.1',246,NULL,1,NULL,1,TRUE),
(628,'Aw22-06012','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.1.2',3060102,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06012','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.1.2',246,NULL,1,NULL,1,TRUE),
(629,'Aw22-06013','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.1.3',3060103,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06013','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.1.3',246,NULL,1,NULL,1,TRUE),
(630,'Aw22-06014','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.1.4',3060104,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06014','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.1.4',246,NULL,1,NULL,1,TRUE),
(631,'Aw22-06021','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.2.1',3060201,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06021','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.2.1',247,NULL,1,NULL,1,TRUE),
(632,'Aw22-06022','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.2.2',3060202,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06022','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.2.2',247,NULL,1,NULL,1,TRUE),
(633,'Aw22-06023','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.2.3',3060203,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06023','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.2.3',247,NULL,1,NULL,1,TRUE),
(634,'Aw22-06024','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.2.4',3060204,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06024','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.2.4',247,NULL,1,NULL,1,TRUE),
(635,'Aw22-06031','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.3.1',3060301,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06031','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.3.1',248,NULL,3,NULL,1,TRUE),
(636,'Aw22-06032','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.3.2',3060302,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06032','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.3.2',248,NULL,3,NULL,1,TRUE),
(637,'Aw22-06033','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.3.3',3060303,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06033','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.3.3',248,NULL,3,NULL,1,TRUE),
(638,'Aw22-06034','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.3.4',3060304,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06034','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.3.4',248,NULL,3,NULL,1,TRUE),
(639,'Aw22-06041','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.4.1',3060401,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06041','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.4.1',249,NULL,1,NULL,1,TRUE),
(640,'Aw22-06042','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.4.2',3060403,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06042','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.4.2',249,NULL,1,NULL,1,TRUE),
(641,'Aw22-06043','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.4.3',3060403,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06043','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.4.3',249,NULL,1,NULL,1,TRUE),
(642,'Aw22-06044','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.4.4',3060404,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06044','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.4.4',249,NULL,1,NULL,1,TRUE),
(643,'Aw22-06051','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.5.1',3060501,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06051','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.5.1',250,NULL,1,NULL,1,TRUE),
(644,'Aw22-06052','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.5.2',3060502,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06052','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.5.2',250,NULL,1,NULL,1,TRUE),
(645,'Aw22-06053','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.5.3',3060503,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06053','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.5.3',250,NULL,1,NULL,1,TRUE),
(646,'Aw22-06061','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#liens','6.6.1',3060601,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule06061','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-6.6.1',251,NULL,1,NULL,1,TRUE),
(647,'Aw22-07011','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#script','7.1.1',3070101,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule07011','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-7.1.1',252,NULL,1,NULL,1,TRUE),
(648,'Aw22-07012','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#script','7.1.2',3070102,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule07012','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-7.1.2',252,NULL,1,NULL,1,TRUE),
(649,'Aw22-07021','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#script','7.2.1',3070201,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule07021','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-7.2.1',253,NULL,1,NULL,1,TRUE),
(650,'Aw22-07022','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#script','7.2.2',3070202,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule07022','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-7.2.2',253,NULL,1,NULL,1,TRUE),
(651,'Aw22-07031','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#script','7.3.1',3070301,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule07031','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-7.3.1',254,NULL,1,NULL,1,TRUE),
(652,'Aw22-07032','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#script','7.3.2',3070302,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule07032','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-7.3.2',254,NULL,1,NULL,1,TRUE),
(653,'Aw22-07033','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#script','7.3.3',3070303,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule07033','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-7.3.3',254,NULL,1,NULL,1,TRUE),
(654,'Aw22-07041','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#script','7.4.1',3070401,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule07041','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-7.4.1',255,NULL,1,NULL,1,TRUE),
(655,'Aw22-07042','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#script','7.4.2',3070402,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule07042','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-7.4.2',255,NULL,1,NULL,1,TRUE),
(656,'Aw22-07051','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#script','7.5.1',3070501,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule07051','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-7.5.1',256,NULL,1,NULL,1,TRUE),
(657,'Aw22-07061','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#script','7.6.1',3070601,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule07061','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-7.6.1',257,NULL,3,NULL,1,TRUE),
(658,'Aw22-08011','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','8.1.1',3080101,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule08011','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-8.1.1',258,NULL,1,NULL,1,TRUE),
(659,'Aw22-08012','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','8.1.2',3080102,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule08012','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-8.1.2',258,NULL,1,NULL,1,TRUE),
(660,'Aw22-08013','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#elements','8.1.3',3080103,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule08013','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-8.1.3',258,NULL,1,NULL,1,TRUE),
(661,'Aw22-08021','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#elements','8.2.1',3080201,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule08021','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-8.2.1',259,NULL,1,NULL,1,TRUE),
(662,'Aw22-08022','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#elements','8.2.2',3080202,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule08022','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-8.2.2',259,NULL,1,NULL,1,TRUE),
(663,'Aw22-08031','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','8.3.1',3080301,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule08031','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-8.3.1',260,NULL,1,NULL,1,TRUE),
(664,'Aw22-08041','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','8.4.1',3080401,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule08041','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-8.4.1',261,NULL,1,NULL,1,TRUE),
(665,'Aw22-08051','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#elements','8.5.1',3080501,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule08051','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-8.5.1',262,NULL,1,NULL,1,TRUE),
(666,'Aw22-08061','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#elements','8.6.1',3080601,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule08061','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-8.6.1',263,NULL,1,NULL,1,TRUE),
(667,'Aw22-08071','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#elements','8.7.1',3080701,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule08071','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-8.7.1',264,NULL,2,NULL,1,TRUE),
(668,'Aw22-08081','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#elements','8.8.1',3080801,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule08081','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-8.8.1',265,NULL,2,NULL,1,TRUE),
(669,'Aw22-08082','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#elements','8.8.2',3080802,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule08082','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-8.8.2',265,NULL,2,NULL,1,TRUE),
(670,'Aw22-08091','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#elements','8.9.1',3080901,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule08091','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-8.9.1',266,NULL,1,NULL,1,TRUE),
(671,'Aw22-08101','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#elements','8.10.1',3081001,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule08101','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-8.10.1',267,NULL,1,NULL,1,TRUE),
(672,'Aw22-09011','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#structure','9.1.1',3090101,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule09011','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-9.1.1',268,NULL,1,NULL,1,TRUE),
(673,'Aw22-09012','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#structure','9.1.2',3090102,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule09012','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-9.1.2',268,NULL,1,NULL,1,TRUE),
(674,'Aw22-09013','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#structure','9.1.3',3090103,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule09013','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-9.1.3',268,NULL,1,NULL,1,TRUE),
(675,'Aw22-09014','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#structure','9.1.4',3090104,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule09014','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-9.1.4',268,NULL,1,NULL,1,TRUE),
(676,'Aw22-09021','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#structure','9.2.1',3090201,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule09021','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-9.2.1',269,NULL,1,NULL,1,TRUE),
(677,'Aw22-09022','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#structure','9.2.2',3090202,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule09022','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-9.2.2',269,NULL,1,NULL,1,TRUE),
(678,'Aw22-09023','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#structure','9.2.3',3090203,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule09023','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-9.2.3',269,NULL,1,NULL,1,TRUE),
(679,'Aw22-09031','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#structure','9.3.1',3090301,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule09031','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-9.3.1',270,NULL,3,NULL,1,TRUE),
(680,'Aw22-09032','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#structure','9.3.2',3090302,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule09032','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-9.3.2',270,NULL,3,NULL,1,TRUE),
(681,'Aw22-09041','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#structure','9.4.1',3090401,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule09041','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-9.4.1',271,NULL,3,NULL,1,TRUE),
(682,'Aw22-09042','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#structure','9.4.2',3090402,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule09042','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-9.4.2',271,NULL,3,NULL,1,TRUE),
(683,'Aw22-09051','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#structure','9.5.1',3090501,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule09051','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-9.5.1',272,NULL,1,NULL,1,TRUE),
(684,'Aw22-09052','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#structure','9.5.2',3090502,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule09052','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-9.5.2',272,NULL,1,NULL,1,TRUE),
(685,'Aw22-10011','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.1.1',3100101,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10011','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.1.1',273,NULL,1,NULL,1,TRUE),
(686,'Aw22-10012','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.1.2',3100102,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10012','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.1.2',273,NULL,1,NULL,1,TRUE),
(687,'Aw22-10013','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.1.3',3100103,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10013','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.1.3',273,NULL,1,NULL,1,TRUE),
(688,'Aw22-10021','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.2.1',3100201,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10021','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.2.1',274,NULL,1,NULL,1,TRUE),
(689,'Aw22-10022','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.2.2',3100202,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10022','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.2.2',274,NULL,1,NULL,1,TRUE),
(690,'Aw22-10023','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.2.3',3100203,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10023','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.2.3',274,NULL,1,NULL,1,TRUE),
(691,'Aw22-10031','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.3.1',3100301,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10031','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.3.1',275,NULL,1,NULL,1,TRUE),
(692,'Aw22-10041','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.4.1',3100401,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10041','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.4.1',276,NULL,2,NULL,1,TRUE),
(693,'Aw22-10042','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.4.2',3100402,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10042','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.4.2',276,NULL,2,NULL,1,TRUE),
(694,'Aw22-10043','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.4.3',3100403,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10043','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.4.3',276,NULL,2,NULL,1,TRUE),
(695,'Aw22-10051','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.5.1',3100501,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10051','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.5.1',277,NULL,2,NULL,1,TRUE),
(696,'Aw22-10052','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.5.2',3100502,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10052','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.5.2',277,NULL,2,NULL,1,TRUE),
(697,'Aw22-10053','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.5.3',3100503,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10053','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.5.3',277,NULL,2,NULL,1,TRUE),
(698,'Aw22-10061','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.6.1',3100601,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10061','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.6.1',278,NULL,1,NULL,1,TRUE),
(699,'Aw22-10071','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.7.1',3100701,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10071','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.7.1',279,NULL,1,NULL,1,TRUE),
(700,'Aw22-10072','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.7.2',3100702,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10072','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.7.2',279,NULL,1,NULL,1,TRUE),
(701,'Aw22-10073','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.7.3',3100703,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10073','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.7.3',279,NULL,1,NULL,1,TRUE),
(702,'Aw22-10081','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.8.1',3100801,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10081','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.8.1',280,NULL,3,NULL,1,TRUE),
(703,'Aw22-10082','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.8.2',3100802,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10082','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.8.2',280,NULL,3,NULL,1,TRUE),
(704,'Aw22-10083','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.8.3',3100803,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10083','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.8.3',280,NULL,3,NULL,1,TRUE),
(705,'Aw22-10084','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.8.4',3100804,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10084','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.8.4',280,NULL,3,NULL,1,TRUE),
(706,'Aw22-10091','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.9.1',3100901,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10091','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.9.1',281,NULL,3,NULL,1,TRUE),
(707,'Aw22-10101','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.10.1',3101001,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10101','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.10.1',282,NULL,3,NULL,1,TRUE),
(708,'Aw22-10111','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.11.1',3101101,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10111','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.11.1',283,NULL,3,NULL,1,TRUE),
(709,'Aw22-10121','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.12.1',3101201,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10121','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.12.1',284,NULL,3,NULL,1,TRUE),
(710,'Aw22-10122','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.12.2',3101202,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10122','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.12.2',284,NULL,3,NULL,1,TRUE),
(711,'Aw22-10131','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.13.1',3101301,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10131','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.13.1',285,NULL,1,NULL,1,TRUE),
(712,'Aw22-10141','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.14.1',3101401,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10141','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.14.1',286,NULL,1,NULL,1,TRUE),
(713,'Aw22-10142','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.14.2',3101402,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10142','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.14.2',286,NULL,1,NULL,1,TRUE),
(714,'Aw22-10143','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.14.3',3101403,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10143','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.14.3',286,NULL,1,NULL,1,TRUE),
(715,'Aw22-10144','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.14.4',3101404,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10144','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.14.4',286,NULL,1,NULL,1,TRUE),
(716,'Aw22-10151','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.15.1',3101501,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10151','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.15.1',287,NULL,1,NULL,1,TRUE),
(717,'Aw22-10152','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.15.2',3101502,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10152','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.15.2',287,NULL,1,NULL,1,TRUE),
(718,'Aw22-10153','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.15.3',3101503,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10153','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.15.3',287,NULL,1,NULL,1,TRUE),
(719,'Aw22-10154','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#presentation','10.15.4',3101504,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule10154','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-10.15.4',287,NULL,1,NULL,1,TRUE),
(720,'Aw22-11011','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.1.1',3110101,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11011','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.1.1',288,NULL,1,NULL,1,TRUE),
(721,'Aw22-11012','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.1.2',3110102,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11012','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.1.2',288,NULL,1,NULL,1,TRUE),
(722,'Aw22-11013','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.1.3',3110103,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11013','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.1.3',288,NULL,1,NULL,1,TRUE),
(723,'Aw22-11021','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.2.1',3110201,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11021','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.2.1',289,NULL,1,NULL,1,TRUE),
(724,'Aw22-11022','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.2.2',3110202,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11022','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.2.2',289,NULL,1,NULL,1,TRUE),
(725,'Aw22-11031','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.3.1',3110301,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11031','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.3.1',290,NULL,2,NULL,1,TRUE),
(726,'Aw22-11032','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.3.2',3110302,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11032','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.3.2',290,NULL,2,NULL,1,TRUE),
(727,'Aw22-11041','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.4.1',3110401,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11041','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.4.1',291,NULL,1,NULL,1,TRUE),
(728,'Aw22-11051','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.5.1',3110501,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11051','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.5.1',292,NULL,1,NULL,1,TRUE),
(729,'Aw22-11061','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.6.1',3110601,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11061','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.6.1',293,NULL,1,NULL,1,TRUE),
(730,'Aw22-11071','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.7.1',3110701,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11071','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.7.1',294,NULL,1,NULL,1,TRUE),
(731,'Aw22-11081','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.8.1',3110801,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11081','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.8.1',295,NULL,1,NULL,1,TRUE),
(732,'Aw22-11082','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.8.2',3110802,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11082','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.8.2',295,NULL,1,NULL,1,TRUE),
(733,'Aw22-11083','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.8.3',3110803,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11083','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.8.3',295,NULL,1,NULL,1,TRUE),
(734,'Aw22-11091','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.9.1',3110901,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11091','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.9.1',296,NULL,1,NULL,1,TRUE),
(735,'Aw22-11101','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.10.1',3111001,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11101','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.10.1',297,NULL,1,NULL,1,TRUE),
(736,'Aw22-11102','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.10.2',3111002,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11102','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.10.2',297,NULL,1,NULL,1,TRUE),
(737,'Aw22-11103','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.10.3',3111003,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11103','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.10.3',297,NULL,1,NULL,1,TRUE),
(738,'Aw22-11111','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.11.1',3111101,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11111','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.11.1',298,NULL,2,NULL,1,TRUE),
(739,'Aw22-11112','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.11.2',3111102,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11112','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.11.2',298,NULL,2,NULL,1,TRUE),
(740,'Aw22-11121','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.12.1',3111201,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11121','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.12.1',299,NULL,2,NULL,1,TRUE),
(741,'Aw22-11122','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.12.2',3111202,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11122','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.12.2',299,NULL,2,NULL,1,TRUE),
(742,'Aw22-11131','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.13.1',3111301,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11131','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.13.1',300,NULL,3,NULL,1,TRUE),
(743,'Aw22-11132','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.13.2',3111302,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11132','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.13.2',300,NULL,3,NULL,1,TRUE),
(744,'Aw22-11141','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.14.1',3111401,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11141','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.14.1',301,NULL,3,NULL,1,TRUE),
(745,'Aw22-11142','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.14.2',3111402,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11142','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.14.2',301,NULL,3,NULL,1,TRUE),
(746,'Aw22-11151','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#formulaire','11.15.1',3111501,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule11151','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-11.15.1',302,NULL,3,NULL,1,TRUE),
(747,'Aw22-12011','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.1.1',3120101,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12011','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.1.1',303,NULL,2,NULL,1,TRUE),
(748,'Aw22-12021','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.2.1',3120201,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12021','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.2.1',304,NULL,2,NULL,1,TRUE),
(749,'Aw22-12022','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.2.2',3120202,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12022','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.2.2',304,NULL,2,NULL,1,TRUE),
(750,'Aw22-12031','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.3.1',3120301,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12031','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.3.1',305,NULL,2,NULL,1,TRUE),
(751,'Aw22-12032','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.3.2',3120302,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12032','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.3.2',305,NULL,2,NULL,1,TRUE),
(752,'Aw22-12041','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.4.1',3120401,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12041','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.4.1',306,NULL,2,NULL,1,TRUE),
(753,'Aw22-12042','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.4.2',3120402,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12042','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.4.2',306,NULL,2,NULL,1,TRUE),
(754,'Aw22-12043','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.4.3',3120403,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12043','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.4.3',306,NULL,2,NULL,1,TRUE),
(755,'Aw22-12051','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.5.1',3120501,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12051','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.5.1',307,NULL,2,NULL,1,TRUE),
(756,'Aw22-12052','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.5.2',3120502,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12052','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.5.2',307,NULL,2,NULL,1,TRUE),
(757,'Aw22-12053','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.5.3',3120503,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12053','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.5.3',307,NULL,2,NULL,1,TRUE),
(758,'Aw22-12061','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.6.1',3120601,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12061','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.6.1',308,NULL,2,NULL,1,TRUE),
(759,'Aw22-12062','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.6.2',3120602,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12062','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.6.2',308,NULL,2,NULL,1,TRUE),
(760,'Aw22-12063','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.6.3',3120603,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12063','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.6.3',308,NULL,2,NULL,1,TRUE),
(761,'Aw22-12071','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.7.1',3120701,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12071','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.7.1',309,NULL,2,NULL,1,TRUE),
(762,'Aw22-12081','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.8.1',3120801,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12081','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.8.1',310,NULL,3,NULL,1,TRUE),
(763,'Aw22-12091','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.9.1',3120901,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12091','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.9.1',311,NULL,3,NULL,1,TRUE),
(764,'Aw22-12101','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.10.1',3121001,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12101','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.10.1',312,NULL,1,NULL,1,TRUE),
(765,'Aw22-12102','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.10.2',3121002,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12102','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.10.2',312,NULL,1,NULL,1,TRUE),
(766,'Aw22-12103','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.10.3',3121003,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12103','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.10.3',312,NULL,1,NULL,1,TRUE),
(767,'Aw22-12111','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.11.1',3121101,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12111','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.11.1',313,NULL,1,NULL,1,TRUE),
(768,'Aw22-12112','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.11.2',3121102,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12112','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.11.2',313,NULL,1,NULL,1,TRUE),
(769,'Aw22-12113','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.11.3',3121103,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12113','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.11.3',313,NULL,1,NULL,1,TRUE),
(770,'Aw22-12114','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.11.4',3121104,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12114','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.11.4',313,NULL,1,NULL,1,TRUE),
(771,'Aw22-12121','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.12.1',3121201,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12121','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.12.1',314,NULL,3,NULL,1,TRUE),
(772,'Aw22-12131','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.13.1',3121301,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12131','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.13.1',315,NULL,1,NULL,1,TRUE),
(773,'Aw22-12132','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.13.2',3121302,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12132','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.13.2',315,NULL,1,NULL,1,TRUE),
(774,'Aw22-12141','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#navigation','12.14.1',3121401,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule12141','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-12.14.1',316,NULL,1,NULL,1,TRUE),
(775,'Aw22-13011','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.1.1',3130101,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13011','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.1.1',317,NULL,1,NULL,1,TRUE),
(776,'Aw22-13012','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.1.2',3130102,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13012','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.1.2',317,NULL,1,NULL,1,TRUE),
(777,'Aw22-13013','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.1.3',3130103,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13013','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.1.3',317,NULL,1,NULL,1,TRUE),
(778,'Aw22-13014','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.1.4',3130104,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13014','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.1.4',317,NULL,1,NULL,1,TRUE),
(779,'Aw22-13015','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.1.5',3130105,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13015','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.1.5',317,NULL,1,NULL,1,TRUE),
(780,'Aw22-13021','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.2.1',3130201,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13021','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.2.1',318,NULL,1,NULL,1,TRUE),
(781,'Aw22-13022','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.2.2',3130202,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13022','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.2.2',318,NULL,1,NULL,1,TRUE),
(782,'Aw22-13023','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.2.3',3130203,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13023','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.2.3',318,NULL,1,NULL,1,TRUE),
(783,'Aw22-13031','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.3.1',3130301,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13031','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.3.1',319,NULL,1,NULL,1,TRUE),
(784,'Aw22-13041','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.4.1',3130401,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13041','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.4.1',320,NULL,3,NULL,1,TRUE),
(785,'Aw22-13051','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.5.1',3130501,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13051','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.5.1',321,NULL,3,NULL,1,TRUE),
(786,'Aw22-13061','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.6.1',3130601,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13061','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.6.1',322,NULL,1,NULL,1,TRUE),
(787,'Aw22-13062','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.6.2',3130602,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13062','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.6.2',322,NULL,1,NULL,1,TRUE),
(788,'Aw22-13063','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.6.3',3130603,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13063','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.6.3',322,NULL,1,NULL,1,TRUE),
(789,'Aw22-13071','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.7.1',3130701,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13071','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.7.1',323,NULL,1,NULL,1,TRUE),
(790,'Aw22-13081','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.8.1',3130801,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13081','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.8.1',324,NULL,1,NULL,1,TRUE),
(791,'Aw22-13091','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.9.1',3130901,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13091','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.9.1',325,NULL,3,NULL,1,TRUE),
(792,'Aw22-13101','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.10.1',3131001,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13101','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.10.1',326,NULL,3,NULL,1,TRUE),
(793,'Aw22-13111','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.11.1',3131101,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13111','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.11.1',327,NULL,1,NULL,1,TRUE),
(794,'Aw22-13121','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.12.1',3131201,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13121','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.12.1',328,NULL,1,NULL,1,TRUE),
(795,'Aw22-13131','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.13.1',3131301,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13131','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.13.1',329,NULL,3,NULL,1,TRUE),
(796,'Aw22-13141','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.14.1',3131401,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13141','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.14.1',330,NULL,3,NULL,1,TRUE),
(797,'Aw22-13151','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.15.1',3131501,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13151','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.15.1',331,NULL,1,NULL,1,TRUE),
(798,'Aw22-13152','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.15.2',3131502,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13152','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.15.2',331,NULL,1,NULL,1,TRUE),
(799,'Aw22-13153','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.15.3',3131503,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13153','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.15.3',331,NULL,1,NULL,1,TRUE),
(800,'Aw22-13154','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.15.4',3131504,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13154','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.15.4',331,NULL,1,NULL,1,TRUE),
(801,'Aw22-13161','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.16.1',3131601,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13161','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.16.1',332,NULL,3,NULL,1,TRUE),
(802,'Aw22-13162','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.16.2',3131602,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13162','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.16.2',332,NULL,3,NULL,1,TRUE),
(803,'Aw22-13163','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.16.3',3131603,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13163','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.16.3',332,NULL,3,NULL,1,TRUE),
(804,'Aw22-13164','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.16.4',3131604,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13164','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.16.4',332,NULL,3,NULL,1,TRUE),
(805,'Aw22-13171','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.17.1',3131701,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13171','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.17.1',333,NULL,1,NULL,1,TRUE),
(806,'Aw22-13172','http://www.accessiweb.org/index.php/accessiweb_2.2_liste_generale.html#consultation','13.17.2',3131702,1.0,'accessiweb2.2','org.tanaguru.rules.accessiweb22.Aw22Rule13172','https://github.com/Tanaguru/Tanaguru-rules-AccessiWeb-2.2-doc/wiki/Rule-13.17.2',333,NULL,1,NULL,1,TRUE);


update test set no_process=FALSE WHERE 
cd_test='Aw22--01011' or 
cd_test='Aw22--01012' or 
cd_test='Aw22--01013' or 
cd_test='Aw22--01014' or 
cd_test='Aw22--01021' or 
cd_test='Aw22--01022' or 
cd_test='Aw22--01023' or 
cd_test='Aw22--01024' or 
cd_test='Aw22--01025' or 
cd_test='Aw22--01031' or 
cd_test='Aw22--01032' or 
cd_test='Aw22--01033' or 
cd_test='Aw22--01034' or 
cd_test='Aw22--01035' or 
cd_test='Aw22--01036' or 
cd_test='Aw22--01041' or 
cd_test='Aw22--01042' or 
cd_test='Aw22--01043' or 
cd_test='Aw22--01044' or 
cd_test='Aw22--01045' or 
cd_test='Aw22--01046' or 
cd_test='Aw22--01051' or 
cd_test='Aw22--01052' or 
cd_test='Aw22--01061' or 
cd_test='Aw22--01062' or 
cd_test='Aw22--01063' or 
cd_test='Aw22--01064' or 
cd_test='Aw22--01065' or 
cd_test='Aw22--01071' or 
cd_test='Aw22--01072' or 
cd_test='Aw22--01073' or 
cd_test='Aw22--01074' or 
cd_test='Aw22--01081' or 
cd_test='Aw22--01082' or 
cd_test='Aw22--01083' or 
cd_test='Aw22--01084' or 
cd_test='Aw22--01085' or 
cd_test='Aw22--01086' or 
cd_test='Aw22--01091' or 
cd_test='Aw22--01092' or 
cd_test='Aw22--01093' or 
cd_test='Aw22--01094' or 
cd_test='Aw22--01095' or 
cd_test='Aw22--01096' or 
cd_test='Aw22--02011' or 
cd_test='Aw22--02012' or 
cd_test='Aw22--02021' or 
cd_test='Aw22--02022' or
cd_test='Aw22--03031' or
cd_test='Aw22--03032' or
cd_test='Aw22--03033' or
cd_test='Aw22--03034' or
cd_test='Aw22--03041' or
cd_test='Aw22--03042' or
cd_test='Aw22--03043' or
cd_test='Aw22--03044' or
cd_test='Aw22--04014' or 
cd_test='Aw22--04053' or 
cd_test='Aw22--04133' or 
cd_test='Aw22--04181' or 
cd_test='Aw22--04191' or 
cd_test='Aw22--04221' or 
cd_test='Aw22--05011' or 
cd_test='Aw22--05021' or 
cd_test='Aw22--05022' or 
cd_test='Aw22--05031' or 
cd_test='Aw22--05041' or 
cd_test='Aw22--05051' or 
cd_test='Aw22--05061' or 
cd_test='Aw22--05062' or 
cd_test='Aw22--05071' or 
cd_test='Aw22--05072' or 
cd_test='Aw22--05073' or 
cd_test='Aw22--05074' or 
cd_test='Aw22--05081' or 
cd_test='Aw22--06011' or 
cd_test='Aw22--06012' or 
cd_test='Aw22--06013' or 
cd_test='Aw22--06014' or 
cd_test='Aw22--06021' or 
cd_test='Aw22--06022' or 
cd_test='Aw22--06023' or 
cd_test='Aw22--06024' or 
cd_test='Aw22--06031' or 
cd_test='Aw22--06032' or 
cd_test='Aw22--06033' or 
cd_test='Aw22--06034' or 
cd_test='Aw22--06041' or 
cd_test='Aw22--06042' or 
cd_test='Aw22--06043' or 
cd_test='Aw22--06044' or 
cd_test='Aw22--06051' or 
cd_test='Aw22--06052' or 
cd_test='Aw22--06053' or 
cd_test='Aw22--06061' or 
cd_test='Aw22--07051' or 
cd_test='Aw22--08011' or 
cd_test='Aw22--08012' or 
cd_test='Aw22--08013' or 
cd_test='Aw22--08031' or 
cd_test='Aw22--08041' or 
cd_test='Aw22--08051' or 
cd_test='Aw22--08061' or 
cd_test='Aw22--08071' or 
cd_test='Aw22--08081' or 
cd_test='Aw22--08082' or 
cd_test='Aw22--08091' or 
cd_test='Aw22--09011' or 
cd_test='Aw22--09012' or 
cd_test='Aw22--09014' or 
cd_test='Aw22--10011' or 
cd_test='Aw22--10012' or 
cd_test='Aw22--10041' or 
cd_test='Aw22--10042' or 
cd_test='Aw22--10071' or 
cd_test='Aw22--10083' or 
cd_test='Aw22--10084' or 
cd_test='Aw22--10131' or 
cd_test='Aw22--11011' or 
cd_test='Aw22--11012' or 
cd_test='Aw22--11013' or 
cd_test='Aw22--11021' or 
cd_test='Aw22--11022' or 
cd_test='Aw22--11031' or 
cd_test='Aw22--11032' or 
cd_test='Aw22--11041' or 
cd_test='Aw22--11051' or 
cd_test='Aw22--11061' or 
cd_test='Aw22--11071' or 
cd_test='Aw22--11081' or 
cd_test='Aw22--11082' or 
cd_test='Aw22--11083' or 
cd_test='Aw22--11091' or 
cd_test='Aw22--11101' or 
cd_test='Aw22--11102' or 
cd_test='Aw22--11103' or 
cd_test='Aw22--11111' or 
cd_test='Aw22--11112' or 
cd_test='Aw22--11121' or 
cd_test='Aw22--11122' or 
cd_test='Aw22--11131' or 
cd_test='Aw22--11132' or 
cd_test='Aw22--11141' or 
cd_test='Aw22--11142' or 
cd_test='Aw22--11151' or
cd_test='Aw22--12011' or
cd_test='Aw22--12021' or
cd_test='Aw22--12022' or
cd_test='Aw22--12031' or
cd_test='Aw22--12032' or
cd_test='Aw22--12051' or
cd_test='Aw22--12052' or
cd_test='Aw22--12053' or
cd_test='Aw22--12061' or
cd_test='Aw22--12062' or
cd_test='Aw22--12063' or
cd_test='Aw22--12071' or
cd_test='Aw22--13012' or
cd_test='Aw22--13021' or
cd_test='Aw22--13022' or
cd_test='Aw22--13023' or
cd_test='Aw22--13061' or
cd_test='Aw22--13062' or
cd_test='Aw22--13063' or
cd_test='Aw22--13071' or
cd_test='Aw22--13154' or
cd_test='Aw22--13164';


-- Post-data save --
COMMIT;