
drop procedure if exists drop_contract_table_fk;
delimiter |
CREATE PROCEDURE `drop_contract_table_fk`()
BEGIN
    
    IF EXISTS (SELECT NULL FROM information_schema.TABLE_CONSTRAINTS
        WHERE CONSTRAINT_SCHEMA = DATABASE() AND CONSTRAINT_NAME = 'FK_CONTRACT_USER') THEN
            ALTER TABLE `TGSI_CONTRACT` DROP FOREIGN KEY `FK_CONTRACT_USER`; 
    END IF;
    IF EXISTS (SELECT NULL FROM information_schema.TABLE_CONSTRAINTS
        WHERE CONSTRAINT_SCHEMA = DATABASE() AND CONSTRAINT_NAME = 'FK_TGSI_CONTRACT_TGSI_USER') THEN
            ALTER TABLE `TGSI_CONTRACT` DROP FOREIGN KEY `FK_TGSI_CONTRACT_TGSI_USER`; 
    END IF;
END |

delimiter ;

call drop_contract_table_fk();
drop procedure drop_contract_table_fk;

ALTER TABLE `TGSI_CONTRACT` 
	ADD CONSTRAINT `FK_TGSI_CONTRACT_TGSI_USER`
    FOREIGN KEY (`USER_Id_User` )
    REFERENCES `TGSI_USER` (`Id_User` )
    ON DELETE CASCADE
    ON UPDATE CASCADE;


ALTER TABLE `TGSI_CONTRACT_REFERENTIAL` DROP FOREIGN KEY `FK_TGSI_CONTRACT_REFERENTIAL_TGSI_CONTRACT`;
ALTER TABLE `TGSI_CONTRACT_REFERENTIAL` 
	ADD CONSTRAINT `FK_TGSI_CONTRACT_REFERENTIAL_TGSI_CONTRACT`
	FOREIGN KEY (`CONTRACT_Id_Contract` )
	REFERENCES `TGSI_CONTRACT` (`Id_Contract` )
	ON DELETE CASCADE
	ON UPDATE CASCADE;


ALTER TABLE `TGSI_CONTRACT_FUNCTIONALITY` DROP FOREIGN KEY `FK_TGSI_CONTRACT_FUNCTIONALITY_TGSI_CONTRACT`;
ALTER TABLE `TGSI_CONTRACT_FUNCTIONALITY` 
	ADD CONSTRAINT `FK_TGSI_CONTRACT_FUNCTIONALITY_TGSI_CONTRACT`
	FOREIGN KEY (`CONTRACT_Id_Contract` )
	REFERENCES `TGSI_CONTRACT` (`Id_Contract` )
	ON DELETE CASCADE
	ON UPDATE CASCADE;


ALTER TABLE `TGSI_CONTRACT_OPTION_ELEMENT` DROP FOREIGN KEY `FK_TGSI_CONTRACT_OPTION_ELEMENT_TGSI_CONTRACT`;
ALTER TABLE `TGSI_CONTRACT_OPTION_ELEMENT` 
	ADD CONSTRAINT `FK_TGSI_CONTRACT_OPTION_ELEMENT_TGSI_CONTRACT`
	FOREIGN KEY (`CONTRACT_Id_Contract` )
	REFERENCES `TGSI_CONTRACT` (`Id_Contract` )
	ON DELETE CASCADE
	ON UPDATE CASCADE;

drop procedure if exists drop_act_table_fk;
delimiter |
CREATE PROCEDURE `drop_act_table_fk`()
BEGIN
    
    IF EXISTS (SELECT NULL FROM information_schema.TABLE_CONSTRAINTS
        WHERE CONSTRAINT_SCHEMA = DATABASE() AND CONSTRAINT_NAME = 'fk_ACT_CONTRACT') THEN
            ALTER TABLE `TGSI_ACT` DROP FOREIGN KEY `fk_ACT_CONTRACT`; 
    END IF;
    IF EXISTS (SELECT NULL FROM information_schema.TABLE_CONSTRAINTS
        WHERE CONSTRAINT_SCHEMA = DATABASE() AND CONSTRAINT_NAME = 'FK_TGSI_ACT_TGSI_CONTRACT') THEN
            ALTER TABLE `TGSI_ACT` DROP FOREIGN KEY `FK_TGSI_ACT_TGSI_CONTRACT`; 
    END IF;
END |

delimiter ;

call drop_act_table_fk();
drop procedure drop_act_table_fk;

ALTER TABLE `TGSI_ACT` 
	ADD CONSTRAINT `FK_TGSI_ACT_TGSI_CONTRACT`
	FOREIGN KEY (`CONTRACT_Id_Contract` )
	REFERENCES `TGSI_CONTRACT` (`Id_Contract` )
	ON DELETE CASCADE
	ON UPDATE CASCADE;

-- -----------------------------------------------------
-- Table `TGSI_USER_OPTION_ELEMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TGSI_USER_OPTION_ELEMENT` (
  `OPTION_ELEMENT_Id_Option_Element` bigint(20) NOT NULL ,
  `USER_Id_User` bigint(20) NOT NULL ,
  UNIQUE INDEX `INDEX_UNIQUE_PAIR` (`OPTION_ELEMENT_Id_Option_Element`, `USER_Id_User`),
  CONSTRAINT `FK_TGSI_USER_OPTION_ELEMENT_TGSI_USER`
    FOREIGN KEY (`USER_Id_User` )
    REFERENCES `TGSI_USER` (`Id_User` )
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_TGSI_USER_OPTION_ELEMENT_TGSI_OPTION_ELEMENT`
    FOREIGN KEY (`OPTION_ELEMENT_Id_Option_Element` )
    REFERENCES `TGSI_OPTION_ELEMENT` (`Id_Option_Element` )
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

ALTER TABLE `TGSI_USER` CHANGE `Name` `Name` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `TGSI_USER` CHANGE `First_Name` `First_Name` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';

