use tanaguru;
TRUNCATE TABLE `PROCESS_REMARK`;TRUNCATE TABLE `PROCESS_RESULT`;TRUNCATE TABLE `CONTENT`;TRUNCATE TABLE `WEB_RESOURCE`;TRUNCATE TABLE `AUDIT_TEST`;TRUNCATE TABLE `AUDIT`;TRUNCATE TABLE `CONTENT_RELATIONSHIP`;
