CREATE USER 'tanaguru'@'localhost' IDENTIFIED BY '********';

GRANT USAGE ON * . * TO 'tanaguru'@'localhost' IDENTIFIED BY '********' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

CREATE DATABASE IF NOT EXISTS `tanaguru` CHARACTER SET utf8;

GRANT ALL PRIVILEGES ON `tanaguru` . * TO 'tanaguru'@'localhost';

FLUSH PRIVILEGES;
