#!/bin/bash -e

APP_VERSION="${APP_VERSION?APP_VERSION must be set}"
WEBAPP_ARTIFACT_DIR="${WEBAPP_ARTIFACT_DIR?WEBAPP_ARTIFACT_DIR must be set}"
WEBAPP_ARTIFACT_FILE="${WEBAPP_ARTIFACT_FILE?WEBAPP_ARTIFACT_FILE must be set}"
REST_SERVER_ARTIFACT_DIR="${REST_SERVER_ARTIFACT_DIR?REST_SERVER_ARTIFACT_DIR must be set}"
REST_SERVER_ARTIFACT_FILE="${REST_SERVER_ARTIFACT_FILE?REST_SERVER_ARTIFACT_FILE must be set}"
ARCHIVE_NAME="asqatasun-${APP_VERSION}.tar.bz2"

# Create archive
tar cvfj \
    "${ARCHIVE_NAME}" \
    "${WEBAPP_ARTIFACT_DIR}/${WEBAPP_ARTIFACT_FILE}" \
    "${REST_SERVER_ARTIFACT_DIR}/${REST_SERVER_ARTIFACT_FILE}"

# Copy archive + artefacts
scp \
    "${ARCHIVE_NAME}" \
    "${WEBAPP_ARTIFACT_DIR}/${WEBAPP_ARTIFACT_FILE}" \
    "${REST_SERVER_ARTIFACT_DIR}/${REST_SERVER_ARTIFACT_FILE}" \
    "${ARCHIVE_ARTEFACT_DEPLOY_USER}@${ARCHIVE_ARTEFACT_DEPLOY_HOST}:${ARCHIVE_ARTEFACT_DEPLOY_PATH}"
