#!/bin/bash -e

APP_VERSION="${APP_VERSION?APP_VERSION must be set}"

WEBAPP_ARTIFACT_DIR="${WEBAPP_ARTIFACT_DIR?WEBAPP_ARTIFACT_DIR must be set}"
WEBAPP_ARTIFACT_FILE="${WEBAPP_ARTIFACT_FILE?WEBAPP_ARTIFACT_FILE must be set}"
WEBAPP_ARTIFACT_FILE_FINAL="Asqatasun-${APP_VERSION}.war"

REST_SERVER_ARTIFACT_DIR="${REST_SERVER_ARTIFACT_DIR?REST_SERVER_ARTIFACT_DIR must be set}"
REST_SERVER_ARTIFACT_FILE="${REST_SERVER_ARTIFACT_FILE?REST_SERVER_ARTIFACT_FILE must be set}"
REST_SERVER_ARTIFACT_FILE_FINAL="Asqatasun-REST-API-Server-${APP_VERSION}.jar"

#ARCHIVE_NAME="asqatasun-${APP_VERSION}.tar.bz2"
DEST_PATH="${ARTEFACT_DEPLOY_PATH}/Asqatasun-${APP_VERSION}"

# Create archive
#tar cvfj \
#    "${ARCHIVE_NAME}" \
#    "${WEBAPP_ARTIFACT_DIR}/${WEBAPP_ARTIFACT_FILE}" \
#    "${REST_SERVER_ARTIFACT_DIR}/${REST_SERVER_ARTIFACT_FILE}"

# Create directory
ssh "${ARTEFACT_DEPLOY_USER}@${ARTEFACT_DEPLOY_HOST}" \
    mkdir -p "${DEST_PATH}"

# Copy artefacts: webapp
scp \
    "${WEBAPP_ARTIFACT_DIR}/${WEBAPP_ARTIFACT_FILE}" \
    "${ARTEFACT_DEPLOY_USER}@${ARTEFACT_DEPLOY_HOST}:${DEST_PATH}/${WEBAPP_ARTIFACT_FILE_FINAL}"

# Copy artefacts: API server
scp \
    "${REST_SERVER_ARTIFACT_DIR}/${REST_SERVER_ARTIFACT_FILE}" \
    "${ARTEFACT_DEPLOY_USER}@${ARTEFACT_DEPLOY_HOST}:${DEST_PATH}/${REST_SERVER_ARTIFACT_FILE_FINAL}"
