Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.vm.hostname = "asqatasun" 
  config.vm.network "private_network", ip: "192.168.33.33"
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  config.vm.define "asqatasun" do |asqatasun|
  end
 
  config.vm.provider "virtualbox" do |vb|
   vb.gui = false
   vb.name = "asqatasun"
   vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
   vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
   vb.memory = 2048
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "setup.yml"
    ansible.host_key_checking = false
  end

end
