jdbc:
  url: "jdbc:mysql://localhost:3306/asqatasun"
  url_query_options: "?useSSL=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8"
  user: "asqatasunDatabaseUserLogin"
  password: "asqatasunDatabaseUserP4ssword"

jpa:
  showSql: false

hibernate:
  cache:
    use_second_level_cache: true
    use_query_cache: true
    ehcache:
      missing_cache_strategy:spring: create

webdriver:
  firefox:
    bin: "/opt/firefox/firefox"

spring:
  profiles:
    active: "webapp"

server:
  error:
    whitelabel:
      enabled: false

app:
  logging:
    path: "tmp"
  version: "@project.version@"
  emailSender:
    smtp:
      debug: false
      from: "asqatasun@example.com"
      host: "localhost"
      port: -1
      user: ""
      password: ""
      starttls:
        enable: false
      ssl:
        enable: false        # If true then "starttls.enable" property is not taken into account
        protocols: "TLSv1.2" # a whitespace separated list of protocols acceptable
  engine:
    persistence:
      packagesToScan: "org.asqatasun.entity,org.asqatasun.webapp.entity"
      useComboPool: true
    loader:
      politenessDelay: 100
      proxy:
        port:
        host:
  webapp:
    security:
      owasp:
        esapiPropertyValue: "/etc/asqatasun"
        tokenDurationValidity: 3600
    ui:
      config:
        authorizedPageSize: "10,25,50,100,250,1000,-1"
        authorizedRefForCriterionViewList: "Aw22,Rgaa30,Rgaa40"
        authorizedScopeForCriterionList: "DOMAIN,SCENARIO"
        authorizedScopeForPageList: "DOMAIN,SCENARIO"
        authorizedScopeForSynthesis: "DOMAIN,SCENARIO"
        authorizedScopeForTrend: "DOMAIN,SCENARIO"
        defaultReferential: "Rgaa40"
        forbiddenUserListForSettings: "guest"
        nbOfFailedPages: 10
        nbOfFailedTest: 5
        referentialWithModifiableTestWeight: "SEO,Aw22"
        userExclusionListForEmail: "guest"
        webAppUrl: "http://localhost:8080/"
        contrastfinderServiceUrl: "https://app.contrast-finder.org"
        forgottenPassword:
          excludeUserList: "guest"
        orchestrator:
          ayncDelay: 30000
          emailSentToUserExclusionList: "guest"
          krashReportMailList: "support@asqatasun.org"
          enableKrashReport: true
