START TRANSACTION;
SET standard_conforming_strings=off;
SET escape_string_warning=off;
SET CONSTRAINTS ALL DEFERRED;


INSERT INTO "reference" VALUES 
(1,'AW21',NULL,'Accessiweb 2.1',1,'http://www.braillenet.org/accessibilite/referentiel-aw21/',2);


INSERT INTO "theme" VALUES 
(1,'AW21-1',NULL,'Images',1),
(2,'AW21-2',NULL,'Cadres',2),
(3,'AW21-3',NULL,'Couleurs',3),
(4,'AW21-4',NULL,'Multimédia',4),
(5,'AW21-5',NULL,'Tableaux',5),
(6,'AW21-6',NULL,'Liens',6),
(7,'AW21-7',NULL,'Script',7),
(8,'AW21-8',NULL,'Éléments Obligatoires',8),
(9,'AW21-9',NULL,'Structuration de l''information',9),
(10,'AW21-10',NULL,'Présentation de l''information',10),
(11,'AW21-11',NULL,'Formulaires',11),
(12,'AW21-12',NULL,'Navigation',12),
(13,'AW21-13',NULL,'Consultation',13);


INSERT INTO "criterion" VALUES 
(1,'AW21-0101','Chaque image a-t-elle une alternative textuelle ?','1.1',1,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-1-1 ',1,1),
(2,'AW21-0102','Pour chaque image de décoration ayant une alternative textuelle,  cette alternative est-elle vide ?','1.2',2,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-1-2',1,1),
(3,'AW21-0103','Pour chaque image porteuse d''information ayant une alternative textuelle,  cette alternative est-elle pertinente (hors cas particuliers) ?','1.3',3,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-1-3 ',1,1),
(4,'AW21-0104','Pour chaque image utilisée comme CAPTCHA ou comme image-test,  ayant une alternative textuelle,  cette alternative permet-elle d''identifier la nature et la fonction de l''image ?','1.4',4,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-1-4 ',1,1),
(5,'AW21-0105','Pour chaque image utilisée comme CAPTCHA,  une solution d''accès alternatif au contenu ou à la fonction du CAPTCHA est-elle présente ?','1.5',5,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-1-5 ',1,1),
(6,'AW21-0106','Chaque image porteuse d''information a-t-elle,  si nécessaire,  une description détaillée ?','1.6',6,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-1-6 ',1,1),
(7,'AW21-0107','Pour chaque image porteuse d''information ayant une description détaillée,  cette description est-elle pertinente ?','1.7',7,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-1-7 ',1,1),
(8,'AW21-0108','Chaque image texte,  en l''absence d''un mécanisme de remplacement,  doit si possible être remplacée par du texte stylé. Cette règle est-elle respectée (hors cas particuliers) ?','1.8',8,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-1-8 ',1,1),
(9,'AW21-0109','Chaque image texte doit si possible être remplacée par du texte stylé. Cette règle est-elle respectée ?','1.9',9,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-1-9 ',1,1),
(10,'AW21-0201','Chaque cadre et chaque cadre en ligne a-t-il un titre de cadre ?','2.1',10,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-2-1 ',1,2),
(11,'AW21-0202','Pour chaque cadre et chaque cadre en ligne ayant un titre de cadre,  ce titre de cadre est-il pertinent ?','2.2',11,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-2-2 ',1,2),
(12,'AW21-0301','Dans chaque page web,  l'' information ne doit pas être donnée uniquement par la couleur. Cette règle est-elle respectée ?','3.1',12,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-3-1 ',1,3),
(13,'AW21-0302','Dans chaque page web,  l'' information ne doit pas être donnée uniquement par la couleur. Cette règle est-elle implémentée de façon pertinente ?','3.2',13,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-3-2 ',1,3),
(14,'AW21-0303','Dans chaque page web,  le contraste entre la couleur du texte et la couleur de son arrière-plan est-il suffisamment élevé (hors cas particuliers) ?','3.3',14,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-3-3 ',1,3),
(15,'AW21-0304','Dans chaque page web,  le contraste entre la couleur du texte et la couleur de son arrière-plan est-il amélioré (hors cas particuliers) ?','3.4',15,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-3-4 ',1,3),
(16,'AW21-0401','Chaque média temporel pré-enregistré a-t-il,  si nécessaire,  une transcription textuelle ou une audio-description (hors cas particuliers) ?','4.1',16,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-1 ',1,4),
(17,'AW21-0402','Pour chaque média temporel pré-enregistré ayant une transcription textuelle ou une audio-description synchronisée,  celles-ci sont-elles pertinentes (hors cas particuliers) ?','4.2',19,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-2 ',1,4),
(18,'AW21-0403','Chaque média temporel synchronisé pré-enregistré a-t-il,  si nécessaire,  des sous-titres synchronisés (hors cas particuliers) ?','4.3',18,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-3 ',1,4),
(19,'AW21-0404','Pour chaque média temporel synchronisé pré-enregistré ayant des sous-titres synchronisés,  ces sous-titres sont-ils pertinents ?','4.4',19,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-4 ',1,4),
(20,'AW21-0405','Chaque média temporel en direct a-t-il,  si nécessaire,  des sous-titres synchronisés ou une transcription textuelle (hors cas particuliers) ?','4.5',20,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-5 ',1,4),
(21,'AW21-0406','Pour chaque média temporel en direct ayant des sous-titres synchronisés ou une transcription textuelle,  ceux-ci sont-ils pertinents ?','4.6',21,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-6 ',1,4),
(22,'AW21-0407','Chaque média temporel synchronisé pré-enregistré a-t-il,  si nécessaire,  une audio-description synchronisée ?','4.7',22,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-7 ',1,4),
(23,'AW21-0408','Pour chaque média temporel pré-enregistré ayant une audio-description synchronisée,  celle-ci est-elle pertinente ?','4.8',23,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-8 ',1,4),
(24,'AW21-0409','Chaque média temporel pré-enregistré a-t-il,  si nécessaire,  une interprétation en langue des signes (hors cas particuliers) ?','4.9',24,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-9 ',1,4),
(25,'AW21-0410','Pour chaque média temporel pré-enregistré ayant une interprétation en langue des signes,  celle-ci est-elle pertinente ?','4.10',25,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-10 ',1,4),
(26,'AW21-0411','Chaque média temporel pré-enregistré a-t-il,  si nécessaire,  une audio-description étendue synchronisée (hors cas particuliers) ?','4.11',26,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-11 ',1,4),
(27,'AW21-0412','Pour chaque média temporel pré-enregistré ayant une audio-description étendue synchronisée,  celle-ci est-elle pertinente ?','4.12',27,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-12 ',1,4),
(28,'AW21-0413','Chaque média temporel synchronisé ou seulement vidéo a-t-il,  si nécessaire,  une transcription textuelle (hors cas particuliers ) ?','4.13',28,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-13 ',1,4),
(29,'AW21-0414','Pour chaque média temporel synchronisé ou seulement vidéo,  ayant une transcription textuelle,  celle-ci est-elle pertinente ?','4.14',29,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-14 ',1,4),
(30,'AW21-0415','Chaque média temporel est-il clairement identifiable (hors cas particuliers) ?','4.15',30,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-15 ',1,4),
(31,'AW21-0416','Chaque média non temporel a-t-il,  si nécessaire,  une alternative (hors cas particuliers) ?','4.16',31,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-16 ',1,4),
(32,'AW21-0417','Pour chaque média non temporel ayant une alternative,  cette alternative est-elle pertinente ?','4.17',32,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-17 ',1,4),
(33,'AW21-0418','Chaque son déclenché automatiquement est-il contrôlable par l''utilisateur ?','4.18',33,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-18 ',1,4),
(34,'AW21-0419','Pour chaque média temporel seulement audio pré-enregistré,  les dialogues sont-ils suffisamment audibles ?','4.19',34,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-19 ',1,4),
(35,'AW21-0420','La consultation de chaque média temporel est-elle contrôlable par le clavier et la souris ?','4.20',35,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-20 ',1,4),
(36,'AW21-0421','La consultation de chaque média non temporel est-elle contrôlable par le clavier et la souris ?','4.21',36,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-21 ',1,4),
(37,'AW21-0422','Chaque média temporel et non temporel est-il compatible avec les technologies d''assistance ?','4.22',37,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-4-22 ',1,4),
(38,'AW21-0501','Chaque tableau de données a-t-il un résumé ?','5.1',38,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-5-1 ',1,5),
(39,'AW21-0502','Pour chaque tableau ayant un résumé,  celui-ci est-il pertinent ?','5.2',39,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-5-2 ',1,5),
(40,'AW21-0503','Pour chaque tableau de mise en forme,  le contenu linéarisé reste-t-il compréhensible ?','5.3',40,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-5-3 ',1,5),
(41,'AW21-0504','Chaque tableau de données a-t-il un titre ?','5.4',41,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-5-4 ',1,5),
(42,'AW21-0505','Pour chaque tableau de données ayant un titre,  celui-ci est-il pertinent ?','5.5',42,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-5-5 ',1,5),
(43,'AW21-0506','Pour chaque tableau de données,  chaque en-tête de colonnes et chaque en-tête de lignes sont-ils correctement déclarés ?','5.6',43,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-5-6 ',1,5),
(44,'AW21-0507','Pour chaque tableau de données,  la technique appropriée permettant d''associer chaque cellule avec ses en-têtes est-elle utilisée ?','5.7',44,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-5-7 ',1,5),
(45,'AW21-0508','Chaque tableau de mise en forme ne doit pas utiliser d''éléments propres aux tableaux de données. Cette règle est-elle respectée ?','5.8',45,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-5-8 ',1,5),
(46,'AW21-0601','Chaque lien est-il explicite (hors cas particuliers ) ?','6.1',46,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-6-1 ',1,6),
(47,'AW21-0602','Pour chaque lien ayant un titre de lien,  celui-ci est-il pertinent ?','6.2',47,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-6-2 ',1,6),
(48,'AW21-0603','Chaque intitulé de lien seul est-il explicite hors contexte (hors cas particuliers) ?','6.3',48,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-6-3 ',1,6),
(49,'AW21-0604','Chaque lien identique a-t-il les mêmes fonction et destination ?','6.4',49,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-6-4 ',1,6),
(50,'AW21-0605','Chaque zone cliquable d''une image réactive côté serveur est-elle doublée d''un lien dans la page ?','6.5',50,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-6-5 ',1,6),
(51,'AW21-0606','Dans chaque page web,  chaque lien,  à l''exception des ancres nommées,  a-t-il un intitulé ?','6.6',51,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-6-6 ',1,6),
(52,'AW21-0701','Chaque script a-t-il,  si nécessaire,  une alternative (hors cas particuliers) ?','7.1',52,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-7-1 ',1,7),
(53,'AW21-0702','Pour chaque script ayant une alternative,  cette alternative est-elle pertinente ?','7.2',53,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-7-2 ',1,7),
(54,'AW21-0703','Chaque script est-il contrôlable par le clavier et la souris (hors cas particuliers) ?','7.3',54,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-7-3 ',1,7),
(55,'AW21-0704','Chaque script est-il,  si nécessaire,  compatible avec les technologies d''assistance ?','7.4',55,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-7-4 ',1,7),
(56,'AW21-0705','Pour chaque script qui initie un changement de contexte,  l''utilisateur est-il averti ou en a-t-il le contrôle ?','7.5',56,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-7-5 ',1,7),
(57,'AW21-0706','Chaque script qui provoque une alerte non sollicitée est-il contrôlable par l''utilisateur (hors cas particuliers ) ?','7.6',57,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-7-6 ',1,7),
(58,'AW21-0801','Chaque page web est-elle définie par un type de document ?','8.1',58,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-8-1 ',1,8),
(59,'AW21-0802','Pour chaque page web,  le code source est-il valide selon le type de document spécifié ?','8.2',59,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-8-2 ',1,8),
(60,'AW21-0803','Dans chaque page web,  la langue par défaut est-elle présente ?','8.3',60,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-8-3 ',1,8),
(61,'AW21-0804','Pour chaque page web ayant une langue par défaut,  le code de langue est-il pertinent ?','8.4',61,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-8-4 ',1,8),
(62,'AW21-0805','Chaque page web a-t-elle un titre de page ?','8.5',62,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-8-5 ',1,8),
(63,'AW21-0806','Pour chaque page web ayant un titre de page,  ce titre est-il pertinent ?','8.6',63,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-8-6 ',1,8),
(64,'AW21-0807','Dans chaque page web,  chaque changement de langue est-il indiqué dans le code source (hors cas particuliers) ?','8.7',64,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-8-7 ',1,8),
(65,'AW21-0808','Dans chaque page web,  chaque changement de langue est-il pertinent ?','8.8',65,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-8-8 ',1,8),
(66,'AW21-0809','Dans chaque page web,  les balises ne doivent pas être utilisées uniquement à des fins de présentation. Cette règle est-elle respectée ?','8.9',66,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-8-9 ',1,8),
(67,'AW21-0810','Dans chaque page web,  les changements du sens de lecture sont-ils signalés ?','8.10',67,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-8-10 ',1,8),
(68,'AW21-0901','Dans chaque page web,  l''information est-elle structurée par l''utilisation appropriée de titres ?','9.1',68,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-9-1 ',1,9),
(69,'AW21-0902','Dans chaque page web,  chaque liste est-elle structurée avec les balises appropriées ?','9.2',69,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-9-2 ',1,9),
(70,'AW21-0903','Dans chaque page web,  la première occurrence de chaque abréviation permet-elle d''en connaître la signification ?','9.3',70,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-9-3 ',1,9),
(71,'AW21-0904','Dans chaque page web,  la signification de chaque abréviation est-elle pertinente ?','9.4',71,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-9-4 ',1,9),
(72,'AW21-0905','Dans chaque page web,  chaque citation est-elle correctement indiquée ?','9.5',72,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-9-5 ',1,9),
(73,'AW21-1001','Dans le site web,  des feuilles de styles sont-elles utilisées pour contrôler la présentation de l''information ?','10.1',73,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-10-1 ',1,10),
(74,'AW21-1002','Dans chaque page web,  le contenu visible reste-t-il présent lorsque les feuilles de styles ou les images sont désactivées ?','10.2',74,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-10-2 ',1,10),
(75,'AW21-1003','Dans chaque page web,  l''information reste-t-elle compréhensible lorsque les feuilles de styles sont désactivées ?','10.3',75,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-10-3 ',1,10),
(76,'AW21-1004','Dans chaque page web,  le texte reste-t-il lisible lorsque la taille des caractères est augmentée jusqu''à 200%,  au moins ?','10.4',76,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-10-4 ',1,10),
(77,'AW21-1005','Dans chaque page web,  les déclarations CSS de couleurs de fond d''élément et de police sont-elles correctement utilisées?','10.5',77,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-10-5 ',1,10),
(78,'AW21-1006','Dans chaque page web,  chaque lien dont la nature n''est pas évidente est-il visible par rapport au texte environnant ?','10.6',78,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-10-6 ',1,10),
(79,'AW21-1007','Dans chaque page web,  pour chaque élément recevant le focus,  la prise de focus est-elle visible ?','10.7',79,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-10-7 ',1,10),
(80,'AW21-1008','Dans chaque page web,  le choix de la couleur de fond et de police du texte est-elle contrôlable par l''utilisateur ?','10.8',80,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-10-8 ',1,10),
(81,'AW21-1009','Pour chaque page web,  le texte ne doit pas être justifié. Cette règle est-elle respectée ?','10.9',81,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-10-9 ',1,10),
(82,'AW21-1010','Pour chaque page web,  en affichage plein écran et avec une taille de police à 200%,  chaque bloc de texte reste-t-il lisible sans l''utilisation de la barre de défilement horizontal ?','10.10',82,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-10-10 ',1,10),
(83,'AW21-1011','Pour chaque page web,  les blocs de texte ont-ils une largeur inférieure ou égale à 80 caractères (hors cas particuliers) ?','10.11',83,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-10-11 ',1,10),
(84,'AW21-1012','Pour chaque page web,  l''espace entre les lignes et les paragraphes est-il suffisant ?','10.12',84,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-10-12 ',1,10),
(85,'AW21-1013','Pour chaque page web,  les textes cachés sont-t-ils correctement restitués par les technologies d''assistance ?','10.13',85,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-10-13 ',1,10),
(86,'AW21-1014','Dans chaque page web,  l''information ne doit pas être donnée uniquement par la forme ou la position. Cette règle est-elle respectée ?','10.14',86,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-10-14 ',1,10),
(87,'AW21-1015','Dans chaque page web,  l''information ne doit pas être donnée par la forme ou la position uniquement. Cette règle est-elle implémentée de façon pertinente ?','10.15',87,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-10-15 ',1,10),
(88,'AW21-1101','Chaque champ de formulaire a-t-il une étiquette ?','11.1',88,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-11-1 ',1,11),
(89,'AW21-1102','Chaque étiquette associée à un champ de formulaire est-elle pertinente ?','11.2',89,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-11-2 ',1,11),
(90,'AW21-1103','Dans chaque formulaire,  chaque étiquette associée à un champ de formulaire ayant la même fonction et répétés plusieurs fois dans une même page ou dans un ensemble de page est-elle cohérente ?','11.3',90,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-11-3 ',1,11),
(91,'AW21-1104','Dans chaque formulaire,  chaque étiquette de champ et son champ associé sont-ils accolés ?','11.4',91,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-11-4 ',1,11),
(92,'AW21-1105','Dans chaque formulaire,  les informations de même nature sont-elles regroupées,  si nécessaire ?','11.5',92,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-11-5 ',1,11),
(93,'AW21-1106','Dans chaque formulaire,  chaque regroupement de champs de formulaire a-t-il une légende ?','11.6',93,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-11-6 ',1,11),
(94,'AW21-1107','Dans chaque formulaire,  chaque légende associée à un groupement de champs de formulaire est-elle pertinente ?','11.7',94,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-11-7 ',1,11),
(95,'AW21-1108','Dans chaque formulaire,  chaque liste de choix est-elle structurée de manière pertinente ?','11.8',95,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-11-8 ',1,11),
(96,'AW21-1109','Dans chaque formulaire,  l''intitulé de chaque bouton est-il pertinent ?','11.9',96,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-11-9 ',1,11),
(97,'AW21-1110','Dans chaque formulaire,  le contrôle de saisie est-il utilisé de manière pertinente ?','11.10',97,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-11-10 ',1,11),
(98,'AW21-1111','Dans chaque formulaire,  le contrôle de saisie est-il accompagné,  si possible,  de suggestions facilitant la correction des erreurs de saisie ?','11.11',98,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-11-11 ',1,11),
(99,'AW21-1112','Pour chaque formulaire,  les données à caractère financier,  juridique ou personnel peuvent-elles être modifiées,  mise à jour ou récupérées par l''utilisateur ?','11.12',99,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-11-12 ',1,11),
(100,'AW21-1113','Pour chaque formulaire,  toutes les données peuvent-elles être modifiées,  mises à jour ou récupérées par l''utilisateur ?','11.13',100,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-11-13 ',1,11),
(101,'AW21-1114','Pour chaque formulaire,  des aides à la saisie sont-elles présentes ?','11.14',101,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-11-14 ',1,11),
(102,'AW21-1115','Pour chaque formulaire,  chaque aide à la saisie est-elle pertinente ?','11.15',102,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-11-15 ',1,11),
(103,'AW21-1201','Chaque ensemble de pages dispose-t-il de deux systèmes de navigation différents,  au moins (hors cas particuliers) ?','12.1',103,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-12-1 ',1,12),
(104,'AW21-1202','Dans chaque ensemble de pages,  le menu ou les barres de navigation sont-ils toujours à la même place (hors cas particuliers) ?','12.2',104,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-12-2 ',1,12),
(105,'AW21-1203','Dans chaque ensemble de pages,  le menu et les barres de navigation ont-ils une présentation cohérente (hors cas particuliers) ?','12.3',105,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-12-3 ',1,12),
(106,'AW21-1204','La page \"plan du site\" est-elle pertinente ?','12.4',106,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-12-4 ',1,12),
(107,'AW21-1205','Dans chaque ensemble de pages,  la page \"plan du site\" est-elle atteignable de manière identique ?','12.5',107,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-12-5 ',1,12),
(108,'AW21-1206','Dans chaque ensemble de pages,  le moteur de recherche est-il atteignable de manière identique ?','12.6',108,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-12-6 ',1,12),
(109,'AW21-1207','Dans chaque page d''une collection de pages,  des liens facilitant la navigation sont-ils présents ?','12.7',109,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-12-7 ',1,12),
(110,'AW21-1208','Dans chaque page web,  un fil d''Ariane est-il présent ?','12.8',110,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-12-8 ',1,12),
(111,'AW21-1209','Dans chaque page web,  le fil d''Ariane est-il pertinent ?','12.9',111,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-12-9 ',1,12),
(112,'AW21-1210','Dans chaque page web,  les groupes de liens importants (menu,  barre de navigation...) et la zone de contenu sont-ils identifiés ?','12.10',112,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-12-10 ',1,12),
(113,'AW21-1211','Dans chaque page web,  des liens d''évitements ou d''accès rapide aux groupes de liens importants et à la zone de contenu sont-ils présents ?','12.11',113,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-12-11 ',1,12),
(114,'AW21-1212','Dans chaque page web,  la page en cours de consultation est-elle indiquée dans le menu de navigation ?','12.12',114,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-12-12 ',1,12),
(115,'AW21-1213','Dans chaque page web,  l''ordre de tabulation est-il cohérent ?','12.13',115,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-12-13 ',1,12),
(116,'AW21-1214','Dans chaque page web,  la navigation ne doit pas contenir de piège au clavier. Cette règle est-elle respectée ?','12.14',116,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-12-14 ',1,12),
(117,'AW21-1301','Pour chaque page web,  l''utilisateur a-t-il le contrôle de chaque limite de temps modifiant le contenu (hors cas particuliers) ?','13.1',119,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-13-1 ',1,13),
(118,'AW21-1302','Dans chaque page web,  pour chaque ouverture de nouvelle fenêtre,  l''utilisateur est-il averti ?','13.2',118,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-13-2 ',1,13),
(119,'AW21-1303','Dans chaque page web,  l''ouverture d''une nouvelle fenêtre ne doit pas être déclenchée sans action de l''utilisateur. Cette règle est-elle respectée ?','13.3',119,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-13-3 ',1,13),
(120,'AW21-1304','Dans chaque page web,  une tâche ne doit pas requérir de limite de temps pour être réalisée,  sauf si elle se déroule en temps réel ou si cette limite de temps est essentielle. Cette règle est-elle respectée ?','13.4',120,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-13-4 ',1,13),
(121,'AW21-1305','Dans chaque page web,  lors d''une interruption de session authentifiée,  les données saisies par l''utilisateur sont-elles récupérées après ré-authentification ?','13.5',121,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-13-5 ',1,13),
(122,'AW21-1306','Dans chaque page web,  pour chaque fichier en téléchargement,  des informations relatives à sa consultation sont-elles présentes ?','13.6',122,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-13-6 ',1,13),
(123,'AW21-1307','Dans chaque page web,  chaque document bureautique en téléchargement possède-t-il,  si nécessaire,  une version accessible (hors cas particuliers) ?','13.7',123,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-13-7 ',1,13),
(124,'AW21-1308','Pour chaque document bureautique ayant une version accessible,  cette version offre-t-elle la même information ?','13.8',124,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-13-8 ',1,13),
(125,'AW21-1309','Dans chaque page web,  les expressions inhabituelles,  les expressions idiomatiques ou le jargon sont-ils explicités ?','13.9',125,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-13-9 ',1,13),
(126,'AW21-1310','Dans chaque page web,  pour chaque expression inhabituelle ou limitée,  idiomatique ou de jargon ayant une définition,  cette définition est-elle pertinente ?','13.10',126,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-13-10 ',1,13),
(127,'AW21-1311','Dans chaque page web,  chaque contenu cryptique (art ascii,  émoticon,  syntaxe cryptique) a-t-il une alternative ?','13.11',127,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-13-11 ',1,13),
(128,'AW21-1312','Dans chaque page web,  pour chaque contenu cryptique (art ascii,  émoticon,  syntaxe cryptique) ayant une alternative,  cette alternative est-elle pertinente ?','13.12',128,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-13-12 ',1,13),
(129,'AW21-1313','Dans chaque page web,  pour chaque mot dont le sens ne peut être compris sans en connaître la prononciation,  celle-ci est-elle indiquée ?','13.13',129,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-13-13 ',1,13),
(130,'AW21-1314','Dans chaque page web,  chaque texte qui nécessite un niveau de lecture plus avancé que le premier cycle de l''enseignement secondaire a-t-il une version alternative ?','13.14',130,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-13-14 ',1,13),
(131,'AW21-1315','Dans chaque page web,  les changements brusques de luminosité ou les effets de flash sont-ils correctement utilisés ?','13.15',131,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-13-15 ',1,13),
(132,'AW21-1316','Dans chaque page web,  les changements brusques de luminosité ou les effets de flash ont-ils une fréquence inférieure ou égale à 3 par seconde ?','13.16',132,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-13-16 ',1,13),
(133,'AW21-1317','Dans chaque page web,  chaque contenu en mouvement ou clignotant est-il contrôlable par l''utilisateur ?','13.17',133,'http://www.braillenet.org/accessibilite/referentiel-aw21/index.php#crit-13-17 ',1,13);


INSERT INTO "test" VALUES 
(1,'Aw21-01011','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.1.1',2010101,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01011','http://www.tanaguru.org/en/content/aw21-rule-1-1-1',1,NULL,1,NULL,1,TRUE),
(2,'Aw21-01012','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.1.2',2010102,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01012','http://www.tanaguru.org/en/content/aw21-rule-1-1-2',1,NULL,1,NULL,1,TRUE),
(3,'Aw21-01013','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.1.3',2010103,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01013','http://www.tanaguru.org/en/content/aw21-rule-1-1-3',1,NULL,1,NULL,1,TRUE),
(4,'Aw21-01021','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.2.1',2010201,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01021','http://www.tanaguru.org/en/content/aw21-rule-1-2-1',2,NULL,1,NULL,1,TRUE),
(5,'Aw21-01031','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.3.1',2010301,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01031','http://www.tanaguru.org/en/content/aw21-rule-1-3-1',3,NULL,1,NULL,1,TRUE),
(6,'Aw21-02011','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#cadres','2.1.1',2020101,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule02011','http://www.tanaguru.org/en/content/aw21-rule-2-1-1',10,NULL,1,NULL,1,TRUE),
(7,'Aw21-02012','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#cadres','2.1.2',2020102,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule02012','http://www.tanaguru.org/en/content/aw21-rule-2-1-2',10,NULL,1,NULL,1,TRUE),
(8,'Aw21-06011','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.1.1',2060101,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06011','http://www.tanaguru.org/en/content/aw21-rule-6-1-1',46,NULL,1,NULL,1,TRUE),
(9,'Aw21-06012','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.1.2',2060102,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06012','http://www.tanaguru.org/en/content/aw21-rule-6-1-2',46,NULL,1,NULL,1,TRUE),
(10,'Aw21-06013','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.1.3',2060103,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06013','http://www.tanaguru.org/en/content/aw21-rule-6-1-3',46,NULL,1,NULL,1,TRUE),
(11,'Aw21-06021','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.2.1',2060201,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06021','http://www.tanaguru.org/en/content/aw21-rule-6-2-1',47,NULL,1,NULL,1,TRUE),
(12,'Aw21-06022','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.2.2',2060202,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06022','http://www.tanaguru.org/en/content/aw21-rule-6-2-2',47,NULL,1,NULL,1,TRUE),
(13,'Aw21-06023','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.2.3',2060203,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06023','http://www.tanaguru.org/en/content/aw21-rule-6-2-3',47,NULL,1,NULL,1,TRUE),
(14,'Aw21-06024','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.2.4',2060204,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06024','http://www.tanaguru.org/en/content/aw21-rule-6-2-4',47,NULL,1,NULL,1,TRUE),
(15,'Aw21-06031','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.3.1',2060301,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06031','http://www.tanaguru.org/en/content/aw21-rule-6-3-1',48,NULL,3,NULL,1,TRUE),
(16,'Aw21-06032','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.3.2',2060302,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06032','http://www.tanaguru.org/en/content/aw21-rule-6-3-2',48,NULL,3,NULL,1,TRUE),
(17,'Aw21-06033','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.3.3',2060303,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06033','http://www.tanaguru.org/en/content/aw21-rule-6-3-3',48,NULL,3,NULL,1,TRUE),
(18,'Aw21-06041','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.4.1',2060401,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06041','http://www.tanaguru.org/en/content/aw21-rule-6-4-1',49,NULL,1,NULL,1,TRUE),
(19,'Aw21-06042','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.4.2',2060403,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06042','http://www.tanaguru.org/en/content/aw21-rule-6-4-2',49,NULL,1,NULL,1,TRUE),
(20,'Aw21-06043','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.4.3',2060403,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06043','http://www.tanaguru.org/en/content/aw21-rule-6-4-3',49,NULL,1,NULL,1,TRUE),
(21,'Aw21-06061','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.6.1',2060601,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06061','http://www.tanaguru.org/en/content/aw21-rule-6-6-1',51,NULL,1,NULL,1,TRUE),
(22,'Aw21-08011','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','8.1.1',2080101,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule08011','http://www.tanaguru.org/en/content/aw21-rule-8-1-1',58,NULL,1,NULL,1,TRUE),
(23,'Aw21-08012','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','8.1.2',2080102,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule08012','http://www.tanaguru.org/en/content/aw21-rule-8-1-2',58,NULL,1,NULL,1,TRUE),
(24,'Aw21-08051','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#elements','8.5.1',2080501,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule08051','http://www.tanaguru.org/en/content/aw21-rule-8-5-1',62,NULL,1,NULL,1,TRUE),
(25,'Aw21-08061','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#elements','8.6.1',2080601,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule08061','http://www.tanaguru.org/en/content/aw21-rule-8-6-1',63,NULL,1,NULL,1,TRUE),
(26,'Aw21-09011','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#structure','9.1.1',2090101,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule09011','http://www.tanaguru.org/en/content/aw21-rule-9-1-1',68,NULL,1,NULL,1,TRUE),
(27,'Aw21-09012','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#structure','9.1.2',2090102,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule09012','http://www.tanaguru.org/en/content/aw21-rule-9-1-2',68,NULL,1,NULL,1,TRUE),
(28,'Aw21-09021','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#structure','9.2.1',2090201,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule09021','http://www.tanaguru.org/en/content/aw21-rule-9-2-1',69,NULL,1,NULL,1,TRUE),
(29,'Aw21-09022','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#structure','9.2.2',2090202,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule09022','http://www.tanaguru.org/en/content/aw21-rule-9-2-2',69,NULL,1,NULL,1,TRUE),
(30,'Aw21-10011','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.1.1',2100101,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10011','http://www.tanaguru.org/en/content/aw21-rule-10-1-1',73,NULL,1,NULL,1,TRUE),
(31,'Aw21-10012','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.1.2',2100102,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10012','http://www.tanaguru.org/en/content/aw21-rule-10-1-2',73,NULL,1,NULL,1,TRUE),
(32,'Aw21-10041','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.4.1',2100401,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10041','http://www.tanaguru.org/en/content/aw21-rule-10-4-1',76,NULL,2,NULL,1,TRUE),
(33,'Aw21-11011','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.1.1',2110101,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11011','http://www.tanaguru.org/en/content/aw21-rule-11-1-1',88,NULL,1,NULL,1,TRUE),
(34,'Aw21-11012','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.1.2',2110102,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11012','http://www.tanaguru.org/en/content/aw21-rule-11-1-2',88,NULL,1,NULL,1,TRUE),
(35,'Aw21-11061','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.6.1',2110601,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11061','http://www.tanaguru.org/en/content/aw21-rule-11-6-1',93,NULL,1,NULL,1,TRUE),
(36,'Aw21-11082','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.8.2',2110802,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11082','http://www.tanaguru.org/en/content/aw21-rule-11-8-2',95,NULL,1,NULL,1,TRUE),
(37,'Aw21-07051','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#script','7.5.1',2070501,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule07051','http://www.tanaguru.org/en/content/aw21-rule-7-5-1',56,NULL,1,NULL,1,TRUE),
(38,'Aw21-08031','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','8.3.1',2080301,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule08031','http://www.tanaguru.org/en/content/aw21-rule-8-3-1',60,NULL,1,NULL,1,TRUE),
(39,'Aw21-08041','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','8.4.1',2080401,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule08041','http://www.tanaguru.org/en/content/aw21-rule-8-4-1',61,NULL,1,NULL,1,TRUE),
(40,'Aw21-05011','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#tableaux','5.1.1',2050101,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule05011','http://www.tanaguru.org/en/content/aw21-rule-5-1-1',38,NULL,1,NULL,1,TRUE),
(41,'Aw21-05041','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#tableaux','5.4.1',2050401,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule05041','http://www.tanaguru.org/en/content/aw21-rule-5-4-1',41,NULL,1,NULL,1,TRUE),
(42,'Aw21-11013','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.1.3',2110103,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11013','http://www.tanaguru.org/en/content/aw21-rule-11-1-3',88,NULL,1,NULL,1,TRUE),
(43,'Aw21-01014','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.1.4',2010104,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01014','http://www.tanaguru.org/en/content/aw21-rule-1-1-4',1,NULL,1,NULL,1,TRUE),
(44,'Aw21-01022','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.2.2',2010202,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01022','http://www.tanaguru.org/en/content/aw21-rule-1-2-2',2,NULL,1,NULL,1,TRUE),
(45,'Aw21-01023','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.2.3',2010203,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01023','http://www.tanaguru.org/en/content/aw21-rule-1-2-3',2,NULL,1,NULL,1,TRUE),
(46,'Aw21-01024','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.2.4',2010204,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01024','http://www.tanaguru.org/en/content/aw21-rule-1-2-4',2,NULL,1,NULL,1,TRUE),
(47,'Aw21-01025','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.2.5',2010205,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01025','http://www.tanaguru.org/en/content/aw21-rule-1-2-5',2,NULL,1,NULL,1,TRUE),
(48,'Aw21-01032','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.3.2',2010302,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01032','http://www.tanaguru.org/en/content/aw21-rule-1-3-2',3,NULL,1,NULL,1,TRUE),
(49,'Aw21-01033','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.3.3',2010303,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01033','http://www.tanaguru.org/en/content/aw21-rule-1-3-3',3,NULL,1,NULL,1,TRUE),
(50,'Aw21-01034','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.3.4',2010304,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01034','http://www.tanaguru.org/en/content/aw21-rule-1-3-4',3,NULL,1,NULL,1,TRUE),
(51,'Aw21-01035','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.3.5',2010305,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01035','http://www.tanaguru.org/en/content/aw21-rule-1-3-5',3,NULL,1,NULL,1,TRUE),
(52,'Aw21-01036','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.3.6',2010306,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01036','http://www.tanaguru.org/en/content/aw21-rule-1-3-6',3,NULL,1,NULL,1,TRUE),
(53,'Aw21-01041','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.4.1',2010401,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01041','http://www.tanaguru.org/en/content/aw21-rule-1-4-1',4,NULL,1,NULL,1,TRUE),
(54,'Aw21-01042','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.4.2',2010402,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01042','http://www.tanaguru.org/en/content/aw21-rule-1-4-2',4,NULL,1,NULL,1,TRUE),
(55,'Aw21-01043','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.4.3',2010403,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01043','http://www.tanaguru.org/en/content/aw21-rule-1-4-3',4,NULL,1,NULL,1,TRUE),
(56,'Aw21-01044','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.4.4',2010404,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01044','http://www.tanaguru.org/en/content/aw21-rule-1-4-4',4,NULL,1,NULL,1,TRUE),
(57,'Aw21-01045','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.4.5',2010405,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01045','http://www.tanaguru.org/en/content/aw21-rule-1-4-5',4,NULL,1,NULL,1,TRUE),
(58,'Aw21-01046','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.4.6',2010406,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01046','http://www.tanaguru.org/en/content/aw21-rule-1-4-6',4,NULL,1,NULL,1,TRUE),
(59,'Aw21-01061','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.6.1',2010601,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01061','http://www.tanaguru.org/en/content/aw21-rule-1-6-1',6,NULL,1,NULL,1,TRUE),
(60,'Aw21-01062','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.6.2',2010602,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01062','http://www.tanaguru.org/en/content/aw21-rule-1-6-2',6,NULL,1,NULL,1,TRUE),
(61,'Aw21-01063','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.6.3',2010603,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01063','http://www.tanaguru.org/en/content/aw21-rule-1-6-3',6,NULL,1,NULL,1,TRUE),
(62,'Aw21-01064','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.6.4',2010604,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01064','http://www.tanaguru.org/en/content/aw21-rule-1-6-4',6,NULL,1,NULL,1,TRUE),
(63,'Aw21-01065','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.6.5',2010605,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01065','http://www.tanaguru.org/en/content/aw21-rule-1-6-5',6,NULL,1,NULL,1,TRUE),
(64,'Aw21-01071','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.7.1',2010701,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01071','http://www.tanaguru.org/en/content/aw21-rule-1-7-1',7,NULL,1,NULL,1,TRUE),
(65,'Aw21-01072','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.7.2',2010702,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01072','http://www.tanaguru.org/en/content/aw21-rule-1-7-2',7,NULL,1,NULL,1,TRUE),
(66,'Aw21-01073','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.7.3',2010703,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01073','http://www.tanaguru.org/en/content/aw21-rule-1-7-3',7,NULL,1,NULL,1,TRUE),
(67,'Aw21-01074','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.7.4',2010704,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01074','http://www.tanaguru.org/en/content/aw21-rule-1-7-4',7,NULL,1,NULL,1,TRUE),
(68,'Aw21-01091','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.9.1',2010901,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01091','http://www.tanaguru.org/en/content/aw21-rule-1-9-1',9,NULL,3,NULL,1,TRUE),
(69,'Aw21-01092','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.9.2',2010902,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01092','http://www.tanaguru.org/en/content/aw21-rule-1-9-2',9,NULL,3,NULL,1,TRUE),
(70,'Aw21-01093','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.9.3',2010903,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01093','http://www.tanaguru.org/en/content/aw21-rule-1-9-3',9,NULL,3,NULL,1,TRUE),
(71,'Aw21-01094','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.9.4',2010904,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01094','http://www.tanaguru.org/en/content/aw21-rule-1-9-4',9,NULL,3,NULL,1,TRUE),
(72,'Aw21-01095','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.9.5',2010905,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01095','http://www.tanaguru.org/en/content/aw21-rule-1-9-5',9,NULL,3,NULL,1,TRUE),
(73,'Aw21-01096','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.9.6',2010906,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01096','http://www.tanaguru.org/en/content/aw21-rule-1-9-6',9,NULL,3,NULL,1,TRUE),
(74,'Aw21-02021','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#cadres','2.2.1',2020201,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule02021','http://www.tanaguru.org/en/content/aw21-rule-2-2-1',11,NULL,1,NULL,1,TRUE),
(75,'Aw21-02022','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#cadres','2.2.2',2020202,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule02022','http://www.tanaguru.org/en/content/aw21-rule-2-2-2',11,NULL,1,NULL,1,TRUE),
(76,'Aw21-01037','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.3.7',2010307,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01037','http://www.tanaguru.org/en/content/aw21-rule-1-3-7',3,NULL,1,NULL,1,TRUE),
(77,'Aw21-01051','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.5.1',2010501,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01052','http://www.tanaguru.org/en/content/aw21-rule-1-5-1',5,NULL,1,NULL,1,TRUE),
(78,'Aw21-01052','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.5.2',2010502,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01081','http://www.tanaguru.org/en/content/aw21-rule-1-5-2',5,NULL,1,NULL,1,TRUE	),
(79,'Aw21-01081','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.8.1',2010801,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01081','http://www.tanaguru.org/en/content/aw21-rule-1-8-1',8,NULL,2,NULL,1,TRUE),
(80,'Aw21-01082','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.8.2',2010802,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01082','http://www.tanaguru.org/en/content/aw21-rule-1-8-2',8,NULL,2,NULL,1,TRUE),
(81,'Aw21-01083','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.8.3',2010803,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01083','http://www.tanaguru.org/en/content/aw21-rule-1-8-3',8,NULL,2,NULL,1,TRUE),
(82,'Aw21-01084','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.8.4',2010804,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01084','http://www.tanaguru.org/en/content/aw21-rule-1-8-4',8,NULL,2,NULL,1,TRUE),
(83,'Aw21-01085','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.8.5',2010805,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01085','http://www.tanaguru.org/en/content/aw21-rule-1-8-5',8,NULL,2,NULL,1,TRUE),
(84,'Aw21-01086','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#images','1.8.6',2010806,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule01086','http://www.tanaguru.org/en/content/aw21-rule-1-8-6',8,NULL,2,NULL,1,TRUE),
(85,'Aw21-03011','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.1.1',2030101,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03011','http://www.tanaguru.org/en/content/aw21-rule-3-1-1',12,NULL,1,NULL,1,TRUE),
(86,'Aw21-03012','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.1.2',2030102,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03012','http://www.tanaguru.org/en/content/aw21-rule-3-1-2',12,NULL,1,NULL,1,TRUE),
(87,'Aw21-03013','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.1.3',2030103,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03013','http://www.tanaguru.org/en/content/aw21-rule-3-1-3',12,NULL,1,NULL,1,TRUE),
(88,'Aw21-03014','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.1.4',2030104,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03014','http://www.tanaguru.org/en/content/aw21-rule-3-1-4',12,NULL,1,NULL,1,TRUE),
(89,'Aw21-03015','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.1.5',2030105,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03015','http://www.tanaguru.org/en/content/aw21-rule-3-1-5',12,NULL,1,NULL,1,TRUE),
(90,'Aw21-03016','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.1.6',2030106,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03016','http://www.tanaguru.org/en/content/aw21-rule-3-1-6',12,NULL,1,NULL,1,TRUE),
(91,'Aw21-03021','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.2.1',2030201,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03021','http://www.tanaguru.org/en/content/aw21-rule-3-2-1',13,NULL,1,NULL,1,TRUE),
(92,'Aw21-03022','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.2.2',2030202,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03022','http://www.tanaguru.org/en/content/aw21-rule-3-2-2',13,NULL,1,NULL,1,TRUE),
(93,'Aw21-03023','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.2.3',2030203,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03023','http://www.tanaguru.org/en/content/aw21-rule-3-2-3',13,NULL,1,NULL,1,TRUE),
(94,'Aw21-03024','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.2.4',2030204,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03024','http://www.tanaguru.org/en/content/aw21-rule-3-2-4',13,NULL,1,NULL,1,TRUE),
(95,'Aw21-03025','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.2.5',2030205,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03025','http://www.tanaguru.org/en/content/aw21-rule-3-2-5',13,NULL,1,NULL,1,TRUE),
(96,'Aw21-03026','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.2.6',2030206,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03026','http://www.tanaguru.org/en/content/aw21-rule-3-2-6',13,NULL,1,NULL,1,TRUE),
(97,'Aw21-03031','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.3.1',2030301,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03031','http://www.tanaguru.org/en/content/aw21-rule-3-3-1',14,NULL,2,NULL,1,TRUE),
(98,'Aw21-03032','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.3.2',2030302,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03032','http://www.tanaguru.org/en/content/aw21-rule-3-3-2',14,NULL,2,NULL,1,TRUE),
(99,'Aw21-03033','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.3.3',2030303,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03033','http://www.tanaguru.org/en/content/aw21-rule-3-3-3',14,NULL,2,NULL,1,TRUE),
(100,'Aw21-03034','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.3.4',2030304,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03034','http://www.tanaguru.org/en/content/aw21-rule-3-3-4',14,NULL,2,NULL,1,TRUE),
(101,'Aw21-03041','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.4.1',2030401,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03041','http://www.tanaguru.org/en/content/aw21-rule-3-4-1',15,NULL,3,NULL,1,TRUE),
(102,'Aw21-03042','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.4.2',2030402,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03042','http://www.tanaguru.org/en/content/aw21-rule-3-4-2',15,NULL,3,NULL,1,TRUE),
(103,'Aw21-03043','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.4.3',2030403,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03043','http://www.tanaguru.org/en/content/aw21-rule-3-4-3',15,NULL,3,NULL,1,TRUE),
(104,'Aw21-03044','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#couleurs','3.4.4',2030404,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule03044','http://www.tanaguru.org/en/content/aw21-rule-3-4-4',15,NULL,3,NULL,1,TRUE),
(105,'Aw21-04011','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.1.1',2040101,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04011','http://www.tanaguru.org/en/content/aw21-rule-4-1-1',16,NULL,1,NULL,1,TRUE),
(106,'Aw21-04012','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.1.2',2040102,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04012','http://www.tanaguru.org/en/content/aw21-rule-4-1-2',16,NULL,1,NULL,1,TRUE),
(107,'Aw21-04013','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.1.3',2040103,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04013','http://www.tanaguru.org/en/content/aw21-rule-4-1-3',16,NULL,1,NULL,1,TRUE),
(108,'Aw21-04014','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.1.4',2040104,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04014','http://www.tanaguru.org/en/content/aw21-rule-4-1-4',16,NULL,1,NULL,1,TRUE),
(109,'Aw21-04021','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.2.1',2040201,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04021','http://www.tanaguru.org/en/content/aw21-rule-4-2-1',17,NULL,1,NULL,1,TRUE),
(110,'Aw21-04022','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.2.2',2040202,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04022','http://www.tanaguru.org/en/content/aw21-rule-4-2-2',17,NULL,1,NULL,1,TRUE),
(111,'Aw21-04023','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.2.3',2040203,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04023','http://www.tanaguru.org/en/content/aw21-rule-4-2-3',17,NULL,1,NULL,1,TRUE),
(112,'Aw21-04031','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.3.1',2040301,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04031','http://www.tanaguru.org/en/content/aw21-rule-4-3-1',18,NULL,1,NULL,1,TRUE),
(113,'Aw21-04041','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.4.1',2040401,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04041','http://www.tanaguru.org/en/content/aw21-rule-4-4-1',19,NULL,1,NULL,1,TRUE),
(114,'Aw21-04051','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.5.1',2040501,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04051','http://www.tanaguru.org/en/content/aw21-rule-4-5-1',20,NULL,1,NULL,1,TRUE),
(115,'Aw21-04052','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.5.2',2040502,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04052','http://www.tanaguru.org/en/content/aw21-rule-4-5-2',20,NULL,1,NULL,1,TRUE),
(116,'Aw21-04053','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.5.3',2040503,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04053','http://www.tanaguru.org/en/content/aw21-rule-4-5-3',20,NULL,1,NULL,1,TRUE),
(117,'Aw21-04061','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.6.1',2040601,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04061','http://www.tanaguru.org/en/content/aw21-rule-4-6-1',21,NULL,2,NULL,1,TRUE),
(118,'Aw21-04062','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.6.2',2040602,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04062','http://www.tanaguru.org/en/content/aw21-rule-4-6-2',21,NULL,2,NULL,1,TRUE),
(119,'Aw21-04071','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.7.1',2040701,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04071','http://www.tanaguru.org/en/content/aw21-rule-4-7-1',22,NULL,2,NULL,1,TRUE),
(120,'Aw21-04081','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.8.1',2040801,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04081','http://www.tanaguru.org/en/content/aw21-rule-4-8-1',23,NULL,2,NULL,1,TRUE),
(121,'Aw21-04082','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.8.2',2040802,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04082','http://www.tanaguru.org/en/content/aw21-rule-4-8-2',23,NULL,2,NULL,1,TRUE),
(122,'Aw21-04091','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.9.1',2040901,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04091','http://www.tanaguru.org/en/content/aw21-rule-4-9-1',24,NULL,3,NULL,1,TRUE),
(123,'Aw21-04092','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.9.2',2040902,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04092','http://www.tanaguru.org/en/content/aw21-rule-4-9-2',24,NULL,3,NULL,1,TRUE),
(124,'Aw21-04101','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.10.1',2041001,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04101','http://www.tanaguru.org/en/content/aw21-rule-4-10-1',25,NULL,3,NULL,1,TRUE),
(125,'Aw21-04102','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.10.2',2041002,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04102','http://www.tanaguru.org/en/content/aw21-rule-4-10-2',25,NULL,3,NULL,1,TRUE),
(126,'Aw21-04111','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.11.1',2041101,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04111','http://www.tanaguru.org/en/content/aw21-rule-4-11-1',26,NULL,3,NULL,1,TRUE),
(127,'Aw21-04112','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.11.2',2041102,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04112','http://www.tanaguru.org/en/content/aw21-rule-4-11-2',26,NULL,3,NULL,1,TRUE),
(128,'Aw21-04121','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.12.1',2041201,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04121','http://www.tanaguru.org/en/content/aw21-rule-4-12-1',27,NULL,3,NULL,1,TRUE),
(129,'Aw21-04122','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.12.2',2041202,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04122','http://www.tanaguru.org/en/content/aw21-rule-4-12-2',27,NULL,3,NULL,1,TRUE),
(130,'Aw21-04131','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.13.1',2041301,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04131','http://www.tanaguru.org/en/content/aw21-rule-4-13-1',28,NULL,3,NULL,1,TRUE),
(131,'Aw21-04132','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.13.2',2041302,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04132','http://www.tanaguru.org/en/content/aw21-rule-4-13-2',28,NULL,3,NULL,1,TRUE),
(132,'Aw21-04133','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.13.3',2041303,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04133','http://www.tanaguru.org/en/content/aw21-rule-4-13-3',28,NULL,3,NULL,1,TRUE),
(133,'Aw21-04141','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.14.1',2041401,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04141','http://www.tanaguru.org/en/content/aw21-rule-4-14-1',29,NULL,3,NULL,1,TRUE),
(134,'Aw21-04142','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.14.2',2041402,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04142','http://www.tanaguru.org/en/content/aw21-rule-4-14-2',29,NULL,3,NULL,1,TRUE),
(135,'Aw21-04151','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.15.1',2041501,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04151','http://www.tanaguru.org/en/content/aw21-rule-4-15-1',30,NULL,1,NULL,1,TRUE),
(136,'Aw21-04152','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.15.2',2041502,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04152','http://www.tanaguru.org/en/content/aw21-rule-4-15-2',30,NULL,1,NULL,1,TRUE),
(137,'Aw21-04161','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.16.1',2041601,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04161','http://www.tanaguru.org/en/content/aw21-rule-4-16-1',31,NULL,1,NULL,1,TRUE),
(138,'Aw21-04162','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.16.2',2041602,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04162','http://www.tanaguru.org/en/content/aw21-rule-4-16-2',31,NULL,1,NULL,1,TRUE),
(139,'Aw21-04171','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.17.1',2041701,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04171','http://www.tanaguru.org/en/content/aw21-rule-4-17-1',32,NULL,1,NULL,1,TRUE),
(140,'Aw21-04181','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.18.1',2041801,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04181','http://www.tanaguru.org/en/content/aw21-rule-4-18-1',33,NULL,1,NULL,1,TRUE),
(141,'Aw21-04191','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.19.1',2041901,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04191','http://www.tanaguru.org/en/content/aw21-rule-4-19-1',34,NULL,3,NULL,1,TRUE),
(142,'Aw21-04201','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.20.1',2042001,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04201','http://www.tanaguru.org/en/content/aw21-rule-4-20-1',35,NULL,1,NULL,1,TRUE),
(143,'Aw21-04202','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.20.2',2042002,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04202','http://www.tanaguru.org/en/content/aw21-rule-4-20-2',35,NULL,1,NULL,1,TRUE),
(144,'Aw21-04203','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.20.3',2042003,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04203','http://www.tanaguru.org/en/content/aw21-rule-4-20-3',35,NULL,1,NULL,1,TRUE),
(145,'Aw21-04211','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.21.1',2042101,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04211','http://www.tanaguru.org/en/content/aw21-rule-4-21-1',36,NULL,1,NULL,1,TRUE),
(146,'Aw21-04212','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.21.2',2042102,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04212','http://www.tanaguru.org/en/content/aw21-rule-4-21-2',36,NULL,1,NULL,1,TRUE),
(147,'Aw21-04221','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#multimedia','4.22.1',2042201,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule04221','http://www.tanaguru.org/en/content/aw21-rule-4-22-1',37,NULL,1,NULL,1,TRUE),
(148,'Aw21-05021','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#tableaux','5.2.1',2050201,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule05021','http://www.tanaguru.org/en/content/aw21-rule-5-2-1',39,NULL,1,NULL,1,TRUE),
(149,'Aw21-05022','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#tableaux','5.2.2',2050202,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule05022','http://www.tanaguru.org/en/content/aw21-rule-5-2-2',39,NULL,1,NULL,1,TRUE),
(150,'Aw21-05031','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#tableaux','5.3.1',2050301,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule05031','http://www.tanaguru.org/en/content/aw21-rule-5-3-1',40,NULL,1,NULL,1,TRUE),
(151,'Aw21-05051','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#tableaux','5.5.1',2050501,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule05051','http://www.tanaguru.org/en/content/aw21-rule-5-5-1',42,NULL,1,NULL,1,TRUE),
(152,'Aw21-05061','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#tableaux','5.6.1',2050601,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule05061','http://www.tanaguru.org/en/content/aw21-rule-5-6-1',43,NULL,1,NULL,1,TRUE),
(153,'Aw21-05062','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#tableaux','5.6.2',2050602,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule05062','http://www.tanaguru.org/en/content/aw21-rule-5-6-2',43,NULL,1,NULL,1,TRUE),
(154,'Aw21-05071','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#tableaux','5.7.1',2050701,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule05071','http://www.tanaguru.org/en/content/aw21-rule-5-7-1',44,NULL,1,NULL,1,TRUE),
(155,'Aw21-05072','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#tableaux','5.7.2',2050702,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule05072','http://www.tanaguru.org/en/content/aw21-rule-5-7-2',44,NULL,1,NULL,1,TRUE),
(156,'Aw21-05073','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#tableaux','5.7.3',2050703,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule05073','http://www.tanaguru.org/en/content/aw21-rule-5-7-3',44,NULL,1,NULL,1,TRUE),
(157,'Aw21-05074','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#tableaux','5.7.4',2050704,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule05074','http://www.tanaguru.org/en/content/aw21-rule-5-7-4',44,NULL,1,NULL,1,TRUE),
(158,'Aw21-05081','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#tableaux','5.8.1',2050801,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule05081','http://www.tanaguru.org/en/content/aw21-rule-5-8-1',45,NULL,1,NULL,1,TRUE),
(159,'Aw21-06014','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.1.4',2060104,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06014','http://www.tanaguru.org/en/content/aw21-rule-6-1-4',46,NULL,1,NULL,1,TRUE),
(160,'Aw21-06034','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.3.4',2060304,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06034','http://www.tanaguru.org/en/content/aw21-rule-6-3-4',48,NULL,3,NULL,1,TRUE),
(161,'Aw21-06044','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.4.4',2060404,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06044','http://www.tanaguru.org/en/content/aw21-rule-6-4-4',49,NULL,1,NULL,1,TRUE),
(162,'Aw21-06051','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.5.1',2060501,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06051','http://www.tanaguru.org/en/content/aw21-rule-6-5-1',50,NULL,1,NULL,1,TRUE),
(163,'Aw21-06052','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.5.2',2060502,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06052','http://www.tanaguru.org/en/content/aw21-rule-6-5-2',50,NULL,1,NULL,1,TRUE),
(164,'Aw21-06053','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#liens','6.5.3',2060503,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule06053','http://www.tanaguru.org/en/content/aw21-rule-6-5-3',50,NULL,1,NULL,1,TRUE),
(165,'Aw21-07011','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#script','7.1.1',2070101,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule07011','http://www.tanaguru.org/en/content/aw21-rule-7-1-1',52,NULL,1,NULL,1,TRUE),
(166,'Aw21-07012','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#script','7.1.2',2070102,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule07012','http://www.tanaguru.org/en/content/aw21-rule-7-1-2',52,NULL,1,NULL,1,TRUE),
(167,'Aw21-07021','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#script','7.2.1',2070201,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule07021','http://www.tanaguru.org/en/content/aw21-rule-7-2-1',53,NULL,1,NULL,1,TRUE),
(168,'Aw21-07022','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#script','7.2.2',2070202,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule07022','http://www.tanaguru.org/en/content/aw21-rule-7-2-2',53,NULL,1,NULL,1,TRUE),
(169,'Aw21-07031','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#script','7.3.1',2070301,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule07031','http://www.tanaguru.org/en/content/aw21-rule-7-3-1',54,NULL,1,NULL,1,TRUE),
(170,'Aw21-07032','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#script','7.3.2',2070302,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule07032','http://www.tanaguru.org/en/content/aw21-rule-7-3-2',54,NULL,1,NULL,1,TRUE),
(171,'Aw21-07033','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#script','7.3.3',2070303,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule07033','http://www.tanaguru.org/en/content/aw21-rule-7-3-3',54,NULL,1,NULL,1,TRUE),
(172,'Aw21-07041','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#script','7.4.1',2070401,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule07041','http://www.tanaguru.org/en/content/aw21-rule-7-4-1',55,NULL,1,NULL,1,TRUE),
(173,'Aw21-07042','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#script','7.4.2',2070402,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule07042','http://www.tanaguru.org/en/content/aw21-rule-7-4-2',55,NULL,1,NULL,1,TRUE),
(174,'Aw21-07061','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#script','7.6.1',2070601,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule07061','http://www.tanaguru.org/en/content/aw21-rule-7-6-1',57,NULL,3,NULL,1,TRUE),
(175,'Aw21-08013','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#elements','8.1.3',2080103,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule08013','http://www.tanaguru.org/en/content/aw21-rule-8-1-3',58,NULL,1,NULL,1,TRUE),
(176,'Aw21-08021','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#elements','8.2.1',2080201,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule08021','http://www.tanaguru.org/en/content/aw21-rule-8-2-1',59,NULL,1,NULL,1,TRUE),
(177,'Aw21-08022','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#elements','8.2.2',2080202,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule08022','http://www.tanaguru.org/en/content/aw21-rule-8-2-2',59,NULL,1,NULL,1,TRUE),
(178,'Aw21-08071','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#elements','8.7.1',2080701,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule08071','http://www.tanaguru.org/en/content/aw21-rule-8-7-1',64,NULL,2,NULL,1,TRUE),
(179,'Aw21-08081','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#elements','8.8.1',2080801,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule08081','http://www.tanaguru.org/en/content/aw21-rule-8-8-1',65,NULL,2,NULL,1,TRUE),
(180,'Aw21-08082','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#elements','8.8.2',2080802,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule08082','http://www.tanaguru.org/en/content/aw21-rule-8-8-2',65,NULL,2,NULL,1,TRUE),
(181,'Aw21-08091','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#elements','8.9.1',2080901,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule08091','http://www.tanaguru.org/en/content/aw21-rule-8-9-1',66,NULL,1,NULL,1,TRUE),
(182,'Aw21-08101','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#elements','8.10.1',2081001,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule08101','http://www.tanaguru.org/en/content/aw21-rule-8-10-1',67,NULL,1,NULL,1,TRUE),
(183,'Aw21-09013','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#structure','9.1.3',2090103,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule09013','http://www.tanaguru.org/en/content/aw21-rule-9-1-3',68,NULL,1,NULL,1,TRUE),
(184,'Aw21-09023','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#structure','9.2.3',2090203,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule09023','http://www.tanaguru.org/en/content/aw21-rule-9-2-3',69,NULL,1,NULL,1,TRUE),
(185,'Aw21-09031','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#structure','9.3.1',2090301,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule09031','http://www.tanaguru.org/en/content/aw21-rule-9-3-1',70,NULL,3,NULL,1,TRUE),
(186,'Aw21-09032','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#structure','9.3.2',2090302,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule09032','http://www.tanaguru.org/en/content/aw21-rule-9-3-2',70,NULL,3,NULL,1,TRUE),
(187,'Aw21-09041','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#structure','9.4.1',2090401,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule09041','http://www.tanaguru.org/en/content/aw21-rule-9-4-1',71,NULL,3,NULL,1,TRUE),
(188,'Aw21-09042','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#structure','9.4.2',2090402,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule09042','http://www.tanaguru.org/en/content/aw21-rule-9-4-2',71,NULL,3,NULL,1,TRUE),
(189,'Aw21-09051','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#structure','9.5.1',2090501,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule09051','http://www.tanaguru.org/en/content/aw21-rule-9-5-1',72,NULL,1,NULL,1,TRUE),
(190,'Aw21-09052','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#structure','9.5.2',2090502,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule09052','http://www.tanaguru.org/en/content/aw21-rule-9-5-2',72,NULL,1,NULL,1,TRUE),
(191,'Aw21-10013','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.1.3',2100103,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10013','http://www.tanaguru.org/en/content/aw21-rule-10-1-3',73,NULL,1,NULL,1,TRUE),
(192,'Aw21-10021','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.2.1',2100201,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10021','http://www.tanaguru.org/en/content/aw21-rule-10-2-1',74,NULL,1,NULL,1,TRUE),
(193,'Aw21-10022','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.2.2',2100202,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10022','http://www.tanaguru.org/en/content/aw21-rule-10-2-2',74,NULL,1,NULL,1,TRUE),
(194,'Aw21-10023','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.2.3',2100203,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10023','http://www.tanaguru.org/en/content/aw21-rule-10-2-3',74,NULL,1,NULL,1,TRUE),
(195,'Aw21-10031','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.3.1',2100301,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10031','http://www.tanaguru.org/en/content/aw21-rule-10-3-1',75,NULL,1,NULL,1,TRUE),
(196,'Aw21-10042','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.4.2',2100402,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10042','http://www.tanaguru.org/en/content/aw21-rule-10-4-2',76,NULL,2,NULL,1,TRUE),
(197,'Aw21-10043','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.4.3',2100403,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10043','http://www.tanaguru.org/en/content/aw21-rule-10-4-3',76,NULL,2,NULL,1,TRUE),
(198,'Aw21-10051','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.5.1',2100501,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10051','http://www.tanaguru.org/en/content/aw21-rule-10-5-1',77,NULL,2,NULL,1,TRUE),
(199,'Aw21-10052','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.5.2',2100502,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10052','http://www.tanaguru.org/en/content/aw21-rule-10-5-2',77,NULL,2,NULL,1,TRUE),
(200,'Aw21-10053','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.5.3',2100503,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10053','http://www.tanaguru.org/en/content/aw21-rule-10-5-3',77,NULL,2,NULL,1,TRUE),
(201,'Aw21-10061','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.6.1',2100601,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10061','http://www.tanaguru.org/en/content/aw21-rule-10-6-1',78,NULL,1,NULL,1,TRUE),
(202,'Aw21-10071','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.7.1',2100701,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10071','http://www.tanaguru.org/en/content/aw21-rule-10-7-1',79,NULL,1,NULL,1,TRUE),
(203,'Aw21-10072','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.7.2',2100702,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10072','http://www.tanaguru.org/en/content/aw21-rule-10-7-2',79,NULL,1,NULL,1,TRUE),
(204,'Aw21-10073','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.7.3',2100703,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10073','http://www.tanaguru.org/en/content/aw21-rule-10-7-3',79,NULL,1,NULL,1,TRUE),
(205,'Aw21-10081','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.8.1',2100801,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10081','http://www.tanaguru.org/en/content/aw21-rule-10-8-1',80,NULL,3,NULL,1,TRUE),
(206,'Aw21-10082','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.8.2',2100802,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10082','http://www.tanaguru.org/en/content/aw21-rule-10-8-2',80,NULL,3,NULL,1,TRUE),
(207,'Aw21-10083','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.8.3',2100803,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10083','http://www.tanaguru.org/en/content/aw21-rule-10-8-3',80,NULL,3,NULL,1,TRUE),
(208,'Aw21-10084','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.8.4',2100804,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10084','http://www.tanaguru.org/en/content/aw21-rule-10-8-4',80,NULL,3,NULL,1,TRUE),
(209,'Aw21-10091','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.9.1',2100901,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10091','http://www.tanaguru.org/en/content/aw21-rule-10-9-1',81,NULL,3,NULL,1,TRUE),
(210,'Aw21-10101','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.10.1',2101001,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10101','http://www.tanaguru.org/en/content/aw21-rule-10-10-1',82,NULL,3,NULL,1,TRUE),
(211,'Aw21-10111','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.11.1',2101101,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10111','http://www.tanaguru.org/en/content/aw21-rule-10-11-1',83,NULL,3,NULL,1,TRUE),
(212,'Aw21-10121','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.12.1',2101201,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10121','http://www.tanaguru.org/en/content/aw21-rule-10-12-1',84,NULL,3,NULL,1,TRUE),
(213,'Aw21-10122','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.12.2',2101202,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10122','http://www.tanaguru.org/en/content/aw21-rule-10-12-2',84,NULL,3,NULL,1,TRUE),
(214,'Aw21-10131','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.13.1',2101301,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10131','http://www.tanaguru.org/en/content/aw21-rule-10-13-1',85,NULL,1,NULL,1,TRUE),
(215,'Aw21-10141','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.14.1',2101401,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10141','http://www.tanaguru.org/en/content/aw21-rule-10-14-1',86,NULL,1,NULL,1,TRUE),
(216,'Aw21-10142','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.14.2',2101402,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10142','http://www.tanaguru.org/en/content/aw21-rule-10-14-2',86,NULL,1,NULL,1,TRUE),
(217,'Aw21-10143','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.14.3',2101403,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10143','http://www.tanaguru.org/en/content/aw21-rule-10-14-3',86,NULL,1,NULL,1,TRUE),
(218,'Aw21-10144','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.14.4',2101404,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10144','http://www.tanaguru.org/en/content/aw21-rule-10-14-4',86,NULL,1,NULL,1,TRUE),
(219,'Aw21-10151','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.15.1',2101501,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10151','http://www.tanaguru.org/en/content/aw21-rule-10-15-1',87,NULL,1,NULL,1,TRUE),
(220,'Aw21-10152','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.15.2',2101502,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10152','http://www.tanaguru.org/en/content/aw21-rule-10-15-2',87,NULL,1,NULL,1,TRUE),
(221,'Aw21-10153','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.15.3',2101503,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10153','http://www.tanaguru.org/en/content/aw21-rule-10-15-3',87,NULL,1,NULL,1,TRUE),
(222,'Aw21-10154','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#presentation','10.15.4',2101504,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule10154','http://www.tanaguru.org/en/content/aw21-rule-10-15-4',87,NULL,1,NULL,1,TRUE),
(223,'Aw21-11021','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.2.1',2110201,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11021','http://www.tanaguru.org/en/content/aw21-rule-11-2-1',89,NULL,1,NULL,1,TRUE),
(224,'Aw21-11022','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.2.2',2110202,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11022','http://www.tanaguru.org/en/content/aw21-rule-11-2-2',89,NULL,1,NULL,1,TRUE),
(225,'Aw21-11031','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.3.1',2110301,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11031','http://www.tanaguru.org/en/content/aw21-rule-11-3-1',90,NULL,2,NULL,1,TRUE),
(226,'Aw21-11032','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.3.2',2110302,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11032','http://www.tanaguru.org/en/content/aw21-rule-11-3-2',90,NULL,2,NULL,1,TRUE),
(227,'Aw21-11041','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.4.1',2110401,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11041','http://www.tanaguru.org/en/content/aw21-rule-11-4-1',91,NULL,1,NULL,1,TRUE),
(228,'Aw21-11051','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.5.1',2110501,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11051','http://www.tanaguru.org/en/content/aw21-rule-11-5-1',92,NULL,1,NULL,1,TRUE),
(229,'Aw21-11071','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.7.1',2110701,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11071','http://www.tanaguru.org/en/content/aw21-rule-11-7-1',94,NULL,1,NULL,1,TRUE),
(230,'Aw21-11081','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.8.1',2110801,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11081','http://www.tanaguru.org/en/content/aw21-rule-11-8-1',95,NULL,1,NULL,1,TRUE),
(231,'Aw21-11083','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.8.3',2110803,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11083','http://www.tanaguru.org/en/content/aw21-rule-11-8-3',95,NULL,1,NULL,1,TRUE),
(232,'Aw21-11091','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.9.1',2110901,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11091','http://www.tanaguru.org/en/content/aw21-rule-11-9-1',96,NULL,1,NULL,1,TRUE),
(233,'Aw21-11101','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.10.1',2111001,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11101','http://www.tanaguru.org/en/content/aw21-rule-11-10-1',97,NULL,1,NULL,1,TRUE),
(234,'Aw21-11102','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.10.2',2111002,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11102','http://www.tanaguru.org/en/content/aw21-rule-11-10-2',97,NULL,1,NULL,1,TRUE),
(235,'Aw21-11103','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.10.3',2111003,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11103','http://www.tanaguru.org/en/content/aw21-rule-11-10-3',97,NULL,1,NULL,1,TRUE),
(236,'Aw21-11111','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.11.1',2111101,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11111','http://www.tanaguru.org/en/content/aw21-rule-11-11-1',98,NULL,2,NULL,1,TRUE),
(237,'Aw21-11112','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.11.2',2111102,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11112','http://www.tanaguru.org/en/content/aw21-rule-11-11-2',98,NULL,2,NULL,1,TRUE),
(238,'Aw21-11121','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.12.1',2111201,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11121','http://www.tanaguru.org/en/content/aw21-rule-11-12-1',99,NULL,2,NULL,1,TRUE),
(239,'Aw21-11122','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.12.2',2111202,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11122','http://www.tanaguru.org/en/content/aw21-rule-11-12-2',99,NULL,2,NULL,1,TRUE),
(240,'Aw21-11131','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.13.1',2111301,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11131','http://www.tanaguru.org/en/content/aw21-rule-11-13-1',100,NULL,3,NULL,1,TRUE),
(241,'Aw21-11132','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.13.2',2111302,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11132','http://www.tanaguru.org/en/content/aw21-rule-11-13-2',100,NULL,3,NULL,1,TRUE),
(242,'Aw21-11141','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.14.1',2111401,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11141','http://www.tanaguru.org/en/content/aw21-rule-11-14-1',101,NULL,3,NULL,1,TRUE),
(243,'Aw21-11142','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.14.2',2111402,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11142','http://www.tanaguru.org/en/content/aw21-rule-11-14-2',101,NULL,3,NULL,1,TRUE),
(244,'Aw21-11151','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#formulaire','11.15.1',2111501,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule11151','http://www.tanaguru.org/en/content/aw21-rule-11-15-1',102,NULL,3,NULL,1,TRUE),
(245,'Aw21-12011','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.1.1',2120101,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12011','http://www.tanaguru.org/en/content/aw21-rule-12-1-1',103,NULL,2,NULL,1,TRUE),
(246,'Aw21-12021','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.2.1',2120201,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12021','http://www.tanaguru.org/en/content/aw21-rule-12-2-1',104,NULL,2,NULL,1,TRUE),
(247,'Aw21-12022','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.2.2',2120202,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12022','http://www.tanaguru.org/en/content/aw21-rule-12-2-2',104,NULL,2,NULL,1,TRUE),
(248,'Aw21-12031','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.3.1',2120301,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12031','http://www.tanaguru.org/en/content/aw21-rule-12-3-1',105,NULL,2,NULL,1,TRUE),
(249,'Aw21-12032','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.3.2',2120302,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12032','http://www.tanaguru.org/en/content/aw21-rule-12-3-2',105,NULL,2,NULL,1,TRUE),
(250,'Aw21-12041','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.4.1',2120401,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12041','http://www.tanaguru.org/en/content/aw21-rule-12-4-1',106,NULL,2,NULL,1,TRUE),
(251,'Aw21-12042','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.4.2',2120402,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12042','http://www.tanaguru.org/en/content/aw21-rule-12-4-2',106,NULL,2,NULL,1,TRUE),
(252,'Aw21-12043','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.4.3',2120403,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12043','http://www.tanaguru.org/en/content/aw21-rule-12-4-3',106,NULL,2,NULL,1,TRUE),
(253,'Aw21-12051','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.5.1',2120501,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12051','http://www.tanaguru.org/en/content/aw21-rule-12-5-1',107,NULL,2,NULL,1,TRUE),
(254,'Aw21-12052','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.5.2',2120502,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12052','http://www.tanaguru.org/en/content/aw21-rule-12-5-2',107,NULL,2,NULL,1,TRUE),
(255,'Aw21-12053','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.5.3',2120503,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12053','http://www.tanaguru.org/en/content/aw21-rule-12-5-3',107,NULL,2,NULL,1,TRUE),
(256,'Aw21-12061','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.6.1',2120601,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12061','http://www.tanaguru.org/en/content/aw21-rule-12-6-1',108,NULL,2,NULL,1,TRUE),
(257,'Aw21-12062','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.6.2',2120602,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12062','http://www.tanaguru.org/en/content/aw21-rule-12-6-2',108,NULL,2,NULL,1,TRUE),
(258,'Aw21-12063','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.6.3',2120603,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12063','http://www.tanaguru.org/en/content/aw21-rule-12-6-3',108,NULL,2,NULL,1,TRUE),
(259,'Aw21-12071','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.7.1',2120701,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12071','http://www.tanaguru.org/en/content/aw21-rule-12-7-1',109,NULL,2,NULL,1,TRUE),
(260,'Aw21-12081','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.8.1',2120801,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12081','http://www.tanaguru.org/en/content/aw21-rule-12-8-1',110,NULL,3,NULL,1,TRUE),
(261,'Aw21-12091','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.9.1',2120901,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12091','http://www.tanaguru.org/en/content/aw21-rule-12-9-1',111,NULL,3,NULL,1,TRUE),
(262,'Aw21-12101','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.10.1',2121001,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12101','http://www.tanaguru.org/en/content/aw21-rule-12-10-1',112,NULL,1,NULL,1,TRUE),
(263,'Aw21-12102','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.10.2',2121002,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12102','http://www.tanaguru.org/en/content/aw21-rule-12-10-2',112,NULL,1,NULL,1,TRUE),
(264,'Aw21-12103','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.10.3',2121003,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12103','http://www.tanaguru.org/en/content/aw21-rule-12-10-3',112,NULL,1,NULL,1,TRUE),
(265,'Aw21-12111','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.11.1',2121101,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12111','http://www.tanaguru.org/en/content/aw21-rule-12-11-1',113,NULL,1,NULL,1,TRUE),
(266,'Aw21-12112','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.11.2',2121102,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12112','http://www.tanaguru.org/en/content/aw21-rule-12-11-2',113,NULL,1,NULL,1,TRUE),
(267,'Aw21-12113','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.11.3',2121103,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12113','http://www.tanaguru.org/en/content/aw21-rule-12-11-3',113,NULL,1,NULL,1,TRUE),
(268,'Aw21-12114','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.11.4',2121104,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12114','http://www.tanaguru.org/en/content/aw21-rule-12-11-4',113,NULL,1,NULL,1,TRUE),
(269,'Aw21-12121','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.12.1',2121201,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12121','http://www.tanaguru.org/en/content/aw21-rule-12-12-1',114,NULL,3,NULL,1,TRUE),
(270,'Aw21-12131','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.13.1',2121301,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12131','http://www.tanaguru.org/en/content/aw21-rule-12-13-1',115,NULL,1,NULL,1,TRUE),
(271,'Aw21-12132','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.13.2',2121302,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12132','http://www.tanaguru.org/en/content/aw21-rule-12-13-2',115,NULL,1,NULL,1,TRUE),
(272,'Aw21-12141','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#navigation','12.14.1',2121401,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule12141','http://www.tanaguru.org/en/content/aw21-rule-12-14-1',116,NULL,1,NULL,1,TRUE),
(273,'Aw21-13011','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.1.1',2130101,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13011','http://www.tanaguru.org/en/content/aw21-rule-13-1-1',117,NULL,1,NULL,1,TRUE),
(274,'Aw21-13012','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.1.2',2130102,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13012','http://www.tanaguru.org/en/content/aw21-rule-13-1-2',117,NULL,1,NULL,1,TRUE),
(275,'Aw21-13013','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.1.3',2130103,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13013','http://www.tanaguru.org/en/content/aw21-rule-13-1-3',117,NULL,1,NULL,1,TRUE),
(276,'Aw21-13014','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.1.4',2130104,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13014','http://www.tanaguru.org/en/content/aw21-rule-13-1-4',117,NULL,1,NULL,1,TRUE),
(277,'Aw21-13021','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.2.1',2130201,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13021','http://www.tanaguru.org/en/content/aw21-rule-13-2-1',118,NULL,1,NULL,1,TRUE),
(278,'Aw21-13022','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.2.2',2130202,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13022','http://www.tanaguru.org/en/content/aw21-rule-13-2-2',118,NULL,1,NULL,1,TRUE),
(279,'Aw21-13023','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.2.3',2130203,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13023','http://www.tanaguru.org/en/content/aw21-rule-13-2-3',118,NULL,1,NULL,1,TRUE),
(280,'Aw21-13031','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.3.1',2130301,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13031','http://www.tanaguru.org/en/content/aw21-rule-13-3-1',119,NULL,1,NULL,1,TRUE),
(281,'Aw21-13041','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.4.1',2130401,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13041','http://www.tanaguru.org/en/content/aw21-rule-13-4-1',120,NULL,3,NULL,1,TRUE),
(282,'Aw21-13051','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.5.1',2130501,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13051','http://www.tanaguru.org/en/content/aw21-rule-13-5-1',121,NULL,3,NULL,1,TRUE),
(283,'Aw21-13061','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.6.1',2130601,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13061','http://www.tanaguru.org/en/content/aw21-rule-13-6-1',122,NULL,1,NULL,1,TRUE),
(284,'Aw21-13062','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.6.2',2130602,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13062','http://www.tanaguru.org/en/content/aw21-rule-13-6-2',122,NULL,1,NULL,1,TRUE),
(285,'Aw21-13063','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.6.3',2130603,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13063','http://www.tanaguru.org/en/content/aw21-rule-13-6-3',122,NULL,1,NULL,1,TRUE),
(286,'Aw21-13071','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.7.1',2130701,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13071','http://www.tanaguru.org/en/content/aw21-rule-13-7-1',123,NULL,1,NULL,1,TRUE),
(287,'Aw21-13081','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.8.1',2130801,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13081','http://www.tanaguru.org/en/content/aw21-rule-13-8-1',124,NULL,1,NULL,1,TRUE),
(288,'Aw21-13091','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.9.1',2130901,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13091','http://www.tanaguru.org/en/content/aw21-rule-13-9-1',125,NULL,3,NULL,1,TRUE),
(289,'Aw21-13101','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.10.1',2131001,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13101','http://www.tanaguru.org/en/content/aw21-rule-13-10-1',126,NULL,3,NULL,1,TRUE),
(290,'Aw21-13111','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.11.1',2131101,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13111','http://www.tanaguru.org/en/content/aw21-rule-13-11-1',127,NULL,1,NULL,1,TRUE),
(291,'Aw21-13121','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.12.1',2131201,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13121','http://www.tanaguru.org/en/content/aw21-rule-13-12-1',128,NULL,1,NULL,1,TRUE),
(292,'Aw21-13131','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.13.1',2131301,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13131','http://www.tanaguru.org/en/content/aw21-rule-13-13-1',129,NULL,3,NULL,1,TRUE),
(293,'Aw21-13141','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.14.1',2131401,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13141','http://www.tanaguru.org/en/content/aw21-rule-13-14-1',130,NULL,3,NULL,1,TRUE),
(294,'Aw21-13151','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.15.1',2131501,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13151','http://www.tanaguru.org/en/content/aw21-rule-13-15-1',131,NULL,1,NULL,1,TRUE),
(295,'Aw21-13152','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.15.2',2131502,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13152','http://www.tanaguru.org/en/content/aw21-rule-13-15-2',131,NULL,1,NULL,1,TRUE),
(296,'Aw21-13153','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.15.3',2131503,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13153','http://www.tanaguru.org/en/content/aw21-rule-13-15-3',131,NULL,1,NULL,1,TRUE),
(297,'Aw21-13154','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.15.4',2131504,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13154','http://www.tanaguru.org/en/content/aw21-rule-13-15-4',131,NULL,1,NULL,1,TRUE),
(298,'Aw21-13161','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.16.1',2131601,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13161','http://www.tanaguru.org/en/content/aw21-rule-13-16-1',132,NULL,3,NULL,1,TRUE),
(299,'Aw21-13162','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.16.2',2131602,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13162','http://www.tanaguru.org/en/content/aw21-rule-13-16-2',132,NULL,3,NULL,1,TRUE),
(300,'Aw21-13163','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.16.3',2131603,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13163','http://www.tanaguru.org/en/content/aw21-rule-13-16-3',132,NULL,3,NULL,1,TRUE),
(301,'Aw21-13164','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.16.4',2131604,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13164','http://www.tanaguru.org/en/content/aw21-rule-13-16-4',132,NULL,3,NULL,1,TRUE),
(302,'Aw21-13171','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.17.1',2131701,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13171','http://www.tanaguru.org/en/content/aw21-rule-13-17-1',133,NULL,1,NULL,1,TRUE),
(303,'Aw21-13172','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.17.2',2131702,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13172','http://www.tanaguru.org/en/content/aw21-rule-13-17-2',133,NULL,1,NULL,1,TRUE),
(304,'Aw21-09014','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#structure','9.1.4',2090104,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule09014','http://www.tanaguru.org/en/content/aw21-rule-9-1-4',68,NULL,1,NULL,1,TRUE),
(305,'Aw21-13015','http://www.braillenet.org/accessibilite/referentiel-aw21/liste-deploye.php#consultation','13.1.5',2130105,1.0,'accessiweb2.1','org.tanaguru.rules.accessiweb21.Aw21Rule13015','http://www.tanaguru.org/en/content/aw21-rule-13-1-5',117,NULL,1,NULL,1,TRUE);


update test set no_process=FALSE WHERE 
cd_test='Aw21-01011' or 
cd_test='Aw21-01012' or 
cd_test='Aw21-01013' or 
cd_test='Aw21-01014' or 
cd_test='Aw21-01021' or 
cd_test='Aw21-01022' or 
cd_test='Aw21-01023' or 
cd_test='Aw21-01024' or 
cd_test='Aw21-01025' or 
cd_test='Aw21-01031' or 
cd_test='Aw21-01032' or 
cd_test='Aw21-01033' or 
cd_test='Aw21-01034' or 
cd_test='Aw21-01035' or 
cd_test='Aw21-01036' or 
cd_test='Aw21-01041' or 
cd_test='Aw21-01042' or 
cd_test='Aw21-01043' or 
cd_test='Aw21-01044' or 
cd_test='Aw21-01045' or 
cd_test='Aw21-01046' or 
cd_test='Aw21-01061' or 
cd_test='Aw21-01062' or 
cd_test='Aw21-01063' or 
cd_test='Aw21-01064' or 
cd_test='Aw21-01065' or 
cd_test='Aw21-01071' or 
cd_test='Aw21-01072' or 
cd_test='Aw21-01073' or 
cd_test='Aw21-01074' or 
cd_test='Aw21-01091' or 
cd_test='Aw21-01092' or 
cd_test='Aw21-01093' or 
cd_test='Aw21-01094' or 
cd_test='Aw21-01095' or 
cd_test='Aw21-01096' or 
cd_test='Aw21-02011' or 
cd_test='Aw21-02012' or 
cd_test='Aw21-02021' or 
cd_test='Aw21-02022' or 
cd_test='Aw21-05011' or 
cd_test='Aw21-05021' or 
cd_test='Aw21-05022' or 
cd_test='Aw21-05031' or 
cd_test='Aw21-05041' or 
cd_test='Aw21-05051' or 
cd_test='Aw21-05061' or 
cd_test='Aw21-05062' or 
cd_test='Aw21-05071' or 
cd_test='Aw21-05072' or 
cd_test='Aw21-05073' or 
cd_test='Aw21-05074' or 
cd_test='Aw21-05081' or 
cd_test='Aw21-06011' or 
cd_test='Aw21-06012' or 
cd_test='Aw21-06013' or 
cd_test='Aw21-06021' or 
cd_test='Aw21-06022' or 
cd_test='Aw21-06023' or 
cd_test='Aw21-06024' or 
cd_test='Aw21-06031' or 
cd_test='Aw21-06032' or 
cd_test='Aw21-06033' or 
cd_test='Aw21-06041' or 
cd_test='Aw21-06042' or 
cd_test='Aw21-06043' or 
cd_test='Aw21-06051' or 
cd_test='Aw21-06052' or 
cd_test='Aw21-06053' or 
cd_test='Aw21-06061' or 
cd_test='Aw21-07051' or 
cd_test='Aw21-08011' or 
cd_test='Aw21-08012' or 
cd_test='Aw21-08031' or 
cd_test='Aw21-08041' or 
cd_test='Aw21-08051' or 
cd_test='Aw21-08061' or 
cd_test='Aw21-08081' or 
cd_test='Aw21-08082' or
cd_test='Aw21-09011' or 
cd_test='Aw21-09012' or 
cd_test='Aw21-09021' or 
cd_test='Aw21-09022' or 
cd_test='Aw21-10011' or 
cd_test='Aw21-10012' or 
cd_test='Aw21-10041' or 
cd_test='Aw21-11011' or 
cd_test='Aw21-11012' or 
cd_test='Aw21-11013' or 
cd_test='Aw21-11021' or 
cd_test='Aw21-11022' or 
cd_test='Aw21-11031' or 
cd_test='Aw21-11041' or 
cd_test='Aw21-11051' or 
cd_test='Aw21-11061' or 
cd_test='Aw21-11071' or 
cd_test='Aw21-11081' or 
cd_test='Aw21-11082' or 
cd_test='Aw21-11083' or 
cd_test='Aw21-11091' or 
cd_test='Aw21-11101' or 
cd_test='Aw21-11102' or 
cd_test='Aw21-11103' or 
cd_test='Aw21-11111' or 
cd_test='Aw21-11112' or 
cd_test='Aw21-11121' or 
cd_test='Aw21-11122' or 
cd_test='Aw21-11131' or 
cd_test='Aw21-11132' or 
cd_test='Aw21-11141' or 
cd_test='Aw21-11142' or 
cd_test='Aw21-11151' or 
cd_test='Aw21-13012' ;


-- Post-data save --
COMMIT;